### ISSUE TITLE
Android Only - Plugin not installed

### ISSUE THREAD

**Issue by cgould16** [thudugala/Plugin.LocalNotification#101]
Hello!

I am using the Android 9.0 that you suggested in the prior issues.  I have the nuGet package installed under my main solution dependencies, but it wont work for android.  The plugin runs fine on iOS.

**Comment by thudugala** [comment]
@cgould16 Can you please attach a sample project ?

**Comment by thudugala** [comment]
@cgould16 Project should target Android framework 10.0+

**Comment by Paulpetta668** [comment]
Hi, I don't know if I can ask here but I have the same problem.

I added the line in the MainActivity.cs:
`NotificationCenter.CreateNotificationChannel();`

Then I created a class to handle notifications:
```
public static void CreaNotifica(String titolo, String contenuto, int id)
        {
            notifica = new NotificationRequest
            {
                BadgeNumber = 1,
                Title = titolo,
                Description = contenuto,
                NotificationId = id,
                //NotifyTime = DateTime.Now.AddSeconds(5),

                Android = 
                {
                    LedColor = 1,   
                },
                iOS =
                {
                    PlayForegroundSound = true,
                }
            };

            /*var notification = new NotificationRequest
            {
                BadgeNumber = 1,
                Description = "Test Description",
                Title = "Notification!",
                ReturningData = "Dummy Data",
                NotificationId = 1337,
                Schedule = new NotificationRequestSchedule { NotifyTime = DateTime.Now.AddSeconds(5) },
            };*/

            NotificationCenter.Current.Show(notifica);
        }

```
![image](https://user-images.githubusercontent.com/48731892/125427941-7b4bde86-3374-4a9f-b938-82d75d09ff5e.png)

It works perfectly on iOS but not on Android, thanks in advance.

**Comment by thudugala** [comment]
@Paulpetta668 can you attach a sample project

**Comment by Paulpetta668** [comment]
> @Paulpetta668 can you attach a sample project

Do I need to upload the project?
