### ISSUE TITLE
Not working on release mode

### ISSUE THREAD

**Issue by alexisVidal29** [thudugala/Plugin.LocalNotification#108]
it doesnt show notifications on release mode, on debug works fine but nothing shows on release

**Comment by thudugala** [comment]
@alexisVidal29 Can you please attach a sample project ?

**Comment by alexisVidal29** [comment]
im using like this, in OnAppearing, on debug it shows with no problem, but on realease simply doesnt show but it runs over there because after that i update a table 
`var notification = new NotificationRequest
                                {
                                    NotificationId = 200,
                                    Title = "Axeso",
                                    Description = mensaje,
                                    ReturningData = "" 
                                };
                                NotificationCenter.Current.Show(notification);`

**Comment by thudugala** [comment]
@alexisVidal29 Can you please verify it with https://github.com/thudugala/Plugin.LocalNotification/tree/master/Sample/NuGet
