### ISSUE TITLE
Button actions feature?

### ISSUE THREAD

**Issue by LeoJHarris** [thudugala/Plugin.LocalNotification#111]
Not sure if this would be outside the scope of this plugin but is it possible to add in button options to a local notification. Such that a user can select an option and then pass the id of the action pressed into NotificationTapped event so that it can be handled in the application?

Abit like this:

![foreground-services-02](https://user-images.githubusercontent.com/5468757/93986874-f8609b00-fdda-11ea-83c0-6bf3227cb6c6.png)

**Comment by mphill** [comment]
I've added support for this, for iOS only at the moment.  

When the app load, there is a new a new RegisterActions method which can be used to register custom notifications actions:

```
          Plugin.LocalNotification.NotificationCenter.RegisterActions("LOCAL_NOTIFICATIONS", // Category identifier, you can register multiple for different action contexts
              new Plugin.LocalNotification.NotificationAction("DONE", "Mark all as done", (notificationId, userData) =>
              {
                 
              }),
              new Plugin.LocalNotification.NotificationAction("SNOOZE", "Snooze", (notificationId, userData) =>
              {
                  
              })
          );
```

Please take a look at https://github.com/mphill/Plugin.LocalNotification/commit/0d1dacca35914e60a86a5108b6a6dd1806a1ad76

If you agree with the approach please let me know and I can add Android.

**Comment by thudugala** [comment]
@LeoJHarris 
FYI

**In Android Category**
Must be one of the predefined notification categories (see the CATEGORY_* constants in Notification) that best describes this notification. May be used by the system for ranking and filtering.

Also, CATEGORY_ values are added in different version of android

**Comment by thudugala** [comment]
@LeoJHarris 
FYI

**In Android Category**
Must be one of the predefined notification categories (see the CATEGORY_* constants in Notification) that best describes this notification. May be used by the system for ranking and filtering.

Also CATEGORY_ values are added in different version of android

**Comment by mphill** [comment]
I pushed some changes that abstract away the use of the string for the category.

**Comment by LeoJHarris** [comment]
@mphill fantastic this will be implemented!

**Comment by thudugala** [comment]
Added support in Version 7.0.0
