### ISSUE TITLE
[BUG] When negating permission the first time on iOS, the app needs to be killed to read new permission gave from the ios settings

### ISSUE THREAD

**Issue by GiampaoloGabba** [thudugala/Plugin.LocalNotification#112]
If i negate notification permissions the first time the `NotificationPlugin` asks for them, and then i go to the iOS settings (while my app is still in background) and allow the notification, the `NotificationPlugin` dont "see" the new permission unless the app is killed and reopened

I think this is due the `static bool _alertsAllowed` always return its value when already sets.
so when we change the permissions while the app is still in memory, the new check will never happen until the app is killed.

I tried this on iOS only, maybe there is the same issue in Android.

i see two options:
- the plugin needs to always check it's permission (at least when the "allow" is "false"

- let us to check and request permission directly in shared code

**Comment by thudugala** [comment]
@GiampaoloGabba If a user say no to notification. Wouldn't this correction keep asking for it ? even user said no.

**Comment by thudugala** [comment]
@GiampaoloGabba Published under v5.0.7
