### ISSUE TITLE
NotificationCenter.Current.Show should return a Bool result

### ISSUE THREAD

**Issue by jmeyerworms** [thudugala/Plugin.LocalNotification#124]
Hi,

if i call NotificationCenter.Current.Show i dont know if the creation was succesfull , for the user to show a error dialog.

a solution:
return a bool value would be great 
more better a enum like value so we can show a error dialog as example no rights, or rights dissmissed for notification.

greets.

**Comment by thudugala** [comment]
Fixed in version 6.0.0
