### ISSUE TITLE
Android: Image support

### ISSUE THREAD

**Issue by Suplanus** [thudugala/Plugin.LocalNotification#130]
**Is your feature request related to a problem? Please describe.**
I would love to add an image to the notification.

**Describe the solution you'd like**
Platform specific implementation, so we can expand this feature with the rich notification in iOS and have no deependings on Android implementation

**Describe alternatives you've considered**
Same as in Android and it would be a property cross platform.

**Additional context**
https://stackoverflow.com/questions/39063942/image-from-attachment-from-local-notification-is-not-shown-in-unnotificationcont
![image](https://user-images.githubusercontent.com/2002916/103476827-52e59c00-4db9-11eb-9526-82d86873d816.png)

**Comment by angelru** [comment]
any update?

**Comment by thudugala** [comment]
Added support for IOS in veriosn 7.0.0

**Comment by thudugala** [comment]
Need add support in Android

**Comment by thudugala** [comment]
added support to android in version 8.0.1
