### ISSUE TITLE
Move to XamarinCommunityToolkit

### ISSUE THREAD

**Issue by maxkoshevoi** [thudugala/Plugin.LocalNotification#132]
Hi, starting from Xamarin 5 there is [XamarinCommunityToolkit](https://github.com/xamarin/XamarinCommunityToolkit) NuGet package that is supported by community and intended to be single stop for all Xamarin needs that isn't included in official NuGets. 

Are there plans to add this package there?

**Comment by thudugala** [comment]
Yes, when time permit

**Comment by LeoJHarris** [comment]
@thudugala can you shed any light on when this might be performed?

**Comment by thudugala** [comment]
@LeoJHarris before getting started, I'm still waiting on version 9 to finalize and also need to write unite test.
