### ISSUE TITLE
Notification tap event not working in Xamarin Forms Shell

### ISSUE THREAD

**Issue by Ezeji** [thudugala/Plugin.LocalNotification#135]
Hi @thudugala , Great efforts you put in through your plugin. 

I discovered the issue earlier raised by @hjavaher still persists for Xamarin Forms Shell with the bug:
I have the NotificationCenter.Current.NotificationTapped += Current_NotificationTapped; in the App.xaml.cs file above the MainPage=new AppShell(); but no matter what I do this event is not triggered when I click on the notifications. As of writing this, I'm on the latest version of everything including ios, xamarin.forms and this plugin.

I followed the setup strictly and all the guides in the documentation for the Nuget package 4.1.4 and I was able to successfully implement a local notification with custom sound in Xamarin Forms Shell but no matter what I do I can't seem to make the tap event work in Shell.

Please your urgent help on this bug will be highly appreciated as my team need to do a quick update on an existing app. Thanks in advance.

**Comment by thudugala** [comment]
@Ezeji Check if you project is using a splash screen, then please look at below wiki link
 https://github.com/thudugala/Plugin.LocalNotification/wiki/Getting-NotificationTapped-to-work-with-splash-screen

**Comment by Ezeji** [comment]
Alright @thudugala, Let me check it out and revert.

Thanks for your efforts.

**Comment by Ezeji** [comment]
Hi @thudugala, thanks for the resource shared.

It worked like charm particularly this article was the plug: https://progrunning.net/best-way-to-create-a-splash-screen-in-xamarin-forms-android-project/

Thumbs up to your team on this plugin.
