### ISSUE TITLE
NotificationTapped not getting called on Android

### ISSUE THREAD

**Issue by michaelconnolly1** [thudugala/Plugin.LocalNotification#136]
I have a similar problem to Issue 32 on Android and when I click on the notification the NotificationTapped method does not get called and instead the app reopens (even though it's already open). However, it works fine on iOS.

Your sample app on Github works and I've tried using all the same versions of .NET, Xamarin Forms, etc in my application but still can't get it to work on Android. I've even tried going back to version 4.1.4 but still can't get it to work.

I've set the method up as:

NotificationCenter.Current.NotificationTapped += OnLocalNotificationTapped;

and the method signature is:

private void OnLocalNotificationTapped(NotificationTappedEventArgs e)

I have even tried preceding the NotificationCenter as:

Plugin.LocalNotification.NotificationCenter.Current.NotificationTapped += OnLocalNotificationTapped;

but this doesn't have any effect.

It seems it's not recognising the method signature on Android (hence why it's not getting called) but why would it then work on iOS? I have used earlier version of the plugin without any difficulty so not sure why I'm having a problem now.

In case this is relevant, I have set up an AlarmReceiver and BootBroadcastReceiver to capture the bootup event to reset the notifications when the phone is switched off and back on. Is this still required with the new version of the plugin?

I notice from another posted issue that having a splash screen may be an issue? I have a splash screen activity with mainlauncher=true if that is relevant?

Any insights would be greatly appreciated,

Michael

**Comment by angelru** [comment]
@michaelconnolly1 

try setting MainActivity as `LaunchMode = LaunchMode.SingleTop`, try putting your SplashScreen as follows:

```
    public class SplashActivity: Activity
     {
         protected override void OnCreate (Bundle savedInstanceState)
         {
             base.OnCreate (savedInstanceState);

             var mainIntent = new Intent (Application.Context, typeof (MainActivity));

             if (Intent.Extras! = null)
             {
                 mainIntent.PutExtras (Intent.Extras);
             }

             mainIntent.SetFlags (ActivityFlags.SingleTop);

             StartActivity (mainIntent);
         }

         protected override void OnResume ()
         {
             base.OnResume ();
         }
     }
```

**Comment by michaelconnolly1** [comment]
Many thanks, changed the splash screen from being a separate activity to being handled by MainActivity and all is working now. So it seemed to be the fact that the Splashscreen activity was the launch activity rather than MainActivity.

**Comment by paullly** [comment]
> Many thanks, changed the splash screen from being a separate activity to being handled by MainActivity and all is working now. So it seemed to be the fact that the Splashscreen activity was the launch activity rather than MainActivity.

I'm actually experiencing the same problem. Could you elaborate on what you changed? Thank you very much.
