### ISSUE TITLE
[Enhancement] Support foreground notification sound on iOS

### ISSUE THREAD

**Issue by Steffenberg** [thudugala/Plugin.LocalNotification#139]
Hey there,
I have an use case where having an option for a notification sound while the app is in foreground on iOS (described here https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/SchedulingandHandlingLocalNotifications.html - "Handling Notifications When Your App Is in the Foreground") is needed.

I made a fork and came up with a simple solution but your guidelines told me to create an issue first, so what do you think?

https://github.com/Steffenberg/Plugin.LocalNotification/tree/add_foreground_sound_option_ios

Best regards

**Comment by thudugala** [comment]
@Steffenberg please do PR. Thanks

**Comment by thudugala** [comment]
Published in Version 6.0.0
