### ISSUE TITLE
Repeat Feature

### ISSUE THREAD

**Issue by psnogi** [thudugala/Plugin.LocalNotification#154]
Hi,
First of all, Fantastic job. It works even if app is closed. 

Can you add extra bit of documentation on how to use the Repeat feature?

For example :

 Repeats = RepeatSwitch.IsToggled ? **NotificationRepeat.TimeInterval**  : NotificationRepeat.No,
                Android =
                {
                    IconName = "my_icon",
                    //AutoCancel = false,
                    //Ongoing = true
                },

I have changed here. But how to define this time interval and what is unit of time interval (seconds/minutes/days)?
There is missing help in your readme.

The enum definition
 /// <summary>
        /// Notification to be delivered after **the specified amount of** time elapses
        /// </summary>
        TimeInterval

**How and where to specify the time and which unit of time (second/minute/hour)?**
I want to repeat it every hour even if app is closed. Can you guide me and add that to documentation?

Issue #2 
When app is closed, the "<-" button beside "tapped" does not do anything.

**Comment by psnogi** [comment]
Part 1 solved!

**Comment by aharwood2** [comment]
I'm using v5.2.0 like this:
```c#
NotificationCenter.Current.Show(new NotificationRequest
{
    Title = "Test 2",
    Repeats = NotificationRepeat.TimeInterval,
    NotifyRepeatInterval = TimeSpanExt.ToTimeSpanExt(TimeSpan.FromHours(4)),
    NotificationId = 998,
    NotifyTime = DateTime.Now.AddHours(1)
});
```

**Comment by thudugala** [comment]
@psnogi Can you please elaborate on Part 2 ?

**Comment by psnogi** [comment]
@thudugala Since app is in closed state, the main app window (where the selection controls are) is closed. 
After tapping, the notification page opens up, but the navigation button does not do anything as there is no "mainpage" to go to.

**Comment by aharwood2** [comment]
@psnogi you mention that "it works even if the app is closed". Presumably you mean paused? If I kill the app completely on Android then the notifications stop working. I presume this is because the library uses WorkManager rather than AlarmManager to handle background notifications? I'm guessing that the former only works if the app is either in the background (paused) or foreground (running) rather than killed (stopped). @thudugala Any plans to use AlarmManager?

**Comment by thudugala** [comment]
https://developer.android.com/reference/androidx/work/package-summary

WorkManager should work even if the app is closed.

But I have some phone manufactures override this. Specially in Huawei phones

**Comment by thudugala** [comment]
@psnogi Added to Documentation 

 https://github.com/thudugala/Plugin.LocalNotification/wiki/Repeat-Notification
