### ISSUE TITLE
Plugin.LocalNotification NotificationTapped event does not work with Prism.DryIoc.Forms on Android 

### ISSUE THREAD

**Issue by maxchu92** [thudugala/Plugin.LocalNotification#156]
**Describe the bug**
I tried using Plugin.LocalNotification in my Prism.Forms.DryIoc project, Notification trigger, channel, receive event, everything works except NotificationTapped event. When a notification is tapped, the app just relaunched. Is there anything I'm doing wrongly, or is there any specific way need to be handled before using local notification on Prism project?

**To Reproduce**
You can refer to my repository: [https://github.com/maxchu92/PrismLocalNotificationBug](https://github.com/maxchu92/PrismLocalNotificationBug)
1. Install NuGet Package of Plugin.LocalNotification [https://github.com/thudugala/Plugin.LocalNotification]
2. Implement Android extra step.
```csharp
public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
{
	protected override void OnCreate(Bundle savedInstanceState)
	{
	        .....
	        // Must create a Notification Channel when API >= 26
                // you can created multiple Notification Channels with different names.
                NotificationCenter.CreateNotificationChannel();		
		.....		
		LoadApplication(new App());
		.....	
		NotificationCenter.NotifyNotificationTapped(Intent);
	}

	protected override void OnNewIntent(Intent intent)
	{
		NotificationCenter.NotifyNotificationTapped(intent);
		base.OnNewIntent(intent);
	}
}
```
3. Implement Tap event in the App.xaml.cs or AnyPage.xaml.cs
```csharp
public partial class App : Application
{
	public App()
	{
		InitializeComponent();

		// Local Notification tap event listener
		NotificationCenter.Current.NotificationTapped += OnLocalNotificationTapped;

		MainPage = new MainPage();
	}
	
	private void OnLocalNotificationTapped(NotificationTappedEventArgs e)
    	{
		Device.BeginInvokeOnMainThread(()=>{
			DisplayAlert("Notification Tapped", e.data, "Done");
		});
	}
}
```
4. Implement Command to trigger a local notification
```csharp
var notification = new NotificationRequest
{
    NotificationId = 100,
    Title = "Test",
    Description = "Test Description",
    ReturningData = "Dummy data", // Returning data when tapped on notification.
    NotifyTime = DateTime.Now.AddSeconds(30) // Used for Scheduling local notification, if not specified notification will show immediately.
};
NotificationCenter.Current.Show(notification);
```

5. Result
- If the app is running while notification is tapped, the app seems like relaunched, or maybe MainPage was launched again.
- If the app is not running while notification is tapped, the app will be launched and nothing else happened.

**Expected behavior**
- If the app is running while notification is tapped, the event should be triggered.
- If the app is not running while notification is tapped, the app will be launched and the event should be triggered.

**Screenshots**
N/A

**Platform (please complete the following information):**
 - OS: Both Android 10 and 11
 - Version: Both 29 and 30 (Target Android version)
 
**Smartphone (please complete the following information):**
 - Device: Android Emulator
 - OS: Tested on Android 8.1 and Android 9.0
 - Version: 27/28

**Additional context**
N/A

**Comment by thudugala** [comment]
@maxchu92 can you have look at https://github.com/thudugala/Plugin.LocalNotification/wiki/Getting-NotificationTapped-to-work-with-splash-screen

**Comment by maxchu92** [comment]
Hi @thudugala . Thanks for replying.

I finally made it work by using the method you provided, with a little bit of extra tweak.

So the code for `OnCreate` from [https://github.com/thudugala/Plugin.LocalNotification/wiki/Getting-NotificationTapped-to-work-with-splash-screen](https://github.com/thudugala/Plugin.LocalNotification/wiki/Getting-NotificationTapped-to-work-with-splash-screen) can be placed in either `OnCreate` or `OnResume` in **SplashActivity.cs.** So if you prefer Prism.Forms methods of putting in `OnResume`, it totally will have no issue.

After adding the code in, the tapped event is finally being recognized, but the app still relaunched, and everytime it relaunch, the number of tapped event being triggered was increased. We need to add `LaunchMode = LaunchMode.SingleTask` onto the Activity attribute declaration of **MainActivity.cs**, to prevent the app from relaunching upon notification tapped.

My code is here, maybe you can add into your documentation in case someone have the same issue.:

### SplashActivity.cs
```
[Activity(Theme = "@style/MainTheme.Splash",
			  MainLauncher = true,
			  NoHistory = true)]
	public class SplashActivity : AppCompatActivity {
		protected override void OnResume() {
			base.OnResume();
			var data = Intent.GetStringExtra(NotificationCenter.ExtraReturnDataAndroid);
			var mainIntent = new Intent(Application.Context, typeof(MainActivity));

			mainIntent.SetFlags(ActivityFlags.SingleTop);
			if (!string.IsNullOrWhiteSpace(data)) {
				mainIntent.PutExtra(NotificationCenter.ExtraReturnDataAndroid, data);
			}

			StartActivity(mainIntent);
		}
	}
```

### MainActivity.cs
```
[Activity(Theme = "@style/MainTheme",
			  LaunchMode = LaunchMode.SingleTask,
			  ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation | ConfigChanges.UiMode | ConfigChanges.ScreenLayout | ConfigChanges.SmallestScreenSize)]
	public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity {
		protected override void OnCreate(Bundle savedInstanceState) {
			TabLayoutResource = Resource.Layout.Tabbar;
			ToolbarResource = Resource.Layout.Toolbar;

			base.OnCreate(savedInstanceState);

			global::Xamarin.Forms.Forms.Init(this, savedInstanceState);

			// Must create a Notification Channel when API >= 26
			// you can created multiple Notification Channels with different names.
			NotificationCenter.CreateNotificationChannel();

			LoadApplication(new App(new AndroidInitializer()));

			NotificationCenter.NotifyNotificationTapped(Intent);
		}


		protected override void OnNewIntent(Intent intent) {
			NotificationCenter.NotifyNotificationTapped(intent);
			base.OnNewIntent(intent);
		}

		public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults) {
			Xamarin.Essentials.Platform.OnRequestPermissionsResult(requestCode, permissions, grantResults);

			base.OnRequestPermissionsResult(requestCode, permissions, grantResults);
		}
	}

	public class AndroidInitializer : IPlatformInitializer {
		public void RegisterTypes(IContainerRegistry containerRegistry) {
			// Register any platform specific implementations
		}
	}
```

**Comment by maxchu92** [comment]
Now I m facing another problem, IF the app was launched by the notification tapped, it will launch and trigger tapped event correctly. But if you schedule a notification, from the app that was launched by the notification tapped and tap the notification without closing the app, the tapped event wont trigger again.

**Comment by thudugala** [comment]
@maxchu92 Documentation updated

**Comment by maxchu92** [comment]
Thank you!
