### ISSUE TITLE
Tapped event wont trigger again.

### ISSUE THREAD

**Issue by thudugala** [thudugala/Plugin.LocalNotification#157]
Now I m facing another problem, IF the app was launched by the notification tapped, it will launch and trigger tapped event correctly. But if you schedule a notification, from the app that was launched by the notification tapped and tap the notification without closing the app, the tapped event wont trigger again.

_Originally posted by @maxchu92 in https://github.com/thudugala/Plugin.LocalNotification/issues/156#issuecomment-841484714_

Steps to recreate
1. Schedule a repeating notification.
2. Wait for notification and tap on it.
3. This will launch the app, do not close the app.
4. Wait for next notification and tap on it. 
5. The tapped event wont trigger again.

**Comment by thudugala** [comment]
@maxchu92 can you please create a sample project to demonstrate this issue ? I'm unable recreate the issue.

**Comment by maxchu92** [comment]
@thudugala I had updated my repository to recreate the issue. You can refer to the video as well.
[https://github.com/maxchu92/PrismLocalNotificationBug](https://github.com/maxchu92/PrismLocalNotificationBug)

**Comment by thudugala** [comment]
@maxchu92 try v9.1.0

**Comment by maxchu92** [comment]
> @maxchu92 try v9.1.0

Sorry for the late response. I just tested the newer version and it works flawlessly. Thank you for your effort!

**Comment by maxchu92** [comment]
> @maxchu92 try v9.1.0

Sorry for the late response. I just tested the newer version. In my case, both `SplashActivity.cs` and `MainActivity,cs` requires `LaunchMode = LaunchMode.SingleTask` in order for everything works. Thank you for your effort!
