### ISSUE TITLE
Missing Methods After Upgrade to 6

### ISSUE THREAD

**Issue by jamsoft** [thudugala/Plugin.LocalNotification#159]
**Describe the bug**

After upgrade method on Android like NotifyNotificationTapped can no longer be found.

I think the documentation needs updating as these methods all seem to have been removed.

**Comment by thudugala** [comment]
@jamsoft method is not removed

https://github.com/thudugala/Plugin.LocalNotification/blob/master/Source/Plugin.LocalNotification/Platform/Droid/NotificationCenter.cs

**Comment by jamsoft** [comment]
Very odd. I must have had some odd compiler issue. Will attempt the upgrade again.

**Comment by thudugala** [comment]
Same as #160
