### ISSUE TITLE
NotificationCenter.CreateNotificationChannel() not found on v6.0.0

### ISSUE THREAD

**Issue by marcominerva** [thudugala/Plugin.LocalNotification#160]
Using Xamarin.Forms v5.0.0.2012, If I add the version 5.2.0 of the package (on all projects of course), I can add this line in the MainActivity.cs of the Android project (API level 29) as stated in the documentation:

`NotificationCenter.CreateNotificationChannel();`

If, however, I update the library to v6.0.0, I obtain the error "'NotificationCenter' does not contain a definition for 'CreateNotificationChannel'"

**Comment by ArunPrakashG** [comment]
It's not removed. 
https://github.com/thudugala/Plugin.LocalNotification/blob/9f68c02c6b00df2dfe96d8a18e70978777f5f51e/Source/Plugin.LocalNotification/Platform/Droid/NotificationCenter.cs#L123

maybe try clearing nuget cache and rebuild ?

**Comment by marcominerva** [comment]
I think the problem is this:

![image](https://user-images.githubusercontent.com/3522534/119801283-d8d7c000-bedd-11eb-9d30-45b76fbee092.png)

This version requires Android v11, while my application uses the v10. Moreover, the .NET Standard version is 2.1, while the Xamarin.Forms project uses v2.0.

**Comment by ArunPrakashG** [comment]
Yeah, i just updated and checked on my project and had the same issue.

**Comment by ArunPrakashG** [comment]
Just added a [PR](https://github.com/thudugala/Plugin.LocalNotification/pull/161) for this issue

**Comment by thudugala** [comment]
@marcominerva 

The reason for using Android version 11

https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/android-api-levels?tabs=windows#framework

> We recommend that you always compile with the latest available Target Framework version

**Comment by marcominerva** [comment]
Ok... But what about the .NET Standard 2.1 requirement?

**Comment by thudugala** [comment]
@marcominerva if you are using Android 10 and above you can user  .NET Standard 2.1, this allows you to use C# language version 8.0

**Comment by marcominerva** [comment]
OK, I have updated the common project to .NET Standard 2.1 and now it works, thank you for your support

**Comment by thudugala** [comment]
@marcominerva no worries

**Comment by jamsoft** [comment]
Hmm ... I cannot get this to compile at all. Even when targetting Android 11.
