### ISSUE TITLE
IconImage does not display icon in the Android 9 notification

### ISSUE THREAD

**Issue by andy-shindey** [thudugala/Plugin.LocalNotification#164]
**Describe the bug**
IconImage atribute does not display icon in the Android 9 notification, it shows a dark gray circle where icon is expected to be displayed

**To Reproduce**
1. Go to sample project on the github
2. Download code and run it
3. Check notification on the Android Simulator
4. Icon is not seen

**Expected behavior**
An icon is expected to be displayed

**Screenshots**
No Screenshots

**Platform (please complete the following information):**
 - OS: Windows 
 - Version 10

**Smartphone (please complete the following information):**
 - Device: Simulator
 - OS: Android
 - Version 9

**Additional context**
none.

**Comment by thudugala** [comment]
@andy-shindey Did you set the IconName ?

**Comment by andy-shindey** [comment]
I did, also I ran your sample unaltered, and I got the same result. No icon could be seen on the notification.
Thank you for the fast turnaround.
I will look at the link you have sent.
