### ISSUE TITLE
Handling notifications that caused the application start

### ISSUE THREAD

**Issue by pikausp** [thudugala/Plugin.LocalNotification#17]
I can use the `NotificationTapped` event to listen to notification interactions while the application is running, however, this event does not get fired when the App had to be started (was not running).

Consider the following scenario. 

1. I schedule a notification to be displayed in an hour. 
2. The user kills the application before the notification is displayed. 
3. The user taps the delayed notification.

When the application starts, I would like to be able to receive data of the notification that caused the application to start so I can i.e display the correct page.

Is that possible?

**Comment by thudugala** [comment]
Yes, tryout the sample app

**Comment by pikausp** [comment]
There was a configuration mistake on my side and that's why I was not receiving the `NotificationTapped`. Thank you for the great plugin!
