### ISSUE TITLE
[feature] Android 12 - Exact alarm permission

### ISSUE THREAD

**Issue by wcoder** [thudugala/Plugin.LocalNotification#171]
Android doc: https://developer.android.com/about/versions/12/behavior-changes-12?hl=cs#exact-alarm-permission

```kt
// Open settings
if (!alarmManager.canScheduleExactAlarms()) {
	startActivityForResult(
		Intent(Settings.ACTION_REQUEST_SCHEDULE_EXACT_ALARM, "package:<package_id>")
	)
}
```

![alarms-and-reminders](https://user-images.githubusercontent.com/766193/122674420-c5b6c800-d1dd-11eb-8cc3-180c0c52d815.png)

**Comment by thudugala** [comment]
Check v9.1.0
