### ISSUE TITLE
NotifyTime is not coming in Plugin.LocalNotification

### ISSUE THREAD

**Issue by Abhamini** [thudugala/Plugin.LocalNotification#172]
var _myNotification = new NotificationRequest
            {
                BadgeNumber = 1,
                Description = "My first Notification",
                Title = "Push Notification",
                ReturningData = "Dummy data",
                NotificationId =12345,
            //Not able to put NotifyTime here
             
            };

**Comment by thudugala** [comment]
@Abhamini documentation fixed 

```CS
var notification = new NotificationRequest
{
    NotificationId = 100,
    Title = "Test",
    Description = "Test Description",
    ReturningData = "Dummy data", // Returning data when tapped on notification.
    Schedule = 
    {
        NotifyTime = DateTime.Now.AddSeconds(30) // Used for Scheduling local notification, if not specified notification will show immediately.
    }
};
NotificationCenter.Current.Show(notification);
```
