### ISSUE TITLE
Regression in v7.0.0 : AndroidOptions Color is not working anymore

### ISSUE THREAD

**Issue by tranb3r** [thudugala/Plugin.LocalNotification#177]
In Plugin.LocalNotification.Platform.Droid.NotificationServiceImpl, I think the code for setting the color is not correct:
```
            if (string.IsNullOrWhiteSpace(request.Android.Color) == false)
            {
                var colorId = Application.Context.Resources?.GetIdentifier(request.Android.Color, "color", Application.Context.PackageName) ?? 0;
                builder.SetColor(colorId);
            }
```
SetColor expects an ARGB int, not a resourceId.
This was working in previous versions so this is a regression in v7.0.0.

Also, why did you do this change ? In the previous version, we were able to set the color value (ARGB int) directly in NotificationRequest, but now if I understand correctly you expect us to use an android resource for it ?

**Comment by thudugala** [comment]
@tranb3r Yes, the expectation is to use a colour in android resource, if it's a custom one, developer need to add it to android resource then use the name of the colour. 

This makes the code more readable.

**Comment by tranb3r** [comment]
@thudugala 
I don't understand how this makes the code more readable, since it means duplicating the color definition that is already done in the cross-platform library (for a xamarin forms application).
Also, why did you remove the bug label ? This code does not work. SetColor expects an ARGB color, not a resourceId.

**Comment by thudugala** [comment]
@tranb3r Have not updated the sample with version 7 yet.

in your experience, is it much more likely to use a custom colour, rather than existing colour definition already in android resources ?
