### ISSUE TITLE
NotificationTappedEventArgs and NotificationReceivedEventArgs not exist

### ISSUE THREAD

**Issue by MarcoSal** [thudugala/Plugin.LocalNotification#185]
**Describe the bug**
i upgraded to version 8 but it tells me they NotificationTappedEventArgs and NotificationReceivedEventArgs don't exist ..

**To Reproduce**
event on app.xaml.cs

Visual Studio 2019 16.10.3
Target Framework: .NET Standard 2.0
Xamarin Forms: 5.0.0.2012

**Comment by thudugala** [comment]
@MarcoSal Sorry documentation is fixed now, it's NotificationEventArgs, NotificationTappedEventArgs and NotificationReceivedEventArgs is renamed to NotificationEventArgs
