### ISSUE TITLE
not install on android

### ISSUE THREAD

**Issue by MarcoSal** [thudugala/Plugin.LocalNotification#186]
**Describe the bug**
8.0.2 it does not install on android. ios and forms ok, android refuses installation.
the only version that works correctly, for me, is 5.2.
I also created a new APP from scratch ...

Gravità	Codice	Descrizione	Progetto	File	Riga	Stato eliminazione
Errore	NU1107	È stato rilevato un conflitto di versioni per Xamarin.AndroidX.Lifecycle.LiveData. Per risolvere questo problema, installare Xamarin.AndroidX.Lifecycle.LiveData 2.3.1 o farvi riferimento direttamente nel progetto etools_platform.Android. 
 etools_platform.Android -> Plugin.LocalNotification 8.0.2 -> Xamarin.AndroidX.Work.Runtime 2.5.0.2 -> Xamarin.AndroidX.Lifecycle.LiveData (>= 2.3.1) 
 etools_platform.Android -> Xamarin.Forms 5.0.0.2083 -> Xamarin.AndroidX.Lifecycle.LiveData (>= 2.2.0.4 && < 2.3.0).	etools_platform.Android	D:\GitHub\etools_platform\etools_platform.Android\etools_platform.Android.csproj	1	

all packages are up to date

Visual Studio 2019 16.10.4
Target Framework: .NET Standard 2.0
Xamarin Forms: 5.0.0.2012

**Comment by MarcoSal** [comment]
after cleaning nuget packages, version 8.0.1 works.
8.0.2 gives the above error ...

**Comment by thudugala** [comment]
@MarcoSal Xamarin.Forms issue

Please look at 

https://github.com/xamarin/Xamarin.Forms/issues/14425 
and 
https://github.com/xamarin/Xamarin.Forms/issues/14417
