### ISSUE TITLE
Documentation in README.md is out of date

### ISSUE THREAD

**Issue by jlchavez** [thudugala/Plugin.LocalNotification#19]
The documentation is out of date, in the Platform Specific Notes section, NotificationCenter has Current property, has no NotificationIconId, etc.

**Comment by thudugala** [comment]
@jichavez you can only access NotificationIconId from Android project.

**Comment by thudugala** [comment]
@jlchavez  Please make sure you are targeting Android framework 9.0+ for Plugin.LocalNotification 3.0 and above
