### ISSUE TITLE
Expiration date

### ISSUE THREAD

**Issue by AldairOrta** [thudugala/Plugin.LocalNotification#191]
It would be nice to have an "Expiration date" where in a certain given date the notification automatically stops or cancel itself through notification ID.

For example:

- Notification starts on 12/12/21 repeats "Daily"
- We add "Expiration date" 12/25/21
- So when it’s the 12/25/21 the notification stops or cancel automatically.
- In 12/26/21 notification will not longer appear and so on

**Comment by thudugala** [comment]
@AldairOrta have you tried NotifyAutoCancelTime ? thsi was added after version 8.0.2

```cs
var notification = new NotificationRequest
{   
    Schedule = 
    {
        NotifyAutoCancelTime 
    }
};
```
