### ISSUE TITLE
Duplicate notifications

### ISSUE THREAD

**Issue by trystanwilcock** [thudugala/Plugin.LocalNotification#192]
I appear to be getting more notifications than I scheduled.

**To Reproduce**
Steps to reproduce the behaviour:
1. Schedule 2 notifications (i.e. 1.30pm and 1.35pm)
2. Cancel all notifications 
3. Reschedule 2 notifications for different times (1.45pm and 1.50pm)

**Expected behavior**
Two notifications; one at 1.45pm and one at 1.50pm.

**Actual behaviour**
Notifications for the first 2, notifications for the second 2. Sometimes notifications are duplicated. One time I ended up with 7 notifications.

**Package:**
 - Version 9.0.0-preview01

**Smartphone:**
 - Device: Google Pixel 2 EMULATED running Android 9
 - Device: Samsung Galaxy S10 PHYSICAL DEVICE running Android 10

**Additional context**
I am scheduling multiple notifications at the same time for every day of the week. For example, if I set a notification for 1.30pm, I am creating a recurring notification for each day of the week for 1.30pm, so that would be 7 recurring notifications in total.

**Comment by thudugala** [comment]
@trystanwilcock can you please check what happened if you cancel one by one rather than cancel all?

**Comment by trystanwilcock** [comment]
It seems to be working on Android, however no notifications are appearing in iOS. I have added the following line to the FinishedLaunching method in AppDelegate in the iOS project but they are still not appearing:

Plugin.LocalNotification.NotificationCenter.AskPermission();

**Comment by thudugala** [comment]
@trystanwilcock have you tried changing iOSOptions ?

**Comment by trystanwilcock** [comment]
Which iOS options are you referring to?

**Comment by thudugala** [comment]
@trystanwilcock Can you try new version 9.0.0-preview02, this should fix cancel all.

iOS options
```cs
var notification = new NotificationRequest
{   
    iOS =
    {
        HideForegroundAlert = false,
        PlayForegroundSound = true
    }
};
```

**Comment by thudugala** [comment]
@thudugala please use Version 9.0.0

**Comment by thudugala** [comment]
@trystanwilcock please use Version 9.1.3

**Comment by thudugala** [comment]
@trystanwilcock closing issue, due to no responce.
