### ISSUE TITLE
Repeats

### ISSUE THREAD

**Issue by L10Messi10** [thudugala/Plugin.LocalNotification#196]
**Repeats is gone.
what are the other alternatives for that? It was very useful. Why remove it?

**bring back the Repeats
Please bring back the repeats option.

**Comment by thudugala** [comment]
@L10Messi10 It is not removed it is under Schedule 

var notification = new NotificationRequest
{   
    Schedule = 
    {
        RepeatType = NotificationRepeat.Daily
    }
};
await NotificationCenter.Current.Show(notification);
