### ISSUE TITLE
NotifyNotificationTapped is not found

### ISSUE THREAD

**Issue by Abesoddy** [thudugala/Plugin.LocalNotification#20]
Hello, 

I have this error on the project Xamarin.Froms.Android : 

Error CS0117: 'NotificationCenter' does not contain a definition for 'NotifyNotificationTapped' (CS0117)

Does this come from the plugin or an implementation error?

**Comment by thudugala** [comment]
Hi @Abesoddy, Can you attach a sample project?

**Comment by Abesoddy** [comment]
Hi,

Thank you for your answer, here is a sample : https://github.com/Abesoddy/SampleLocalNotification

**Comment by LeoJHarris** [comment]
I noticed on v3.0.1 all definitions of the localNotification have red squiggly lines and adding the using Plugin.LocalNotification; namespace doesn't resolve it, downgrading to v2.0.7 works fine.

**Comment by LeoJHarris** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'ILocalNotificationService' could not be found (are you missing a using directive or an assembly reference?)	LocalNotification.Sample	C:\Users\Admin\Downloads\Plugin.LocalNotification-master (1)\Plugin.LocalNotification-master\Sample\NuGet v207\Sample\MainPage.xaml.cs	40	Active

**Comment by LeoJHarris** [comment]
If you update the samples that come with this project you notice the same issue. Just update the library to 3.0.1

**Comment by thudugala** [comment]
Incorrect Android framework

![image](https://user-images.githubusercontent.com/4112014/57818275-4e7d0180-77d7-11e9-9bc0-112f72566a41.png)

Project should target Android framework 9.0+ for Plugin.LocalNotification 3.0 and above

![image](https://user-images.githubusercontent.com/4112014/57818332-81bf9080-77d7-11e9-979d-8c7baa0407b9.png)
