### ISSUE TITLE
Unexpected notification behavior on Samsung device

### ISSUE THREAD

**Issue by gaurakshay** [thudugala/Plugin.LocalNotification#201]
**Describe the bug**
The notifications don't appear in the notification area unless you open the app and bring it to the foreground.

**To Reproduce**
Use the library just as described in the wiki. I have attached the sample repro
[Notif.zip](https://github.com/thudugala/Plugin.LocalNotification/files/7100487/Notif.zip)

**Expected behavior**
The notification should appear in the notification bar at the scheduled time.

**Screenshots**
Attaching a video to better show what my observations are:

https://user-images.githubusercontent.com/17280428/131885349-5c954d5b-4f30-42d2-a5bb-f547c547c2f5.mp4

**Platform (please complete the following information):**
 - OS: Android
 - Version 9.0.0 preview 01

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20 FE
 - OS: Android 11
 - Version 30

**Additional context**
I am not sure if this can be categorized as a bug. The notifications work perfectly on Google Pixel 3 XL that I have also conducted tests on using the same repro sample provided above. This seems to be a Samsung OneUI thing. I have tried to change the following settings on the Samsung device so that the notifications work as intended:
1. Allow the notifications to bypass DND (added the app to exceptions list)
2. Disable any battery optimizations for the app (added the app to list of "Never sleeping apps" in background usage limits section)

Are there any other Android settings that I can try to change to see if the notifications come through when scheduled?

**Comment by thudugala** [comment]
@gaurakshay can you use preview 04

**Comment by gaurakshay** [comment]
By uninstalling preview 01 you mean uninstall the app that used preview 01 and then re-install an app using preview 04 right?

**Comment by thudugala** [comment]
Yes, there is a braking change in preview 04

**Comment by thudugala** [comment]
@gaurakshay Version 9.0.0 released

**Comment by gaurakshay** [comment]
So I am not sure what changed between preview 1 and preview 4 but if I install the app on my phone in `Release` configuration, I have to make sure that the linker option is set to  `None` instead of `Link SDK assemblies only`. If the linker is set to `Link SDK assemblies only` I don't receive any notifications. Once I figured this out, now I think I will take version 9 that was just released for a spin on the Samsung S20 FE.

**Comment by gaurakshay** [comment]
After testing with `v9.1.0-preview01`, this issue persists on the Samsung Galaxy S20 FE.

**Comment by gaurakshay** [comment]
How can I help in diagnosing this issue? Please let me know what information you require and I'll do my best to get it to you.

**Comment by thudugala** [comment]
@gaurakshay does it work if you set linker option to None instead of Link SDK assemblies only?

**Comment by gaurakshay** [comment]
Yes, it happens even if the linker is set to None.

**Comment by thudugala** [comment]
@gaurakshay Try 9.1.0-preview02

**Comment by AntAttakk** [comment]
We have a similar problem on v9.0.1, where local notifications are not shown on Android. It seems to be related to the linker, and the workaround for us right now is to tell the linker to skip this plugin:

`<AndroidLinkSkip>Plugin.LocalNotification;Plugin.LocalNotification.Platform.Droid</AndroidLinkSkip>`

**Comment by thudugala** [comment]
@AntAttakk Can you try v9.1.0

**Comment by AntAttakk** [comment]
@thudugala I just tested. It works for us in v9.1.0 without the link skip workaround. Thanks!

**Comment by thudugala** [comment]
@gaurakshay Can you still recreate this issue with Version 9.1.3

**Comment by gaurakshay** [comment]
@thudugala Thank you! I will give it a try!

**Comment by thudugala** [comment]
@gaurakshay Can you please try v9.2.0

**Comment by gaurakshay** [comment]
My observations:

## Setup

### Packages

Xamarin.Forms: 5.0.0.2337
Xamarin.Essentials: 1.7.1
Plugin.LocalNotifications: 9.2.0

### Device

Samsung S20 FE (SM-G781U1/DS)

### Android Version 

Android 12 (One UI 4.0)

### Notifications Scheduled:
```csharp
    nrl.Add(CreateNotificationRequest(
        104456,
        "Morning notification",
        "Morning'",
        "Morning reminder description",
        new DateTime(2022, 02, 18, 09, 00, 00),
        true));
    nrl.Add(CreateNotificationRequest(
        104466,
        "Evening notification",
        "Evenin'",
        "Evening reminder description",
        //new DateTime(2022, 02, 17, 17, 15, 00),
        DateTime.Now.AddMinutes(4),
        true)) ;
    nrl.Add(CreateNotificationRequest(
        104616,
        "Test Notification",
        "Test",
        "Test description",
        DateTime.Now.AddMinutes(2),
        false));
```
Where `CreateNotification` is defined as:
```csharp
    var list = new List<string>
    {
        typeof(NotificationPage).FullName,
        notificationId.ToString(),
        title,
        _tapCount.ToString()
    };
    // No need to use NotificationSerializer, you can use your own one.
    var serializeReturningData = _notificationSerializer.Serialize(list);

    var request = new NotificationRequest
    {
        NotificationId = notificationId,
        Title = title,
        Subtitle = subTitle,
        Description = desc,
        ReturningData = serializeReturningData,
        CategoryType = NotificationCategoryType.Alarm,
        Android =
        {
            Priority = AndroidNotificationPriority.Max
        },
        iOS =
        {
            PlayForegroundSound = true//ForegroundSound.IsToggled
        }
    };

    request.Schedule.NotifyTime = scheduleTime;
    request.Schedule.RepeatType = repeat ? NotificationRepeat.Daily : NotificationRepeat.No;
```

I found that the notifications scheduled pretty soon after the app was deployed and the button was tapped were notified successfully but the notification that I scheduled for this morning (a gap of about 14 hours) didn't go off.

Screenshot showing that the alarms were scheduled:

<img src="https://user-images.githubusercontent.com/17280428/154717955-ebb5306d-807f-4178-b5ce-a7d8a536238a.jpg" width="200" />

Screenshot from this morning showing that the notification didn't go off:

<img src="https://user-images.githubusercontent.com/17280428/154718049-156565c8-d39b-4f8a-acd8-a5643cfee34d.jpg" width="200" />

Here is the sample that I am using:

[XamarinNotifications.zip](https://github.com/thudugala/Plugin.LocalNotification/files/8098557/XamarinNotifications.zip)

Is there anything else that I can test with? I will also monitor and see if the repeat type event that went off successfully last evening goes off this evening too.

**Comment by thudugala** [comment]
@gaurakshay are you testing on real device or on emulator?

**Comment by gaurakshay** [comment]
I am testing on a real device.

**Comment by gaurakshay** [comment]
Could the notifications be effected if the app was was killed by the system? How would it be effected?

**Comment by gaurakshay** [comment]
@thudugala I also added the "com.android.alarm.permission.SET_ALARM" permission in the manifest but that didn't change the outcome. Notification that was supposed to show the next morning didn't show on the physical Samsung S20 FE.

**Comment by gaurakshay** [comment]
@thudugala so I have some positive news to share. In Samsung One UI 4.0 (Android 12) I was able to set the notifications reliably by going into the app details page and setting the battery to "Unrestricted" mode.
<img src="https://user-images.githubusercontent.com/17280428/155803091-e10758a4-94f9-4073-828f-0ae3396f4bd2.jpg" width="200">
<img src="https://user-images.githubusercontent.com/17280428/155803094-b18dc4a1-590a-4965-b615-5520f2cd52c7.jpg" width="200">

Things that I had tried earlier but didn't help:
<img src="https://user-images.githubusercontent.com/17280428/155803095-e59b42c3-e671-4f4a-9210-b76197149176.jpg" width="200">
<img src="https://user-images.githubusercontent.com/17280428/155803096-feff6d9f-7bbe-49ab-86d3-4190729bbe84.jpg" width="200">
