### ISSUE TITLE
Android Notification icon is not shown in Simulator

### ISSUE THREAD

**Issue by mos379** [thudugala/Plugin.LocalNotification#204]
**Describe the bug**
When testing the latest Preview 9v4 I changed the notification Icon to AndroidIcon as described in the wiki.
Only to find out that it is presented as white square in the simulator. 
After ignoring it and actually deploying to a real device I figured out that it is only a problem in the emulator.

**To Reproduce**
Run android simulator

**Expected behavior**
expected to have the selected icon appear

**Screenshots**

**Platform (please complete the following information):**
 - Android V10

**Smartphone (please complete the following information):**
Android emulator windows

**Comment by thudugala** [comment]
If Icon not displaying in notification, white square shown instead
Please follow Google's Design Guidelines https://material.io/design/platform-guidance/android-notifications.html#behavior

**Comment by mos379** [comment]
I did read through this but can'T dfind a reason why it is not presented in the simulator but on the real device

**Comment by thudugala** [comment]
@mos379 Can you please attach a sample project.

**Comment by thudugala** [comment]
@mos379 and @skelt can you please attach a sample project ?

**Comment by thudugala** [comment]
![image](https://user-images.githubusercontent.com/4112014/143733570-efe8e221-21d1-4e11-bcd7-cbab8d86ae5f.png)
