### ISSUE TITLE
Problem to install de Plugin

### ISSUE THREAD

**Issue by AlanFloyd** [thudugala/Plugin.LocalNotification#207]
Hello,

I am trying to install the plugin in Visual Studio for Mac Version 8.10.9 (build 3) and getting the follwing error:

Version conflict detected for Xamarin.AndroidX.Lifecycle.LiveData. Install/reference Xamarin.AndroidX.Lifecycle.LiveData 2.3.1 directly to project avoidfoodwaste.Android to resolve this issue. 
 avoidfoodwaste.Android -> Plugin.LocalNotification 8.0.2 -> Xamarin.AndroidX.Work.Runtime 2.5.0.2 -> Xamarin.AndroidX.Lifecycle.LiveData (>= 2.3.1) 
 avoidfoodwaste.Android -> Xamarin.Forms 5.0.0.2083 -> Xamarin.AndroidX.Lifecycle.LiveData (>= 2.2.0.4 && < 2.3.0).

Any suggestion to solve this issue?

Greetings
Alan

**Comment by mos379** [comment]
Says it right in your message
Install/reference Xamarin.AndroidX.Lifecycle.LiveData 2.3.1 directly to project

**Comment by thudugala** [comment]
@mos379 Thank you

@AlanFloyd Please use version 9.0.0
