### ISSUE TITLE
Notification doesn't show when I installed mobile anti-virus "Avast Mobile Security"

### ISSUE THREAD

**Issue by L10Messi10** [thudugala/Plugin.LocalNotification#210]
**Describe the bug**
When testing out with my physical device without the anti-virus, the notification was fine, it shows, but after installing the anti-virus it doesn't show anymore, and even after uninstalling it the notification just doesn't seem to get triggered anymore

**Platform (please complete the following information):**
 - OS: Android
 - Version 8.1.0

**Additional context**
I think it has something to do with the anti-virus' strict management. But maybe the plug-in can bypass that management just like Facebook App or Messenger App I'm not really sure, I haven't tried it on other devices.

**Comment by L10Messi10** [comment]
I'm closing this since the author is not responding regarding this issue.

**Comment by thudugala** [comment]
@L10Messi10 please attach a sample project and please put all the information you can find related to your device environment
