### ISSUE TITLE
Let the client decide what to do when an exception occurs

### ISSUE THREAD

**Issue by tranb3r** [thudugala/Plugin.LocalNotification#219]
Sometimes, a notification fails to be shown in my app, and I don't know the details of what is happening, because this library is catching exceptions and only returning a boolean.
I know there is a log when an exception is catched, but I don't want to read the device log in my app.
I think it would be better to let the client decide what to do when an exception occurs. The client can either log it, or send it to any tracking sdk the app is using, or simply ignore it.
So, could we add an option to let the client decide if he wants the exception to be catched or not ? Or maybe return an error object containing the exception when it occurs ? 
What do you think ?

**Comment by thudugala** [comment]
@tranb3r yes will start working on it

**Comment by thudugala** [comment]
@tranb3r Try 9.1.0-preview02

```cs
NotificationCenter.NotificationLog += OnNotificationLog;

Private void OnNotificationLog(NotificationLogArgs e)
{

}
```

**Comment by tranb3r** [comment]
Why is it in NotificationCenter instead of INotificationService ?

**Comment by thudugala** [comment]
@tranb3r some of the functionality like  CreateNotificationChannel is at NotificationCenter level.

**Comment by tranb3r** [comment]
Ok. It's fine. Thank you!
