### ISSUE TITLE
Custom Notification Sound

### ISSUE THREAD

**Issue by agusibrahim** [thudugala/Plugin.LocalNotification#22]
**Is your feature request related to a problem? Please describe.**
this Notification plugin is great, but its always using default notification sound. please add feature to custom notification sound each notification

**Describe the solution you'd like**
sound file may stored on res/raw (Android), so in pcl project just input the name of file in NotificationRequest

**Describe alternatives you've considered**
-

**Additional context**
thank you

**Comment by thudugala** [comment]
Released in [3.0.2](https://www.nuget.org/packages/Plugin.LocalNotification/3.0.2)

**Comment by agusibrahim** [comment]
I really appreciate, thank you
