### ISSUE TITLE
[Android] Invalid resource keys for Android.Color will cause notifications to silently fail

### ISSUE THREAD

**Issue by Necrolis** [thudugala/Plugin.LocalNotification#225]
**Describe the bug**
If the Resource name supplied for the `Color` field in the `NotificationRequest.Android` object cannot be found, the notification will silently fail.

**To Reproduce**
1. Modify sample to use a non-existent key other than `colorPrimary`
2. Send notification
3. Wait indefinitely

**Expected behavior**
Either the notification needs to send and ignore the missing resource key, or there needs to be an exception thrown alerting that an invalid key has been used.

**Screenshots**
N/A

**Platform (please complete the following information):**
 - OS: Android
 - Version 10.0

**Smartphone (please complete the following information):**
 - Device: Samsung A21
 - OS: Android 11.0

**Additional context**
The following code in `/Platform/Droid/NotificationServiceImpl.cs` needs to bail on invalid resource id's
```
else if (string.IsNullOrWhiteSpace(request.Android.Color.ResourceName) == false)
{
    var colorResourceId =
        Application.Context.Resources?.GetIdentifier(request.Android.Color.ResourceName, "color",
            Application.Context.PackageName) ?? 0;
    var colorId = Application.Context.GetColor(colorResourceId);
    builder.SetColor(colorId);
}
```

**Comment by thudugala** [comment]
@Necrolis you can now listen to error using event on after version 9.1.0

```cs
NotificationCenter.NotificationLog += NotificationCenter_NotificationLog;

private void NotificationCenter_NotificationLog(NotificationLogArgs e)
{
    Console.WriteLine(e.Message);
    Console.WriteLine(e.Error);
}
```

**Comment by thudugala** [comment]
@Necrolis error will be thrown to the app if shown immediately if scheduled subscribe to NotificationCenter.NotificationLog
