### ISSUE TITLE
Android notification icon

### ISSUE THREAD

**Issue by michaelconnolly1** [thudugala/Plugin.LocalNotification#226]
I am having some problems with the Android notification icon. I have tried icons of different sizes and not all of them appear (in some cases I just get a grey circle). All the ones I have tried have a Build Action of AndroidResource. 

Does the icon have to be of a certain size and should it only be in the drawable folder (and not in the in the mipmap folders)?

**Comment by thudugala** [comment]
If Icon not displaying in notification, white square shown instead

Please follow Google's Design Guidelines https://material.io/design/platform-guidance/android-notifications.html#behavior

**Comment by mos379** [comment]
@thudugala on android 12 I'm getting the white square only when several notifications are grouped, but the notification icon on the items is correctly shown.
which setting do I need to change?

**Comment by fverjan** [comment]
Hello, I have a question. How can i set the Notification icon for Ios? Thank
