### ISSUE TITLE
Foreground notification on iOS with release 9.1.0 not working

### ISSUE THREAD

**Issue by Balu2** [thudugala/Plugin.LocalNotification#231]
Previously I had version 9.0.1 of Plugin.Localnotifications installed.  With that version I was able to receive local notifications when the app was in foreground, background and not started on iOS. 
After the installation of version 9.1.0 I only received notifio=cations when the app was in background or not started. When the app was in foreground no notifications at all.

Xamarin Forms:
Version 5.0.0.2244

Platform:
iOS version 14.8.1

Devive:
iPAD Pro (4e generation)

**Comment by thudugala** [comment]
@masonyc do you have access to a mac to test this issue ?

**Comment by thudugala** [comment]
@Balu2 is 
```cs
request.iOS.HideForegroundAlert = false;
```

**Comment by Balu2** [comment]
@thudugala 

Do I have it set explicitly? In your comments was defined:

       //
        // Summary:
        //     Setting this flag will prevent iOS from displaying the default banner when a
        //     Notification is received in foreground Default is false
        public bool HideForegroundAlert { get; set; }

Therefor I thought it was not neccesary to define it.

**Comment by thudugala** [comment]
@Balu2 can you please try v9.1.2

**Comment by Balu2** [comment]
@thudugala, thanks for new version. I installed version 1.9.2 and everything works as expected.
