### ISSUE TITLE
Notification stucked in PendingNotificationList when Device is in Doze mode

### ISSUE THREAD

**Issue by MrninOFF** [thudugala/Plugin.LocalNotification#239]
**[Propably only Android related issue (Tested on S21, Android 12)]**
Hello,
I have tested many scenarios and I came to conclusion. If I set :
`Schedule = { NotifyTime = ..... }`
And the NotifyTime will be a time, when Device is in Doze mode. Than the notification get "stucked" at PendingNotificationList.
...
Solution would be, if Plugin.LocalNotification automatically check PendingNotificationList after the device leave Doze mode. Than Show all notifications where NotifyTime <= Datetime.Now immediately.
...
Do u have a "best practise" piece of code to share. If any1 already "fixed" that issue ?
Thanks.

**Comment by thudugala** [comment]
Hey @MrninOFF Can you please attach a sample project ?

**Comment by MrninOFF** [comment]
@thudugala I am sorry, but I cant :/ . I use all the latest updates and I follow the Setup guide. No more, no less. 
I can confirm, that NotifyTime works just fine if I use the phone (He dont get to Doze mode cycles). But when I leave my phone on desk for long hours.... Than the issue happen....
I already think of setting up a temporary job scheduler for checking a notificationList to repush them automaticly on 30/40 minute cycle.
To be more specific, I dont use Notification Request Builder ... Should I try ?

**Comment by thudugala** [comment]
@MrninOFF Yes you do not need use Notification Request Builder

**Comment by MrninOFF** [comment]
I created a simple job to check the PendingNotificationList and generate a new notification out of it. Without a NotifyTime.
Did u find out, where could be an issue ? @thudugala 
Simple code:
```
                    // Load undelivered notifications
                    var pendingNotificationList = await NotificationCenter.Current.GetPendingNotificationList();

                    foreach (var pendingNotification in pendingNotificationList.Where(where => where.Schedule.NotifyTime != null && where.Schedule.NotifyTime < DateTime.Now))
                    {
                        // Pending notificationId
                        int pendingNotificationId = pendingNotification.NotificationId;
                        // Edit Pending notification
                        pendingNotification.Schedule = new NotificationRequestSchedule();
                        pendingNotification.NotificationId = 400000 + pendingNotification.NotificationId;
                        // Show notification again
                        var showResult = await NotificationCenter.Current.Show(pendingNotification);
                        if (showResult)
                        {
                            // Remove from Pending list
                            NotificationCenter.Current.Cancel(pendingNotificationId);
                        }
                    }
```
I had test it for a 2 days. It looks good so far.

**Comment by MrninOFF** [comment]
@thudugala Hello, I had found that Samsung has this issue for a long time:
https://eu.community.samsung.com/t5/galaxy-s9-series/delayed-notifications-issue-affecting-all-range-of-samsung/td-p/738070/page/5

**Comment by thudugala** [comment]
@MrninOFF Can you please try v9.2.0 to see if you still get the error.

**Comment by MrninOFF** [comment]
@thudugala Updated ... Let me test it for a few days :) Thanks
