### ISSUE TITLE
NRE on iOS while using 9.1.0

### ISSUE THREAD

**Issue by AndreasReitberger** [thudugala/Plugin.LocalNotification#240]
**Describe the bug**
Since I've updated to 9.1.0, no local notifications are shown anymore. The output gives me following error.

```
2022-01-01 12:49:03.057722+0100 KlipperRemoteControl.iOS[12041:151251] System.NullReferenceException:
Object reference not set to an instance of an object
  at Plugin.LocalNotification.Platform.iOS.LocalNotificationDelegate.WillPresentNotification
(UserNotifications.UNUserNotificationCenter center, UserNotifications.UNNotification notification, System.Action`1[T] completionHandler)
[0x00108] in <fe7d204d65e7467e951920702cd8bc96>:0
```

So I tried to set `HideForegroundAlert = false` on iOS as described here: https://github.com/thudugala/Plugin.LocalNotification/issues/231

However I still get the NRE. This is how I call it.
Using the previous version (9.0.1), this is working.

```cs
  NotificationRequest notification = new()
  {
      NotificationId = _notificationNumber++,
      Title = title,
      Description = message,
      iOS = new iOSOptions()
      {
          HideForegroundAlert = false,
      },
  };
  _ = NotificationCenter.Current.Show(notification);
```

**To Reproduce**
1. Try to show a local notifaction while in foreground

**Expected behavior**
No NRE and the notification should be shown.

**Screenshots**

**Platform (please complete the following information):**
 - OS: iOS
 - Version: 15

**Smartphone (please complete the following information):**
 - Device: SE 2020 (Simulator=
 - OS: 15.0

**Additional context**

**Comment by tranb3r** [comment]
Same issue with 9.1.1

**Comment by tranb3r** [comment]
The test here is not correct:
https://github.com/thudugala/Plugin.LocalNotification/blob/bbd3878a6e53b5328cd6bf0e2e8e8e037472588e/Source/Plugin.LocalNotification/Platform/iOS/LocalNotificationDelegate.cs#L89
```
if (!dictionary.ContainsKey(new NSString(NotificationCenter.ReturnRequestHandled)))
{
    var handled = bool.Parse(dictionary[NotificationCenter.ReturnRequestHandled].ToString());
```
Should probably be
```
if (dictionary.ContainsKey(new NSString(NotificationCenter.ReturnRequestHandled)))
{
    var handled = bool.Parse(dictionary[NotificationCenter.ReturnRequestHandled].ToString());
```
@thudugala Could you please fix it in the next version ? Thank you !

**Comment by thudugala** [comment]
@tranb3r Please try v9.1.2

**Comment by tranb3r** [comment]
> @tranb3r Please try v9.1.2

It works. 
Many thanks for your responsiveness!
