### ISSUE TITLE
FLAG_IMMUTABLE error - Target API-31 S

### ISSUE THREAD

**Issue by thudugala** [thudugala/Plugin.LocalNotification#242]
### Discussed in https://github.com/thudugala/Plugin.LocalNotification/discussions/235

<div type='discussions-op-text'>

<sup>Originally posted by **MrninOFF** December  6, 2021</sup>
Hello, I tried this code ... I end up on with that error:
```
            var notification = new NotificationRequest
            {
                NotificationId = 100,
                Title = "Test",
                Description = "Test Description",
                ReturningData = "Dummy data", 
                Android =
                {
                    PendingIntentFlags = Plugin.LocalNotification.AndroidOption.AndroidPendingIntentFlags.Immutable
                },
                Schedule =
                {
                    NotifyTime = DateTime.Now.AddSeconds(10) 
                }
             };
             await NotificationCenter.Current.Show(notification);
```
_Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.'_

I saw some fixes, but I dont use AndroidX soo I cant try most of them. Thanks</div>

**Comment by thudugala** [comment]
@MrninOFF try v9.1.2

**Comment by MrninOFF** [comment]
@thudugala I tried v9.1.2 but this command ended up in Catch(Exeption e){...} with same massage :(
