### ISSUE TITLE
No local notification after reboot in Android

### ISSUE THREAD

**Issue by Balu2** [thudugala/Plugin.LocalNotification#245]
I integrated the latest Plugin.LocalNotications version 9.1.2 in my Xamarin Forms iOS and - Android app. Everything works as expected when using the app.
When I reboot the device in iOS the local notifications will start again as expected. However in Android this is not the case.
I created a custom BroadcastReceiver, called NotificationsBootReceiver, in which I reset all defined local notifications. This BroadcastReceiver should be started after the Android device is rebooted.
When the device is rebooted, I check with a Toast message if the OnReceive function of the custom BroadcastReceiver is being called. And it is: the earlier defined local notications are correct notification.
However, these notifications are never sent/received, nor seen.
Only when I restart the app, the local notifications are shown again on the correct scheduled time.

Platform 
 - OS: Android
 - Version G981BXXCEUL7 of December 1st 2021

Smartphone
 - Device: Samsung S20
 - OS: Android 
 - Version 

Defined custom BroadcastReceiver:

`[BroadcastReceiver(Enabled = true, Exported = false)]
[IntentFilter(new[] { Intent.ActionBootCompleted })]
public class NotificationsBootReceiver : BroadcastReceiver
{
	public async override void OnReceive(Context context, Intent intent)
	{
		try
		{
			if (intent.Action == "android.intent.action.BOOT_COMPLETED")
			{
				NotificationCenter.CreateNotificationChannel();
				NotificationCenter.NotifyNotificationTapped(intent);

				var deviceService = new Xamarin_Support.Services.DeviceService();
				var custId = deviceService.AppDevice.CustomerId;
				var notificationManager = new xxx_App.Services.NotificationManager(deviceService);
				if (notificationManager != null)
				{
					await notificationManager.Init(custId);
					await notificationManager.SetLocalNotifications();
					var notifications = await NotificationCenter.Current.GetPendingNotificationList();
					foreach (var notificationRequest in notifications)
					{
						Toast.MakeText(Android.App.Application.Context, $"Title: {notificationRequest.Title} Scheduled time: {notificationRequest.Schedule.NotifyTime} Id: {notificationRequest.NotificationId}", ToastLength.Long).Show();
					}
					//Toast.MakeText(Android.App.Application.Context, "LocalNotification registered", ToastLength.Long).Show();
				}
			}
		}
		catch (Exception ex)
		{
			Toast.MakeText(Android.App.Application.Context, "Error in Broadcast Received for app:" + ex.Message, ToastLength.Long).Show();
		}
	}
}`

**Comment by thudugala** [comment]
@Balu2 Can you please try v9.2.0

**Comment by Balu2** [comment]
@thudugala it is working perfectly now. I also had the same problem that the recurring notifications were send later than planned after a reboot. With version 9.2.0 the notifications are sent on time.
