### ISSUE TITLE
Add an option to change the Alarm Type for Android

### ISSUE THREAD

**Issue by fr-memosoft** [thudugala/Plugin.LocalNotification#247]
**Is your feature request related to a problem? Please describe.**
Would like to know if it is possible to have an option to change the AlarmType? For example, AlarmType.RtcWakeup. Currently, the library is [using AlarmType.ElapsedRealtime](https://github.com/thudugala/Plugin.LocalNotification/blob/98ed26d135d46383c07e24dff1a7cca5978adebf/Source/Plugin.LocalNotification/Platform/Droid/NotificationServiceImpl.cs#L216).

**Describe the solution you'd like**
Add an `AlarmType` property to `AndroidOptions` and consume it in `ShowLater()` method. Something like below:

```
public class AndroidOptions
{
    ...
    AlarmType AlarmType { get; set; } = AlarmType.ElapsedRealtime;
}

ShowLater(NotificationRequest request)
{
    ...
    if (Build.VERSION.SdkInt >= BuildVersionCodes.M)
    {
        MyAlarmManager.SetExactAndAllowWhileIdle(request.AlarmType, ...);
    }
    else
    {
        MyAlarmManager.SetExact(request.AlarmType, ...);
    }
    ...
}
```

**Additional context**
If my understanding is correct, AlarmType.ElapsedRealtime is used to trigger the alarm since the device boot time, therefore, using this type, the notification won't show on the expected date and time if he/she changed the system clock. I think for the scenario where we need to trigger the notification based on the system clock, the best option is to use AlarmType.RtcWakeUp.

I am new to the notification so, please let me know if I missed any.

Thank you for this good library!

**Comment by rs-memosoft** [comment]
+1

**Comment by jl-memosoft** [comment]
+1

**Comment by thudugala** [comment]
@fr-memosoft Please try version 9.1.3

**Comment by fr-memosoft** [comment]
@thudugala Seems working fine. Thank you!
