### ISSUE TITLE
how to add notify icon at android ?

### ISSUE THREAD

**Issue by chenjeff622** [thudugala/Plugin.LocalNotification#25]
any sample please?

**Comment by thudugala** [comment]
You can change notification iocn by setting NotificationRequest.Android.IconName

**Comment by chenjeff622** [comment]
how to set NotificationRequest.Android.IconName ?

**Comment by thudugala** [comment]
You only need to do this, if you want to change app icon from getting set as notification icon.

```cs
var notification = new NotificationRequest
{
    NotificationId = 100,
    Title = "Test",
    Description = "Test Description",
    Android =
    {
        IconName = "my_icon.png"
    }
};
NotificationCenter.Current.Show(notification);
```

after that add "my_icon.png" to Android Project Resources/drawable

![image](https://user-images.githubusercontent.com/4112014/59819463-10e23a00-937c-11e9-86b6-4acf619b9ff1.png)

**Comment by chenjeff622** [comment]
thank you  thudugala!
