### ISSUE TITLE
Non-repeating notifications are not re-created after reboot on Android.

### ISSUE THREAD

**Issue by c0ff33-b34n** [thudugala/Plugin.LocalNotification#253]
**Describe the bug**
Non-repeating notifications are not re-created after reboot on Android. So if you scheduled a one-off notification and reboot before that time arrives, the notification is never received.

**To Reproduce**
1. Create a notification with RepeatType = NotificationRepeat.No
2. Reboot the device before that notification is due to be received.
3. Notification is not received

**Expected behavior**
Setting a one-off notification should be received after the device is rebooted, at the time specified when creating the NotificationRequest.

**Platform:**
 - OS: Android
 - Plugin.LocalNotification Version 9.1.3 and prior.

**Smartphone:**
 - Device: Samsung Galaxy A32 Phone
 - Android 11.0
 - API 30.
 - But will occur with any Android device.

**Additional context**

In `BootReciever` after the pending notifications list is retrieved it filters the list using `IsStillActiveForReSchedule()`.

`IsStillActiveForReSchedule() `does not return notifications with `Schedule.RepeatType != NotificationRepeat.No;`

So any one off notifications which were scheduled to arrive after device reboot will not be recreated and won't be received.

In `BootReciever`(Android):

```
var requestList = NotificationRepository.Current.GetPendingList();
...
var activeForReScheduleRequestList = requestList.Where(r => r.IsStillActiveForReSchedule()).ToList();

```
In `NotificationRequest`(Common):

```
internal bool IsStillActiveForReSchedule()
        {
            // NotifyTime does not change for Repeat request
            if (Schedule.NotifyTime is null)
            {
                return false;
            }

            if (Schedule.NotifyAutoCancelTime != null &&
               Schedule.NotifyAutoCancelTime <= DateTime.Now)
            {
                return false;
            }

            return Schedule.RepeatType != NotificationRepeat.No;
        }
```
		
In order for non-repeating notifications to get through this method should return true.
(This could also be used to filter and return notifications that have already passed but are still within the window of `AndroidAllowedDelay` so are re-created and shown immediately when the device is switched on.)

A separate method in NotificationRequest could be created to filter out non repeating notifications to tackle separately. This may be a better option as the method is called `IsStillActiveForReSchedule()`, plus the foreach loop that iterates through `activeForReScheduleRequestList` in `BootReciever` may not be the best place to recreate non-repeating notifications.

**Comment by thudugala** [comment]
@c0ff33-b34n Can you please try version 9.2.0-preview01

**Comment by c0ff33-b34n** [comment]
Hi @thudugala Thanks for the quick changes.

I've done some testing and found a few issues with the changes which affect this and #251. 

For non-repeating notifications, a previously scheduled notification is showed right away after reboot, whether it was set for some time in the future or is within the `AndroidAllowedDelay` in the past. (There is no check to see if the `NotifyTime` is in the future and setting `ShowLater()`, rather than `ShowNow()`, I think it needs to account for both.)

When using a repeating notification, again it seems to send the repeating notification that was due in the future straight after reboot. And it also adds the repeat interval before first checking if the original notification time is in the future.
When testing the repeat notifications on a device the notification was sent straight after reboot and then no further notifications arrived.

I see that the `BootReveiver` class has been removed and everything is now implemented in `ScheduledAlarmReceiver`.

If the class is called when is it was from an `Intent.ActionBootCompleted` it retrieves the whole pending list, `GetPendingList()` and sends each request to `SendNotification()`, or if it was from a scheduled alarm (single notification) that also gets sent to `SendNotification()`.

On reboot for `NotificationRepeat.No` notifications, there appears to be no check to see if the notification is in the future, so all notification times, whether still valid in the Android window (present or past) or in the future are shown right away after reboot not at the originally scheduled time.

The same for repeating notifications, the next notification time is added to the request, without first checking to see if it is in the future, then `ShowNow()` is also called right away. (Calling show now right away would make sense if this was not also being used as the `BootReveiver`, because it would be responding to the alarm not the reboot).

I did an initial quick and dirty fix in my fork which solved the issues (following on from my prior change to the `BootReceiver` before it was updated to 9.2.0-preview01, although it requires further cleanup and optimization. I share it here mainly so you can follow my logic. (You may or may not want to use any of it.)
https://github.com/c0ff33-b34n/Plugin.LocalNotification/commit/974c9335f0f4493fe0480ed5e1076d6428d13a8c

**Comment by thudugala** [comment]
@c0ff33-b34n Can you please try version 9.2.0-preview02

**Comment by c0ff33-b34n** [comment]
Thanks @thudugala 

I've done some testing and found a couple of things.
`AlarmType` and `AllowedDelay` were no longer settable when creating a new `NotificationRequest`.
So I had to set them after. (I'd been using RtcWakeup rather than Rtc, at least while I'm testing.)
`notification.Schedule.Android.AllowedDelay = TimeSpan.FromHours(1); `

I am setting the `AllowedDelay` to allow notifications to come through up to that time after reboot on Android.

However I noticed that this caused an issue with `GetNextNotifyTimeForRepeat()` as you used the value in calculating the `newNotifyTime` for repeat notifications. (I left a note on that line of the commit)

I had a problem with repeating notifications not coming through at all after the initial notification and identified that as being caused by adding `AllowedDelay` in the calculation for the `newNotifyTime`

I noticed that notifications come through early after reboot, which I think is due to the complete phone reboot occurring in just under a minute from when the notification was scheduled to arrive, as you've given a minute window between Now and when the notification is due. When I added extra time to the notification and rebooted early, it came through at the correct time.

**Comment by thudugala** [comment]
@c0ff33-b34n Can you please try version 9.2.0-preview03

**Comment by c0ff33-b34n** [comment]
Thank you @thudugala
I've tested multiple scenarios of rebooting the device and leaving it on using `TimeInterval` repeating notifications and Non-repeating notifications, and all seems to be working well now in 9.2.0-preview03. So I will close this issue and #251 which was interrelated.
