### ISSUE TITLE
Badge count reset not working

### ISSUE THREAD

**Issue by PonyOny** [thudugala/Plugin.LocalNotification#256]
**Describe the bug**
The badge count is not resetting

**To Reproduce**
1. Create a Notification that will set the badge
2. Open the app from background or if closed.

**Expected behavior**
App badge should reset when app is opened

**Platform (please complete the following information):**
 - OS: iOs
 - Version 15.2.1
**Smartphone (please complete the following information):**
 - Device: iphone 7
 - OS: iOs
 - Version 15.2.1

**Additional context**
using the following code will not reset the badge
`public override void WillEnterForeground(UIApplication uiApplication)
 {
     Plugin.LocalNotification.NotificationCenter.ResetApplicationIconBadgeNumber(uiApplication);
}`

Modifying the code like this will clear the badge
`public override void WillEnterForeground(UIApplication uiApplication)
        {
            UIApplication.SharedApplication.ApplicationIconBadgeNumber = 0;
        }`

**Comment by thudugala** [comment]
@PonyOny  can you try 9.2.1-preview01
