### ISSUE TITLE
how to change notification icon in 2.0.7 

### ISSUE THREAD

**Issue by sunnygraphy** [thudugala/Plugin.LocalNotification#26]
I could not change notification icon in Xamarin.forms project.

There is option  android  in 
var notification = new Plugin.LocalNotification.LocalNotification
                {

                    NotificationId = notification_id,
                    Title = body,
                    Description = body,
                    ReturningData = "Dummy data", // Returning data when tapped on notification.
                                               
                    NotifyTime = myDateTime
                };

**Comment by thudugala** [comment]
@sunnygraphy  I would suggest you to update to v4.0.2

https://github.com/thudugala/Plugin.LocalNotification/wiki/How-to-change-notification-icon

if you can't upgrade, look at
https://github.com/thudugala/Plugin.LocalNotification/wiki/Usage-2.0.7#platform-specific-notes
