### ISSUE TITLE
Does the NotificationTapped Event work with a Splash Screen?

### ISSUE THREAD

**Issue by dg2k** [thudugala/Plugin.LocalNotification#265]
I understand this issue was mentioned in the past but couldn't get a definitive answer that works. I have come across @thomasgalliker's suggestion of using [ExtraReturnDataAndroid](https://github.com/thudugala/Plugin.LocalNotification/issues/50) but not clear to me how this addresses the issue.

First of, all work as expected if there is no SplashActivity that precedes the MainActivity, therefore the issue appears to be as a result of having two Activities.

I attempted to keep the equivalent of the SplashActivity in the MainActivity, however I came across new limitations (such as adding dynamic text and animation) that could easily be done with the SplashActivity, but not with the attempted workaround.

While keeping the SplashActivity, is there a workaround for NotificationTapped event triggering to work?

**Comment by aharwood2** [comment]
Still works the same way as it did before as far as I can tell. [The docs](https://github.com/thudugala/Plugin.LocalNotification/wiki/Getting-NotificationTapped-to-work-with-splash-screen) are slightly out of date as the `NotificationCenter.ExtraReturnDataAndroid` key has been renamed to `NotificationCenter.ReturnRequest` by the looks of it but still operates on the same principle. The "Main Launcher" activity (your splash activity) is fired by the system when the notification is tapped then the data just needs to be passed through attached to the intent which launches the main activity afterwards.
