### ISSUE TITLE
.NET MAUI support

### ISSUE THREAD

**Issue by AndreasReitberger** [thudugala/Plugin.LocalNotification#270]
I'm currently try to port my Xamarin.App to donet MAUI.
Do you plan to port this plugin as well?

.NET MAUI should be generally available in April 2022, the first RC should follow this year.

It would be awesome to see this app also working with .NET MAU.
Thank you very much for your package and efforts!

**Comment by pikausp** [comment]
Did you mean it the other way around? RC comes before GA

**Comment by AndreasReitberger** [comment]
Yes, sorry for the mistake. RC seems to be available now.

https://devblogs.microsoft.com/dotnet/dotnet-maui-rc-1/

**Comment by jfversluis** [comment]
Have you verified that this package doesn't work right now? As it's not referencing Forms this might just work. Although it probably does reference Xamarin stuff the only thing that might be required is compile against .NET 6 and fix any breaking changes that result from that.

**Comment by AndreasReitberger** [comment]
Yes, I've tried it. It added some Xamarin.iOS reference, so I thought it's not ready for .NET MAUI due to that.
But I haven't tried further to build it, though.

**Comment by thudugala** [comment]
@AndreasReitberger  @jfversluis @pikausp 

Please try 9.2.1-preview02

**Comment by jfversluis** [comment]
Awesome job!

Seems like something might not be right for iOS. I didn't actually run it yet, but Visual Studio doesn't seem to agree

![image](https://user-images.githubusercontent.com/939291/166896486-6527ff1d-2151-4042-96b3-bb1fbffd055d.png)

**Comment by jfversluis** [comment]
When running on Android and actually trying to schedule a notification I get this 
![image](https://user-images.githubusercontent.com/939291/166904090-be3b9c62-fabd-4682-bb3e-58a7d93a5629.png)

**Comment by jfversluis** [comment]
@AndreasReitberger does it actually work at runtime on Android?

**Comment by AndreasReitberger** [comment]
@jfversluis 
Haven't setup any Android devices yet, so I can't tell if it actually works. I just do not get any build errors if I switch to Android target. Once iOS is working I'll try it at runtime :)

**Comment by thudugala** [comment]
investigating

![image](https://user-images.githubusercontent.com/4112014/167488173-f608b638-93dc-4f13-b5bf-a60c1d7582a9.png)

**Comment by AndreasReitberger** [comment]
@thudugala any update on this?
Thank you!

**Comment by thudugala** [comment]
@AndreasReitberger Can you please try out 9.2.1-preview03?

**Comment by AndreasReitberger** [comment]
@thudugala still the same problem with iOS.

![image](https://user-images.githubusercontent.com/2952443/169072803-dd71425b-d7c9-440f-90dc-837987fe3d65.png)

![image](https://user-images.githubusercontent.com/2952443/169072910-a1793428-607f-40e4-b21c-c53fc6d11411.png)

**Comment by thudugala** [comment]
@AndreasReitberger can you try the sample app for Maui in this repo?

**Comment by AndreasReitberger** [comment]
HI @thudugala 
I just checked the sample app.
I have the same problems on iOS as with my app.

![image](https://user-images.githubusercontent.com/2952443/169483032-d9de845f-febe-4607-beda-de6a03692fa4.png)

![image](https://user-images.githubusercontent.com/2952443/169482939-ddc0f566-ed64-4b24-8245-511703bb7e62.png)

It still says that it's not available on iOS

@jfversluis can you confirm?
Thank you!

**Comment by AndreasReitberger** [comment]
@thudugala 
Still no success.

![image](https://user-images.githubusercontent.com/2952443/169492517-619185a5-2fd0-4e3e-be2b-d11ab5efa5b1.png)
![image](https://user-images.githubusercontent.com/2952443/169493019-5483d6d4-4c96-44bc-9fd2-9b4b2bf3a4da.png)

**Comment by AndreasReitberger** [comment]
Just have forked the project and rebuild the plugin from scratch using the MAUI Library template from VS 2022 Prev.
Still, the same issue comes up.
@jfversluis any thought on this? I'm out of ideas.

**Comment by thudugala** [comment]
@jfversluis @AndreasReitberger will rename NotificationCenter --> LocalNotificationCenter

**Comment by jfversluis** [comment]
Perfect! Excited to have .NET MAUI support for this one! Thanks for all the effort here!

**Comment by AndreasReitberger** [comment]
Seems to be working now. At least I can build the project. I'll do some further functional tests and report back if anything is not working as expected. For this issue, I'll close it because the original issue is fixed :) 

Thank you @thudugala & @jfversluis for getting this package to MAUI so fast 👍🏻
