### ISSUE TITLE
App Background or Sleep support

### ISSUE THREAD

**Issue by quintonv** [thudugala/Plugin.LocalNotification#271]
Scheduling a local notification in a few minutes time works. But once the application has been idle a long time the OS shuts it down. Notifications no longer trigger now and are lost forever.

**Comment by thudugala** [comment]
@quintonv is this an Android issue?

**Comment by quintonv** [comment]
Hi, yes it's an Android issue. From what I read online it started with
android 10 or 11, can't quite remember now.

**Comment by thudugala** [comment]
FYI: https://github.com/thudugala/Plugin.LocalNotification/wiki/Scheduled-Android-notifications
