### ISSUE TITLE
NotificationDismissed event

### ISSUE THREAD

**Issue by tranb3r** [thudugala/Plugin.LocalNotification#274]
We have NotificationTapped and NotificationReceived events in INotificationService.
Would it be possible to add a NotificationDismissed event ? (called when the user swipes a notification to dismiss it)
Or is there a way to do it with the current version ?

Thanks

**Comment by thudugala** [comment]
@tranb3r please try 9.2.1-preview05

**Comment by thudugala** [comment]
```cs
LocalNotificationCenter.Current.NotificationActionTapped += Current_NotificationActionTapped;
```
```cs
private void Current_NotificationActionTapped(NotificationActionEventArgs e)
{
    if(e.IsDismissed)
    {
       // Your code
        return;
    }

    if (e.IsTapped)
    {
       // Your code
        return;
    }
}
```

**Comment by tranb3r** [comment]
Thank you Elvin.

It works when the app is running. However, do you know if it's possible to run some code when a notification is dismissed AND the app is not running (for example, the notification is shown, then the app is killed by the system, and then the user dismisses the notification).

**Comment by thudugala** [comment]
@tranb3r Please try version 10.0.0
