### ISSUE TITLE
No platform plugin found

### ISSUE THREAD

**Issue by sunnygraphy** [thudugala/Plugin.LocalNotification#28]
I install this plugin to PCL and all project in Xamarin.form  without error.
and in Iphone it works well.
But in android I get the following error message.

[Plugin.LocalNotification] No platform plugin found.  Did you install the nuget package in your app project as well?"

What did I  miss  in installation.

Thanks.

**Comment by thudugala** [comment]
Is you android project targeting Android framework 9.0+ ?

*Only support .Net Standard 2 shared projects, does not support Xamarin PCL.

**Comment by sunnygraphy** [comment]
thanks

**Comment by Max87ZA** [comment]
Hi @thudugala , I have similar problem - plugin is throwing same error on Android(not tested with iOS, not necessary). I'm targeting Android API 9.0(API 28), minimal SDK is 4.4(API level 19).
Can you please help me how to solve this error? I installed the package inside shared project and inside Android and iOS separately, I have reference in all .csproj files.
Thank you

**Comment by thudugala** [comment]
@Max87ZA  Can you attach a sample project ?

**Comment by Max87ZA** [comment]
I discovered, that I have problems with Target framework, that is probably main issue why it's not working... Is there any chance to make it work with Target framework set to 8.1 Oreo? Thanks

**Comment by thudugala** [comment]
Sorry, Plugin has a dependency to Xamarin.Android.Arch.Work.Runtime which only support Android 9+

**Comment by cgould16** [comment]
Still running into this issue.  Any tips?
