### ISSUE TITLE
I can't receive the local Notification alert on another phone that has my app installed. Why is this so?

### ISSUE THREAD

**Issue by aproko234** [thudugala/Plugin.LocalNotification#286]
Hi.

The above header refers.

I have been able to test your Plugins.LocalNotifications Sample Project and it is sending out notifications when I am on the MainPage of the phone from where I sent out the message. I have another phone that has the app I am developing and when I send out the notification on the 1st phone, nothing pops up on the 2nd phone. 

Why is this so? Is there a way to resolve? Both phones are online.

Thanks.

**Comment by thudugala** [comment]
@aproko234 Are these Android phones? Have you checked if Notifications are disabled for the App on 2nd phone

**Comment by thudugala** [comment]
@aproko234 This plugin is for local notifications. What you are looking for is Push notification plugin.

**Comment by aproko234** [comment]
Ok.

I have tried implementing several examples from the Microsoft docs but at some point, I start getting this error: “Java.exe” exited with code 1. I am using Visual Studio 2022 with Xamarin.forms.

Then I successfully integrated plugin.FirebasePushNotification unto my app. But, I have tried sending several push notifications to my app (emulator) from the Firebase console all to no avail. I even tried using a plugin (FirebaseNet) to send a Push Notification, yet still no show.

So, do you have a reliable and trusted way I could handle push notifications in my app?

Thanks.

MD Idiake
Chief Promoter of 234Aproko Kia-Kia Lost & Found Service and Goodnewsradio.ng

Sent from Mail for Windows
