### ISSUE TITLE
Preventing Firebase from Receiving Subsequent Messages

### ISSUE THREAD

**Issue by LeeWhite187** [thudugala/Plugin.LocalNotification#290]
**Describe the bug**
Good library, by the way.

In a Xamarin Forms application (iOS, specifically), this library appears to be "taking" the User Notification Center delegate (UNUserNotificationCenter.Current.Delegate) away from the registered Firebase plugin (Plugin.FirebasePushNotification).
This action is preventing the Firebase plugin from receiving remote push notification messages, after a message has been displayed by Plugin.LocalNotification, using its Show() method call.
Subsequent remote notification messages get displayed, by Firebase, just fine.
BUT.
After a local notification is displayed using the Plugin.LocalNotification.NotificationCenter.Current.Show() method, the existing Firebase message event handler no longer triggers for any data messages.

This issue has consistent symptoms with this StackOverflow question: https://stackoverflow.com/questions/71684920/crossfirebasepushnotification-current-onnotificationreceived-event-is-only-execu/72885926#72885926
In which, this same debug message appears when a remote push notification message is sent: "WillPresentNotification: Notification request not found", once data messages are no longer appearing.

The odd thing is that: data-only (no notification payload) push messages can continue to be received, without a problem.
But if a notification payload is included, the notification will display, but the data section will never get passed on to the message received event handler of the Firebase plugin.

**To Reproduce**
I've been able to reliably reproduce this issue by conditionally calling the Show() method call (of Plugin.LocalNotification), and observing remote data message events no longer occurring after the Show() method is called.
This is the same behavior that was noted in the above, stackoverflow page.

From that, I've isolated the problem to this library (Plugin.LocalNotification), by commenting out the Show() method call.
When commented out, all remote push messages (notification and data) are received as expected.
And, once the Show() method call (of Plugin.LocalNotification) is called, no more data received events occur (if a notification is included).

I followed the tutorials to setup and use Plugin.FirebasePushNotification and Plugin.LocalNotification.
With the Show() method of Plugin.LocalNotification commented out, I send multiple push notifications with data to a device, and the are all received, triggering the event handlers as expected.
With the Show() method of Plugin.LocalNotification uncommented (so that it gets called), I send multiple push notifications with data to a device, but only the data from the first message is received.

**Expected behavior**
I expect remote notification and data messages to be received and trigger their configured events, so that data can be received.

**Screenshots**

**Platform (please complete the following information):**
I'm using: 
Plugin.FirebasePushNotification v3.4.25
Plugin.LocalNotification v9.2.0
Xamarin Forms v15.10.0.5
Visual Studio 2022 v17.2.6

**Smartphone (please complete the following information):**
I've seen this occur on iOS 13 and 15.

**Additional context**
None

**Comment by LeeWhite187** [comment]
Currently, I'm doing a workaround to this, by cutting out just the pieces of the local notification functionality that I need, so that there is no code that can take the delegate, UNUserNotificationCenter.Current.Delegate, from the Firebase plugin.
I doubt my workaround/hack-job will do any justice as a fix to your library. But, it it necessary for me to stay on track.

I'm happy to share it, if that helps. But, I have to apologize, ahead of time... I don't expect it to be as elegant as your library.

**Comment by LeeWhite187** [comment]
I came across this post, today, that seems closely related to my problem.
https://bytemeta.vip/repo/thudugala/Plugin.LocalNotification/issues/255

I'll attempt the pre-release and the workaround that you suggested to him, and see how that goes.

**Comment by LeeWhite187** [comment]
As an update, I wasn't able to get both libraries (Plugin.LocalNotification and Plugin.FirebasePushNotification) to work well, together.
I'm falling back to using a simple toast for local notifications, and pulling data elements out of remote push messages in the conventional firebase override.
In the last couple days, I have learned quite a bit about how push messaging is processed, contrary to many of the outdated blogs and instructions I've scoured.
So, I definitely have an appreciation for your effort to create and maintain this library.
I'll revisit using native alerts for local notification events at some point.
By then, I'll have free time to wean myself off of the Firebase solution, and use native APNs, once I get my head around creating a relaible Http/2 client implementation.

Anyways. Thank you for a great library.
I'll close this bug report, for now, as it's not currently holding up my work.

Have a great day!

**Comment by thudugala** [comment]
@LeeWhite187 

Appreciate your effort. 

Let me know when you have time, why https://github.com/thudugala/Plugin.LocalNotification/blob/master/Sample/Direct/LocalNotification.Sample.iOS/CustomUserNotificationCenterDelegate.cs does not help.

```cs
public override bool FinishedLaunching(UIApplication app, NSDictionary options)
{
    global::Xamarin.Forms.Forms.Init();

    // if you want to handel push notifications
    LocalNotificationCenter.SetCustomUserNotificationCenterDelegate(new CustomUserNotificationCenterDelegate());

    // Ask the user for permission to show notifications on iOS 10.0+ at startup.
    // If not asked at startup, user will be asked when showing the first notification.
    LocalNotificationCenter.RequestNotificationPermissionAsync().GetAwaiter().GetResult();

    LoadApplication(new App());

    return base.FinishedLaunching(app, options);
}
```
