### ISSUE TITLE
iOS doesn't work when I add UseLocalNotification() to builder

### ISSUE THREAD

**Issue by zuzannaczaja** [thudugala/Plugin.LocalNotification#293]
**Describe the bug**
My app is crashing when I add UseLocalNotification() function to builder in MauiProgram class.

**To Reproduce**
1. Create project.
2. Add UseLocalNotification() function to builder in MauiProgram class.
	public static MauiApp CreateMauiApp()
	{
		var builder = MauiApp.CreateBuilder();
		builder
			.UseMauiApp<App>()
			.ConfigureFonts(fonts =>
			{
				fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
				fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
			}).UseLocalNotification();

		return builder.Build();
	}
4. Run app.
5. The application won't start.

**Screenshots**
![image](https://user-images.githubusercontent.com/56079308/182773946-a8f8590a-0ce0-44b5-851a-a94e6f616f55.png)

**Platform (please complete the following information):**
 - OS: iOS
 - Version 15.5

**Smartphone (please complete the following information):**
 - Device: iPhone 12 iOS 15.5
 - OS: iOS
 - Version 15.5

**Comment by thudugala** [comment]
@zuzannaczaja 

can try below and remove UseLocalNotification();

```cs
public partial class AppDelegate : : MauiUIApplicationDelegate
{        
        public override bool FinishedLaunching(UIApplication app, NSDictionary options)
        {            
            LocalNotificationCenter.RequestNotificationPermissionAsync().GetAwaiter().GetResult();

            return base.FinishedLaunching(app, options);
        }

	public override void WillEnterForeground(UIApplication uiApplication)
        {
            LocalNotificationCenter.RequestNotificationPermissionAsync().GetAwaiter().GetResult();
            base.WillEnterForeground(uiApplication);
        }
}
```

**Comment by zuzannaczaja** [comment]
> @zuzannaczaja
> 
> can try below and remove UseLocalNotification();
> 
> ```cs
> public partial class AppDelegate :  MauiUIApplicationDelegate
> {        
>         protected override MauiApp CreateMauiApp() => MauiProgram.CreateMauiApp();
> 
>         public override bool FinishedLaunching(UIApplication app, NSDictionary options)
>         {            
>             LocalNotificationCenter.RequestNotificationPermissionAsync().GetAwaiter().GetResult();
> 
>             return base.FinishedLaunching(app, options);
>         }
> 
> 	public override void WillEnterForeground(UIApplication uiApplication)
>         {
>             LocalNotificationCenter.RequestNotificationPermissionAsync().GetAwaiter().GetResult();
>             base.WillEnterForeground(uiApplication);
>         }
> }
> ```

Then there is the same problem

**Comment by thudugala** [comment]
I do not have access to mac now. Will be able to help debug the issue

is so try

```cs
public partial class AppDelegate :  MauiUIApplicationDelegate
{        
        protected override MauiApp CreateMauiApp() => MauiProgram.CreateMauiApp();

        public override async  bool FinishedLaunching(UIApplication app, NSDictionary options)
        {            
            await LocalNotificationCenter.RequestNotificationPermissionAsync();

            return base.FinishedLaunching(app, options);
        }

	public override async void WillEnterForeground(UIApplication uiApplication)
        {
            await LocalNotificationCenter.RequestNotificationPermissionAsync();
            base.WillEnterForeground(uiApplication);
        }
}
```

**Comment by zuzannaczaja** [comment]
> I do not have access to mac now. Will be able to help debug the issue
> 
> is so try
> 
> ```cs
> public partial class AppDelegate :  MauiUIApplicationDelegate
> {        
>         protected override MauiApp CreateMauiApp() => MauiProgram.CreateMauiApp();
> 
>         public override async  bool FinishedLaunching(UIApplication app, NSDictionary options)
>         {            
>             await LocalNotificationCenter.RequestNotificationPermissionAsync();
> 
>             return base.FinishedLaunching(app, options);
>         }
> 
> 	public override async void WillEnterForeground(UIApplication uiApplication)
>         {
>             await LocalNotificationCenter.RequestNotificationPermissionAsync();
>             base.WillEnterForeground(uiApplication);
>         }
> }
> ```

This code doesn't work 
![image](https://user-images.githubusercontent.com/56079308/182779044-a661239e-0aa4-4991-9d58-8e842f7d169d.png)

I changed for this
    public override bool FinishedLaunching(UIApplication app, NSDictionary options)
    {
        LocalNotificationCenter.RequestNotificationPermissionAsync();

        return base.FinishedLaunching(app, options);
    }

    public override async void WillEnterForeground(UIApplication uiApplication)
    {
        await LocalNotificationCenter.RequestNotificationPermissionAsync();
        base.WillEnterForeground(uiApplication);
    }

but It doesn't work either

**Comment by thudugala** [comment]
@mphill will you be able to help?

**Comment by Hashemalrifai** [comment]
I have exactly the same issue, and the workarounds listed above don't work. I hope to see a fix soon, thanks :)

**Comment by thudugala** [comment]
@Hashemalrifai @zuzannaczaja Please try version 10.0.2

**Comment by constantinginga** [comment]
> @Hashemalrifai @zuzannaczaja Please try version 10.0.2

I encountered the same issue. Updating to version 10.0.2 fixes the issue, but the notification doesn't appear at all on the iOS emulator. However, it does work on the Android emulator.

**Comment by thudugala** [comment]
@constantinginga 

can try below and remove **UseLocalNotification();**

```cs
public partial class AppDelegate :  MauiUIApplicationDelegate
{        
        protected override MauiApp CreateMauiApp() => MauiProgram.CreateMauiApp();

        public override bool FinishedLaunching(UIApplication app, NSDictionary options)
        {            
            LocalNotificationCenter.RequestNotificationPermission();

            return base.FinishedLaunching(app, options);
        }

	public override void WillEnterForeground(UIApplication uiApplication)
        {
            LocalNotificationCenter.ResetApplicationIconBadgeNumber(uiApplication);
            base.WillEnterForeground(uiApplication);
        }
}
```

**Comment by constantinginga** [comment]
> @constantinginga
> 
> can try below and remove **UseLocalNotification();**
> 
> ```cs
> public partial class AppDelegate :  MauiUIApplicationDelegate
> {        
>         protected override MauiApp CreateMauiApp() => MauiProgram.CreateMauiApp();
> 
>         public override bool FinishedLaunching(UIApplication app, NSDictionary options)
>         {            
>             LocalNotificationCenter.RequestNotificationPermission();
> 
>             return base.FinishedLaunching(app, options);
>         }
> 
> 	public override void WillEnterForeground(UIApplication uiApplication)
>         {
>             LocalNotificationCenter.ResetApplicationIconBadgeNumber(uiApplication);
>             base.WillEnterForeground(uiApplication);
>         }
> }
> ```

Doesn't seem to work, the notification still doesn't show up.

**Comment by zuzannaczaja** [comment]
> ```cs
>         public override bool FinishedLaunching(UIApplication app, NSDictionary options)
>         {            
>             LocalNotificationCenter.RequestNotificationPermission();
> 
>             return base.FinishedLaunching(app, options);
>         }
> 
> 	public override void WillEnterForeground(UIApplication uiApplication)
>         {
>             LocalNotificationCenter.ResetApplicationIconBadgeNumber(uiApplication);
>             base.WillEnterForeground(uiApplication);
>         }
> ```

I have the same problem.

**Comment by zuzannaczaja** [comment]
> > @constantinginga
> > can try below and remove **UseLocalNotification();**
> > ```cs
> > public partial class AppDelegate :  MauiUIApplicationDelegate
> > {        
> >         protected override MauiApp CreateMauiApp() => MauiProgram.CreateMauiApp();
> > 
> >         public override bool FinishedLaunching(UIApplication app, NSDictionary options)
> >         {            
> >             LocalNotificationCenter.RequestNotificationPermission();
> > 
> >             return base.FinishedLaunching(app, options);
> >         }
> > 
> > 	public override void WillEnterForeground(UIApplication uiApplication)
> >         {
> >             LocalNotificationCenter.ResetApplicationIconBadgeNumber(uiApplication);
> >             base.WillEnterForeground(uiApplication);
> >         }
> > }
> > ```
> 
> Doesn't seem to work, the notification still doesn't show up.




> > @constantinginga
> > can try below and remove **UseLocalNotification();**
> > ```cs
> > public partial class AppDelegate :  MauiUIApplicationDelegate
> > {        
> >         protected override MauiApp CreateMauiApp() => MauiProgram.CreateMauiApp();
> > 
> >         public override bool FinishedLaunching(UIApplication app, NSDictionary options)
> >         {            
> >             LocalNotificationCenter.RequestNotificationPermission();
> > 
> >             return base.FinishedLaunching(app, options);
> >         }
> > 
> > 	public override void WillEnterForeground(UIApplication uiApplication)
> >         {
> >             LocalNotificationCenter.ResetApplicationIconBadgeNumber(uiApplication);
> >             base.WillEnterForeground(uiApplication);
> >         }
> > }
> > ```
> 
> Doesn't seem to work, the notification still doesn't show up.

I have the same problem.

**Comment by claus-lysholm** [comment]
Still not fixed?

**Comment by thudugala** [comment]
Try version 10.0.3
