### ISSUE TITLE
Calling LocalNotificationCenter.RequestNotificationPermissionAsync().GetAwaiter().GetResult() blocks the thread and iOS app launch

### ISSUE THREAD

**Issue by SandipAhluwalia** [thudugala/Plugin.LocalNotification#294]
**Describe the bug**

The Xamarin.Forms setup doc indicates you should call LocalNotificationCenter.RequestNotificationPermissionAsync().GetAwaiter().GetResult() in the FinishedLaunching override, but this blocks the app from loading as the thread is being blocked. Is there a synchronous version of this method if it must be called for iOS apps?

**To Reproduce**

Add:

```
public override bool FinishedLaunching(UIApplication app, NSDictionary options)
        {
            global::Xamarin.Forms.Forms.Init();

            // Ask the user for permission to show notifications on iOS 10.0+ at startup.
            // If not asked at startup, the user will be asked when showing the first notification.
            LocalNotificationCenter.RequestNotificationPermissionAsync().GetAwaiter().GetResult();

            LoadApplication(new App());

            return base.FinishedLaunching(app, options);
        }
```

**Expected behavior**
iOS app to load as normal

**Platform (please complete the following information):**
 - OS: 15.5

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone13]
 - OS: [e.g. iOS15.5]

**Comment by thudugala** [comment]
@SandipAhluwalia, what happens when you try async and await

```cs
public override async bool FinishedLaunching(UIApplication app, NSDictionary options)
{
    global::Xamarin.Forms.Forms.Init();

    // Ask the user for permission to show notifications on iOS 10.0+ at startup.
    // If not asked at startup, the user will be asked when showing the first notification.
    await LocalNotificationCenter.RequestNotificationPermissionAsync();

    LoadApplication(new App());

    return base.FinishedLaunching(app, options);
}
```

**Comment by mphill** [comment]
I ran into this too.  The gist of the issue is that prompt for notification permissions isn't being called on the main thread in iOS.

This would fix it:

```c#
  Xamarin.Forms.Device.BeginInvokeOnMainThread(() =>
  {
      LocalNotificationCenter.RequestNotificationPermissionAsync().GetAwaiter().GetResult();
  });
```

But avoiding `.GetAwaiter().GetResult()` completely is best.  @thudugala  adding async to the overside won't work because the return type will conflict, it would have to be `Task<bool>`

Simply calling `LocalNotificationCenter.RequestNotificationPermissionAsync()` without an await is a totally reasonable solution too.


Please see my comment here: https://github.com/thudugala/Plugin.LocalNotification/issues/257#issuecomment-1214134574

**Comment by thudugala** [comment]
@mphill and @SandipAhluwalia please try version 10.0.2

use LocalNotificationCenter.RequestNotificationPermission()

**Comment by mos379** [comment]
> 	public override void WillEnterForeground(UIApplication uiApplication)
>         {
>             LocalNotificationCenter.ResetApplicationIconBadgeNumber();
>             base.WillEnterForeground(uiApplication);
>         }
should be 

LocalNotificationCenter.ResetApplicationIconBadgeNumber(uiApplication);

**Comment by SandipAhluwalia** [comment]
Hi @thudugala, I can confirm LocalNotificationCenter.RequestNotificationPermission() in v10.0.2 works as expected. Thanks

**Comment by thudugala** [comment]
Thank you @SandipAhluwalia
