### ISSUE TITLE
NotifyTime in the Schedule object is null after creating a notification and run the method GetPendingNotificationList

### ISSUE THREAD

**Issue by hakonn** [thudugala/Plugin.LocalNotification#299]
**Describe the bug**
After I have scheduled a notification and run the method GetPendingNotificationList the NotifyTime in the Schedule object is null.
The bug is in version 10.0.1 and only in release mode. I do not experience the error in debug. 
 
When I roll back to 9.2 everything works fine. 

```
{ 
  "Schedule": 
  {
    ...
    "NotifyRepeatInterval": null,
    "NotifyTime": null,
    "RepeatType": 0
  }
}
```

**To Reproduce**
I have created a repo, which shows the error:
https://github.com/hakonn/LocalNotificationCrashTest/blob/main/src/BlazerWithPluginCrash/Pages/Index.razor 

It must be built in release mode. Debug works fine. 

Example code:

```
var notification = new NotificationRequest
{
	NotificationId = 1000,
	Title = "A fantastic notification",
	Description = "",
        CategoryType = NotificationCategoryType.Alarm,
	Schedule =
	{
      	        NotifyTime = DateTime.Now.AddMinutes(1),
		NotifyRepeatInterval = TimeSpan.FromHours(24),
		RepeatType = NotificationRepeat.TimeInterval
      }
};

await LocalNotificationCenter.Current.Show(notification);

var notifications = await LocalNotificationCenter.Current.GetPendingNotificationList();

//this one is null in release mode
notifications.FirstOrDefault().Schedule.NotifyTime
```

**Expected behavior**
That the NotifyTime is not null. 

**Platform (please complete the following information):**
 - OS: Android
 - Version 12

**Smartphone (please complete the following information):**
 - Device: Sony, Samsung 
 - OS: Android
 - Version 12 

**Additional context**
I'm using the plugin with .Net MAUI Blazer.

**Comment by thudugala** [comment]
@hakonn can you try https://github.com/thudugala/Plugin.LocalNotification/wiki/Switching-Json-Serializer

**Comment by hakonn** [comment]
It worked! Thank you :-) 

But I used the following in the serialize method:
`return JsonConvert.SerializeObject(value);`
