### ISSUE TITLE
Android 31+ requires FLAG_IMMUTABLE or FLAG_MUTABLE

### ISSUE THREAD

**Issue by AdrienBourgon** [thudugala/Plugin.LocalNotification#301]
Hello,

**Describe the bug:**
I'm using the plugin to send scheduled notification to my users. On Android 31+, I get an exception stating that "Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent."

I went through the source code and I saw that in Platforms/Android/NotificationServiceImpl, the method CreateAlarmIntent create an intent with the flag UPDATE_CURRENT. I tried setting the AndroidOptions.PendingIntentFlags to FLAG_IMMUTABLE but the options are ignored when creating the alarm intent.

Is there any workaround for this ?

**Comment by gaurakshay** [comment]
Please take a look at this SO thread: https://stackoverflow.com/a/69754721/3441488

**Comment by thudugala** [comment]
@AdrienBourgon what version of the plugin are you using?

https://github.com/thudugala/Plugin.LocalNotification/blob/master/Source/Plugin.LocalNotification/Platforms/Android/PlatformExtensions.cs

```cs
public static PendingIntentFlags SetImmutableIfNeeded(this PendingIntentFlags type)
{
    if ((int)Build.VERSION.SdkInt >= 31 &&
        type.HasFlag(PendingIntentFlags.Immutable) == false)
    {
        type |= PendingIntentFlags.Immutable;
    }

    return type;
}
```
get set with Immutable if On Android 31+

**Comment by thudugala** [comment]
@AdrienBourgon if you look closely it does 

CreateAlarmIntent --> CreateActionIntent --> ToNative --> SetImmutableIfNeeded

![image](https://user-images.githubusercontent.com/4112014/199581851-fb230e48-901a-4c79-b6f7-2fd02ede0e02.png)

**Comment by AdrienBourgon** [comment]
@thudugala Oh, I didn't see this extension method. I won't be able to try again for a few weeks but it looks like the problem shouldn't happen. I close this issue, and I'll open a new one later if the error comes back.

Thank you for your help 🙂
