### ISSUE TITLE
Foreground alerts not working on  iOS - UNUserNotificationCenter.Current.Delegate never set

### ISSUE THREAD

**Issue by mphill** [thudugala/Plugin.LocalNotification#303]
**Describe the bug**
When and app is foregrounded, local notifications are not processed.  This is because UNUserNotificationCenter.Current.Delegate is never set. 

You can work around this by adding the following to your AppDelegate:

`LocalNotificationCenter.SetCustomUserNotificationCenterDelegate();`

This is a super confusing part of local notification on iOS.  This delegate is required for alerts to work in the foreground.

https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate

> Use the methods of the UNUserNotificationCenterDelegate protocol to handle user-selected actions from notifications, and to process notifications that arrive when your app is running in the foreground. After implementing these methods in an object, assign that object to the [delegate](https://developer.apple.com/documentation/usernotifications/unusernotificationcenter/1649522-delegate) property of the shared [UNUserNotificationCenter](https://developer.apple.com/documentation/usernotifications/unusernotificationcenter) object. The user notification center object calls the methods of your delegate at appropriate times.

**To Reproduce**
Trigger an alert that triggers immediately:

```c#
  var result = await LocalNotificationCenter.Current.Show(new NotificationRequest()
  {
      Title = title,
      iOS = new iOSOptions()
      {
          Priority = iOSPriority.TimeSensitive,
          HideForegroundAlert = false
      },
      Description = description,
      NotificationId = notificationId
  });
```

**Expected behavior**
Alert should show, but does not.

**Screenshots**
n/a

**Platform (please complete the following information):**
 - OS: iOS
 - Version 10+

**Comment by robheffo79** [comment]
I am having this issue but the workaround is ineffective.

**Comment by AndriyGlodan** [comment]
I'm having the same issue as well

**Comment by AndriyGlodan** [comment]
I have already investigated this issue. So, my app uses the FirebasePushNotificationPlugin. And for some reason, the Plugin.LocalNotifications uses the FirebasePushNotificationPlugin's Notification delegate. That's why I can't see a local notification in the foreground because it was handled by FirebasePushNotificationPlugin's Notification delegate. 

I'm still trying to find a solution, so I'll add new details soon.

**Comment by thudugala** [comment]
@AndriyGlodan and @mphill Have you tried creating a Custom UserNotificationCenterDelegate class and 

```cs
public static class MauiProgram
{
    public static MauiApp CreateMauiApp()
    {
        var builder = MauiApp.CreateBuilder();
        builder
            .UseMauiApp<App>()
            .ConfigureFonts(fonts =>
            {
                fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
            })
            .UseLocalNotification(config =>
            {
                config.AddiOS(iOS =>
                {
#if IOS
                    iOS.SetCustomUserNotificationCenterDelegate(new CustomUserNotificationCenterDelegate());
#endif
                    iOS.SetPermission(new iOSNotificationPermission
                    {
                        LocationAuthorization = iOSLocationAuthorization.WhenInUse
                    });
                });

            });

        return builder.Build();
    }
}
```

https://github.com/thudugala/Plugin.LocalNotification/blob/master/Sample/Direct%20Maui/LocalNotification.Sample/Platforms/iOS/CustomUserNotificationCenterDelegate.cs

**Comment by EdwardMcFlurry** [comment]
🕺🏻 I figured it out 😎 using the following...

Priority = iOSPriority.Critical, for iOSOptions.

Hope this helps!

**Comment by faceoffers28** [comment]
The Priority = iOSPriority.Critical didn't work for me. My app is crashing. My app is a .Net Maui iOS 15.4 app using Asp.net 6.0.300, Visual Studio 17.3.6 & Xamarin SDK 17.3.0.308.

**Comment by mphill** [comment]
@faceoffers28 @EdwardMcFlurry don't use  iOSPriority.Critical unless you get the special entitlement form Apple - which they likely won't give you anyways.

that could be causing the crash.

**Comment by EdwardMcFlurry** [comment]
@faceoffers28 Thanks for the heads up, I'll keep that in mind before publishing to App Store. As for your issue, I'm not sure but try to update everything including .Net 7

**Comment by thudugala** [comment]
Try version 10.0.3
