### ISSUE TITLE
LocalNotificationCenter.Current.CancelAll(notificationRequest => notificationRequest.NotificationId > 100)

### ISSUE THREAD

**Issue by LeoJHarris** [thudugala/Plugin.LocalNotification#308]
Quick feature request for CancelAll that can take a lambda expression where we can be selective which Local Notifications will be Canceled. 

Other usages of this maybe:

```cshap
LocalNotificationCenter.Current.CancelAll(notificationRequest => notificationRequest.Android.ChannelId == "CustomChannel")
```

**Comment by LeoJHarris** [comment]
@thudugala I was trying to working to work through this but got some issues around `Type 'NotificationServiceImpl' already defines a member called` I'm guessing this is do with Maui's new way of having a single project architecture but anyway to resolve this as was keen on implementing this ticket.

**Comment by thudugala** [comment]
@LeoJHarris Can you provide a bit more details on this error, project solution may be

**Comment by LeoJHarris** [comment]
@thudugala can you get access to https://github.com/LeoJHarris/Plugin.LocalNotification.git ?

**Comment by LeoJHarris** [comment]
@thudugala I've made some progress on this but yet to be tested, I will wait on your response and continue progress once the issue is identified

**Comment by LeoJHarris** [comment]
@thudugala any update?

**Comment by LeoJHarris** [comment]
[Plugin.LocalNotification.zip](https://github.com/thudugala/Plugin.LocalNotification/files/10856564/Plugin.LocalNotification.zip)

Hoping to move this a bit faster, let me know if the attached is okay.

**Comment by thudugala** [comment]
@LeoJHarris Yes I can
