### ISSUE TITLE
Sound not working in .net maui

### ISSUE THREAD

**Issue by ahmedHa81** [thudugala/Plugin.LocalNotification#309]
The sound not working in .net Maui
Android

![aj](https://user-images.githubusercontent.com/68436168/197424432-6e6295e3-673e-432f-82b3-681a7cbaecfa.png)
![ju](https://user-images.githubusercontent.com/68436168/197424435-99508fbc-ccb9-4b05-bdd2-76c53016c9bc.png)

**Comment by ahmedHa81** [comment]
No answer yet ?!

**Comment by thudugala** [comment]
@ahmedHa81 is you sound file at correct location?

https://github.com/thudugala/Plugin.LocalNotification/wiki/Notification-with-a-Sound-File

![image](https://user-images.githubusercontent.com/4112014/199408191-d726e8c1-c71a-4b6f-8963-26d7ec034deb.png)

**Comment by ahmedHa81** [comment]
@thudugala Yes I did, still not working!
![h](https://user-images.githubusercontent.com/68436168/199816737-c0584846-856b-46b3-9308-c3add3a716ed.png)

**Comment by ahmedHa81** [comment]
@thudugala  I get the issue ,,, App accepts the first costume sound you run it and after that still keeps the first sound you put it and if you want to try to change it to another sound  you can't  and still run the first sound you put it
  my solution is to change the sound to what I need :
create a new Maui app and didn't run it until create a folder named it (raw) in platforms/android/Resources, put my custom notification sound and download the NuGet package and write a code as your simple code and sound changed successfully as I want

**Comment by thudugala** [comment]
@ahmedHa81 sound is set at the Android Channel level. So to change the sound you have to uninstall and install it again
