### ISSUE TITLE
[iOS] ArgumentNullException when showing notification if ReturningData is set to null

### ISSUE THREAD

**Issue by tranb3r** [thudugala/Plugin.LocalNotification#31]
**Describe the bug**
On iOS, if ReturningData is null in NotificationRequest, then NotificationCenter.Current.Show results in an ArgumentNullException.
No issue on Android.

**To Reproduce**
1. Create a NotificationRequest without setting ReturningData (value should be null)
2. Call NotificationCenter.Current.Show for this notificationRequest
3. On iOS, the notification is not shown, and an exception is raised

**Expected behavior**
The notification should be shown on iOS (as it does on Android).

**Platform:**
 - OS: iOS

**Smartphone:**
 - Device: simulator (iPhone XR)
 - OS: iOS 12.4

**Additional context**
Here is the exception:
```
[0:] System.ArgumentNullException: Value cannot be null.
Parameter name: str
  at Foundation.NSString..ctor (System.String str) [0x00009] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.16.0.5/src/Xamarin.iOS/Foundation/NSString.cs:159
  at Plugin.LocalNotification.Platform.iOS.NotificationServiceImpl.Show (Plugin.LocalNotification.NotificationRequest notificationRequest) [0x00036] in <a9531fbd8e004bca81f421001d65427d>:0
```
I suspect something is wrong in this part of the code (in NotificationServiceImpl for iOS, method Show):
```
using (var returningData = new NSString(notificationRequest.ReturningData))
{
           userInfoDictionary.SetValueForKey(
                  string.IsNullOrWhiteSpace(notificationRequest.ReturningData)
                       ? NSString.Empty
                       : returningData, NotificationCenter.ExtraReturnDataIos);
}
```
Maybe you should test for IsNullOrWhiteSpace before creating the NSString ?

**Comment by thudugala** [comment]
Fixed in 4.0.5
