### ISSUE TITLE
Notification crashes .Net Maui iOS app when app is being used

### ISSUE THREAD

**Issue by faceoffers28** [thudugala/Plugin.LocalNotification#314]
**Describe the bug**
If the app is open and being used when the notification arrives, it immediately takes me to the home screen on the iPhone. The notification never shows in the notification screen on my iPhone. The app itself is still open and now in the background. The app is now back to the login screen, which indicates to me that either I got logged out or it crashed and reopened. I'm not sure about this.

**To Reproduce**

```
var notification = new NotificationRequest
            {
                NotificationId = 100,
                Title = "MyApp Alert",
                Description = "MyApp data has been updated!",
                ReturningData = "Dummy data", // Returning data when tapped on notification.
                Schedule =
                {
                    NotifyTime = DateTime.Now.AddSeconds(30) // Used for Scheduling local notification, if not specified notification will show immediately.
                }
            };
            await LocalNotificationCenter.Current.Show(notification);

```

**Expected behavior**
Seems like the notification should appear in the notification area without crashing the app.

**Screenshots**

**Platform (please complete the following information):**

The issue persists in Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.3.6. Microsoft Visual Studio Enterprise 2022. I'm running version Xamarin.iOS and Xamarin.Mac SDK 16.0.0.75 (e4f48bed7). My target framework is net6.0-ios15.2.

**Smartphone (please complete the following information):**

Iphone 12 running 15.7.

**Additional context**

Is there something that I need to handle or can I place a try catch somewhere in order to get a crash report using something like Sentry.io? Thanks!

**Comment by EdwardMcFlurry** [comment]
@faceoffers28 What about the Permissions on iOS, did you prompt the User for one or you managed to get it working without Permissions, just wondering since Gerald said it?

**Comment by EdwardMcFlurry** [comment]
@faceoffers28 Never mind, I figured it out. 🕺

**Comment by faceoffers28** [comment]
@EdwardMcFlurry The Notifications are working when the app is in the background. The crash only occurs when the app is in the foreground / being used. Is anyone else experiencing the same issue?

**Comment by EdwardMcFlurry** [comment]
@faceoffers28 On my side the iOS app is NOT crashing when the app is running both on the Foreground and/or Background however, on the Foreground I don't see the Notification from the Top nor hear the sound but I do see the Batch number and notifications on the Notification Center.

**Comment by EdwardMcFlurry** [comment]
@faceoffers28  https://github.com/thudugala/Plugin.LocalNotification/issues/303#issuecomment-1304408852

**Comment by faceoffers28** [comment]
@EdwardMcFlurry The Priority = iOSPriority.Critical didn't work for me. My app is still crashing. My app is a .Net Maui iOS 15.4 app using Asp.net 6.0.300, Visual Studio 17.3.6 & Xamarin SDK 17.3.0.308. I tried to implement Remote Notifications. That didn't work either. Perhaps something I'm overriding is causing the issue.

**Comment by faceoffers28** [comment]
This problem was happening for me because I created a iOSNotificationManager.cs and iOSNotificationReciever.cs for remote notifications. I looks like iOSNotificationReciever was causing the problem. I didn't think that would impact location notifications.
