### ISSUE TITLE
Can't get NotificationTapped Event working

### ISSUE THREAD

**Issue by hjavaher** [thudugala/Plugin.LocalNotification#32]
**Describe the bug**
I have the `NotificationCenter.Current.NotificationTapped += Current_NotificationTapped;` in the App.xaml.cs file above the MainPage=new AppShell(); but no matter what I do this event is not triggered when I click on the notifications. As of writing this, I'm on the latest version of everything including ios, xamarin.forms and this plugin.

**Comment by thudugala** [comment]
@hjavaher can you please attach a sample project?

**Comment by hjavaher** [comment]
Unfortunately I can't simulate the app as it's quite far in the development phase and I can't release it yet. I would be more than happy to answer any questions I can though. I'm sorry. I know you're trying to help me out but I just can't simulate the app at this stage.

**Comment by hjavaher** [comment]
Also, Great plugin buddy! Thank you so much for your time and efforts!

**Comment by thudugala** [comment]
Can you get the sample project in this repo to work?

**Comment by karthic1986** [comment]
Change "LocalNotificationTappedEvent"  event args to "NotificationTappedEventArgs"

From
 private void OnLocalNotificationTapped(LocalNotificationTappedEvent e)
 {
      // your code goes here
 }

To
 private void OnLocalNotificationTapped(NotificationTappedEventArgs e)
 {
      // your code goes here
 }

**Comment by askinadze** [comment]
Why the docu is showing LocalNotificationTappedEvent while only NotificationTappedEventArgs  is working?

**Comment by thudugala** [comment]
@askinadze Documentation fixed

**Comment by Ezeji** [comment]
Hi @thudugala , Great efforts you put in through your plugin. 

I discovered the issue earlier raised by @hjavaher still persists for Xamarin Forms Shell with the bug:
I have the NotificationCenter.Current.NotificationTapped += Current_NotificationTapped; in the App.xaml.cs file above the MainPage=new AppShell(); but no matter what I do this event is not triggered when I click on the notifications. As of writing this, I'm on the latest version of everything including ios, xamarin.forms and this plugin.

I followed the setup strictly and all the guides in the documentation for the Nuget package 4.1.4 and I was able to successfully implement a local notification with custom sound in Xamarin Forms Shell but no matter what I do I can't seem to make the tap event work in Shell.

Please your urgent help on this bug will be highly appreciated as my team need to do a quick update on an existing app. Thanks in advance.

**Comment by thudugala** [comment]
@Ezeji can you please attach a sample project.?

**Comment by Ezeji** [comment]
Alright @thudugala,

Let me attach a link to the project right away. Few minutes please

**Comment by Ezeji** [comment]
Hi @thudugala,

Here's a google drive link to the project(xamarin forms shell):
https://drive.google.com/drive/folders/1htDWF3NLeRKF47H6vO7wfZicDpBxRmFQ?usp=sharing

I look forward to your help so as to meet up with the project's timeline. Thanks once again

**Comment by michaelconnolly1** [comment]
I have a similar problem on Android and when I click on the notification the NotificationTapped method does not get called and instead the app reopens (even though it's already open). It works fine on iOS.

The sample app works and I've tried using all the same versions of .NET, Xamarin Forms, etc but still can't get it work on Android. I've even tried going back to version 4.1.4 but still can't get it to work.

I've set the method up as:

NotificationCenter.Current.NotificationTapped += OnLocalNotificationTapped;

and the method signature is:

 private void OnLocalNotificationTapped(NotificationTappedEventArgs e)

I have even tried preceding the NotificationCenter as:

Plugin.LocalNotification.NotificationCenter.Current.NotificationTapped += OnLocalNotificationTapped;

but this doesn't have any effect.

It seems it's not recognising the method signature on Android (hence why it's not getting called) but why would it then work on iOS. I have used earlier version of the plugin without any difficulty so not sure why I'm having a problem now.

In case this is relevant, I have set up an AlarmReceiver and BootBroadcastReceiver to capture the bootup event to reset the notifications when the phone is switched off and back on. Is this still required with the new version of the plugin?

Any insights would be greatly appreciated,

  Michael

**Comment by thudugala** [comment]
@Ezeji you sample project has a SplashActivity, Please have look at https://github.com/thudugala/Plugin.LocalNotification/wiki/Getting-NotificationTapped-to-work-with-splash-screen

**Comment by Ezeji** [comment]
Alright @thudugala, Let me check it out and revert.

Thanks for your efforts.

**Comment by Ezeji** [comment]
Hi @thudugala, thanks for the resource shared.

It worked like charm particularly this article was the plug: https://progrunning.net/best-way-to-create-a-splash-screen-in-xamarin-forms-android-project/

Thumbs up to your team on this plugin.

**Comment by jamesdlow** [comment]
On iOS I had to add `UNUserNotificationCenter.Current.Delegate = new UserNotificationCenterDelegate();` to the FinishedLaunching of my AppDelegate.

```public override bool FinishedLaunching(UIApplication app, NSDictionary options)
        {
            global::Xamarin.Forms.Forms.Init();
            LoadApplication(new App());
            UNUserNotificationCenter.Current.Delegate = new UserNotificationCenterDelegate();
            return base.FinishedLaunching(app, options);
        }
