### ISSUE TITLE
Geofence notifications do not execute either on Android or iPhone

### ISSUE THREAD

**Issue by claus-lysholm** [thudugala/Plugin.LocalNotification#324]
**Describe the bug**
Cannot get Geofence notifications to execute either on Android or iPhone.
Have tried with and without the iOS and Android parameters. No difference. 
Required permissions set for Android: AcceptBackgroundLocation, Access CoarseLocation, AccessFineLocation, AccessNetworkState, Internet, LocationHardware, PostNotifications.
info.plist properties set for iOS: Privacy - Location Always and When In Use Usage Description (true), Privacy - Reminders Usage Description (true), Required background modes.

FYI, normal plugin.localNotification's work fine on Android, not iPhone. 

**To Reproduce**
Steps to reproduce the behavior (code):

The NotificationRequest code:

        NotificationRequest notification = new NotificationRequest
        {
            NotificationId = 110,
            Title = "Climbing a Fence",
            Description = $"You have just passed a Fence",
            //CategoryType = NotificationCategoryType.Event,
            Geofence = new NotificationRequestGeofence
            {
                Center = new NotificationRequestGeofence.Position
                {
                    Latitude = savedLocation.Latitude,   // the value is valid.
                    Longitude = savedLocation.Longitude. // the value is valid
                },
                RadiusInMeters = savedFenceRadius,  // value set to 50 meters
                iOS = new Plugin.LocalNotification.iOSOption.iOSGeofenceOptions
                {
                    Repeats = true
                },
                Android = new Plugin.LocalNotification.AndroidOption.AndroidGeofenceOptions
                {
                    ExpirationDurationInMilliseconds = -1
                },
                NotifyOn = NotificationRequestGeofence.GeofenceNotifyOn.OnEntry |
                           NotificationRequestGeofence.GeofenceNotifyOn.OnExit
            }
        };
        LocalNotificationCenter.Current.Show(notification);

The .UseLocalNotification configuration setup code:
           .UseLocalNotification(config =>
            {
                config.AddiOS(iOS =>
                {
                    iOS.SetPermission(new iOSNotificationPermission
                    {
                        LocationAuthorization = iOSLocationAuthorization.WhenInUse
                    });
                });
            })

To test the functionality I enter the mobile's location option and setting different locations inside and outside the defined position for the notification geofence setup.

**Expected behavior**
I expect a notification to appear whenever I enter or exit a defined geofence area.

**Screenshots**
![image](https://user-images.githubusercontent.com/85547439/202137318-fa53108a-3215-49fb-a694-e49c39829deb.png)

**Platform (please complete the following information):**
 - OS: MacBook Pro 2021 
 
**Smartphone (please complete the following information):**
 - Device: iOS Emulator
 - Version iPhone 14 iOS 16.1
 - Device:  Android Emulator
 - Version Pixel 5 - API 33
 - 
**Additional context**
Using Visual Studio 2022 for Mac
.NET 7, MAUI

**Comment by claus-lysholm** [comment]
Since I mentioned that notifications didn't work either on iOS, I better mention that I finally got that one working by adding the following to the AppDelegate (but would of course prefer if it worked out of the "box" with the plugin):

           if (UIDevice.CurrentDevice.CheckSystemVersion(10, 0))
            {
                // iOS 10 or later
                var authOptions = UNAuthorizationOptions.Alert | UNAuthorizationOptions.Badge | UNAuthorizationOptions.Sound;
                UNUserNotificationCenter.Current.RequestAuthorization(authOptions, (granted, error) =>
                {
                    Console.WriteLine(granted);
                });
            }
            else
            {
                // iOS 9 or before
                var allNotificationTypes = UIUserNotificationType.Alert | UIUserNotificationType.Badge | UIUserNotificationType.Sound;
                var settings = UIUserNotificationSettings.GetSettingsForTypes(allNotificationTypes, null);
                UIApplication.SharedApplication.RegisterUserNotificationSettings(settings);
            }
            UIApplication.SharedApplication.RegisterForRemoteNotifications();

**Comment by thudugala** [comment]
@claus-lysholm  Please try version 10.0.3
