### ISSUE TITLE
Notification not show in simulator 

### ISSUE THREAD

**Issue by RaitoTec2022** [thudugala/Plugin.LocalNotification#325]
I  create new project use
Plugin.LocalNotification version 10.0.2
Xamarin.Forms version 5.0.0.2515
this code in MainPage 

```
  async void Button_Clicked(System.Object sender, System.EventArgs e)
        {
            try
            {
                var notification = new NotificationRequest
                {
                    NotificationId = 100,
                    Title = "Test",
                    Description = "Test Description",
                    ReturningData = "Dummy data", // Returning data when tapped on notification.
                    Schedule =
    {
        NotifyTime = DateTime.Now.AddSeconds(5) // Used for Scheduling local notification, if not specified notification will show immediately.
    }
                };
                await Plugin.LocalNotification.LocalNotificationCenter.Current.Show(notification);
            }
            catch(Exception ex)
            {

            }
        }
```
no exception found and no notification appears what is the problem ?

**Comment by samuelwine** [comment]
Your code as pasted above works perfectly by me.
I had the same problem today, and realised that setting unused properties to null (see below) was causing null reference errors, but failing silently.

`var request = new NotificationRequest
                {
                    Android = null,
                    BadgeNumber = 42,
                    CategoryType = NotificationCategoryType.None,
                    Description = "OMG!!!!!!!",
                    Group = null,
                    Image = null,
                    iOS = null,

                    NotificationId = 1337,
                    ReturningData = null,
                    Schedule =
                    {
                        NotifyTime = DateTime.Now.AddSeconds(5),
                    },
                    Geofence = null,
                    Silent = false,
                    Sound = null,

                    Subtitle = "Hello",
                    Title = "New Message Received"
                };`

**Comment by NehaLOsamaFahmy** [comment]
Notification come silent in background not show on the top of screen, and on foreground not show any thing

**Comment by RaitoTec2022** [comment]
Notification come silent in background not show on the top of screen, and on foreground not show any thing

**Comment by thudugala** [comment]
@RaitoTec2022  Please try version 10.0.3
