### ISSUE TITLE
[Forms-UWP]: No platform plugin found error.

### ISSUE THREAD

**Issue by stormenergy91** [thudugala/Plugin.LocalNotification#327]
I'm trying to use this plugin (version 10.0.2) with Xamarin.Forms and UWP. I installed the library to the .NET standard library and in the UWP project but the app stop in this code:

```
 Plugin.LocalNotification.LocalNotificationCenter.Current.NotificationActionTapped += (Plugin.LocalNotification.EventArgs.NotificationActionEventArgs e) =>
{
    if (OnLocalNotificationTapped != null)
        OnLocalNotificationTapped.Invoke(e.Request.ReturningData);
};
```

with this error: `System.NotImplementedException: '[Plugin.LocalNotification] No platform plugin found.  Did you install the nuget package in your app project as well?'`.

I readed the [docs](https://github.com/thudugala/Plugin.LocalNotification/wiki/Usage-10.0.0-Xamarin.Forms) but there is no info on how install under UWP. What was wrong?

**Comment by thudugala** [comment]
@stormenergy91 This Plugging does not support UWP
