### ISSUE TITLE
cannot access ListenableFuture 

### ISSUE THREAD

**Issue by jrahma** [thudugala/Plugin.LocalNotification#33]
Hi,

I am getting:

error: cannot access ListenableFuture public class ScheduledNotificationWorker class file for com.google.common.util.concurrent.ListenableFuture not found LocalNotifications.Android C:\Users\jrahm\Source\Repos\LocalNotifications\LocalNotifications\LocalNotifications.Android\obj\Debug\90\android\src\md50e8eea8286f69b03ef3779df0abd57a6\ScheduledNotificationWorker.java 4

Thanks,
[Jassim](https://maxmon.softnames.com)

**Comment by thudugala** [comment]
Please look at #27

**Comment by jrahma** [comment]
Yes it is working. Thanks
