### ISSUE TITLE
Notification is not work in IOS 

### ISSUE THREAD

**Issue by Kremed** [thudugala/Plugin.LocalNotification#334]
**Describe the bug**
I'm trying to get local notifications on the iOS platform, but nothing appears, it works fine on Android, but in iOS nothing appears,I am using an iPhone iOS 16 emulator

**To Reproduce**
01 - MauiProgram.cs
```
.UseLocalNotification(config =>
{
   config.AddiOS(iOS =>
   {
      iOS.SetPermission(new iOSNotificationPermission
      {
         LocationAuthorization = iOSLocationAuthorization.WhenInUse
      });
  });
})
```

02 - add permission to Info.plist
`Privacy - Location When In Use Usage Description`

03 - Schedule Notification

```
if (marktingsAdList.Count() > 0)
            {
                var ScheduleTime = DateTime.Now;
                var NotifiId = 0;
                foreach (var item in marktingsAdList)
                {
                    ScheduleTime = ScheduleTime.AddSeconds(1);
                    NotifiId++;
                    var notify = new NotificationRequest
                    {
                        BadgeNumber = NotifiId,
                        NotificationId = NotifiId,
                        Subtitle = "الجميع أونلاين ",
                        Title = item.Title,
                        Description = item.Kind,
                        CategoryType = NotificationCategoryType.Service,

                        Schedule = new NotificationRequestSchedule
                        {
                            NotifyTime = ScheduleTime,
                        },

                        Android = new Plugin.LocalNotification.AndroidOption.AndroidOptions
                        {
                            IsProgressBarIndeterminate = true,
                            VisibilityType = Plugin.LocalNotification.AndroidOption.AndroidVisibilityType.Private,
                            LedColor = 1,
                        }
                    };

                    LocalNotificationCenter.Current.Show(notify);
                }
            }
```

**Expected behavior**
A notification is expected to appear in the emulator system, but nothing appears !!

**Platform (please complete the following information):**
 - OS:  iOS
 - Version 16.1

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Simulator
 - OS: iOS16.1

**Comment by thudugala** [comment]
@ClauderGunpowder can you help?

**Comment by thudugala** [comment]
#335

**Comment by thudugala** [comment]
@Kremed Please try version 10.1.3

**Comment by danlfarnell** [comment]
Hi,

I'm having the same issue as well using the latest 10.1.3.  I am currently running this on an ipod touch which has iOS 15.7.2.

I have .UseLocalNotification() set on the Maui builder and the following code set in my Notify method.


```
 private async Task NotifyWithPushNotification(string title, string data)
 {
            if (await LocalNotificationCenter.Current.AreNotificationsEnabled() == false)
            {
                await LocalNotificationCenter.Current.RequestNotificationPermission();
            }

            var notification = new NotificationRequest
            {
                NotificationId = _notificationId,
                Title = title,
                Description = data,
            };

            await LocalNotificationCenter.Current.Show(notification); //<====Notifications don't show

}

```


Any suggestions?  Thanks for your help in advance.

**Comment by EntityBox** [comment]
@danlfarnell have you tried using the DI method instead of the static, I had similar issues on iOS and at least I'm getting messages now. 

[LocalNotification.Sample/MainPage.xaml.cs#L14](https://github.com/thudugala/Plugin.LocalNotification/blob/master/Sample/Direct%20Maui/LocalNotification.Sample/MainPage.xaml.cs#L14)

Also remember to set a schedule on your notification as they need to fire at a specific time if you do not repeat them:
[/LocalNotification.Sample/MainPage.xaml.cs#L161](https://github.com/thudugala/Plugin.LocalNotification/blob/master/Sample/Direct%20Maui/LocalNotification.Sample/MainPage.xaml.cs#L161)

once you have your notification built, you can just show it on the DI INotificationService instance:
`await _notificationService.Show(request);`

**Comment by ZacharyThomasStone** [comment]
@EntityBox thank you for sharing, I have tried using the Dependency Injection method and I'm still unable to get the notifications to show up for iOS. Any other ideas?

**Comment by EntityBox** [comment]
@ZacharyThomasStone , remember that you have 2 instances for the messages to show:

1. Foreground - Application is running and open - iOS will not show the message when you in this mode, you must handle the incoming message based on the ` += NotificationReceived` eventhandler from the DI instance. eg:  push an Alert popup on the MainThread to display the message.

2. Background - this is when you minimized or closed the app, now for debugging, I've used just the minimize, the OnSleep in App.cs is called and VS still runs in debug mode. Push the message request with your schedule set to 30seconds from the .Show() method, sleep the device, and wait for it to appear.

I've tested with just the default `.UseLocalNotification()` in MauiProgram.cs running .net-6.0. Hope this helps.

**Comment by borrmann** [comment]
it is possible to show notifications on iOS when the App is in Foreground since iOS 10 when you override 


```
public class UserNotificationCenterDelegate : UNUserNotificationCenterDelegate
    {
        #region Constructors
        public UserNotificationCenterDelegate()
        {
        }
        #endregion

        #region Override Methods

        public override void WillPresentNotification(UNUserNotificationCenter center, UNNotification notification, Action<UNNotificationPresentationOptions> completionHandler)
        {
            // Do something with the notification
            Console.WriteLine("Active Notification: {0}", notification);

            // Tell system to display the notification anyway or use
            // `None` to say we have handled the display locally.
            completionHandler(UNNotificationPresentationOptions.Altert);

        }
        #endregion
    }
```

und use this in FinishedLaunching:

`
            UNUserNotificationCenter.Current.Delegate = new UserNotificationCenterDelegate();`

**Comment by thudugala** [comment]
@Kremed @gsk143 @danlfarnell @ZacharyThomasStone @EntityBox 

Please try version 10.1.6
