### ISSUE TITLE
Property "IconName" shouldn't have extention for filename

### ISSUE THREAD

**Issue by arrTeamGun** [thudugala/Plugin.LocalNotification#34]
**Describe the bug**
You have a typo in code

**To Reproduce**
https://github.com/thudugala/Plugin.LocalNotification/wiki/How-to-change-notification-icon

**Expected behavior**
IconName = "myicon"

**Comment by thudugala** [comment]
Thank you @arrTeamGun. Documentation fixed 

https://github.com/thudugala/Plugin.LocalNotification/wiki/%5BAndroid%5D-How-to-change-notification-icon
