### ISSUE TITLE
UseLocalNotification is not defined if TFM is net7.0

### ISSUE THREAD

**Issue by tranb3r** [thudugala/Plugin.LocalNotification#343]
I'm referencing Plugin.LocalNotification in a library built only for net7.0 (no platform specific code).
Of course this library is then referenced in a Maui App (net7.0-android and net7.0-ios).

When building the lib, I've got an error, because UseLocalNotification is not defined for TFM net7.0.
https://github.com/thudugala/Plugin.LocalNotification/blob/1f34082cd5086adc894cfe136e490d02bd2f55eb/Source/Plugin.LocalNotification/LocalNotificationExtensions.cs#L17
Could you please fix this issue and make sure we can reference this package in a net7.0 lib and call the mauiAppBuilder initialisation from this lib ?

Thanks.

**Comment by tranb3r** [comment]
Here is a [repro](https://github.com/tranb3r/Issues/tree/main/MauiAppLocalNotificationLib).

**Comment by thudugala** [comment]
@tranb3r also try referencing Plugin.LocalNotification in Maui App

**Comment by tranb3r** [comment]
Hi @thudugala 
I think there is a misunderstanding. The classLibrary in my repro is not building. Adding the plugin to the app project won't help it.
The issue described here is of your plugin not supporting net7.0 TFM, which prevents using/initializing your plugin in a classLibrary.
Here is the [MauiAppLocalNotificationLib.zip](https://github.com/thudugala/Plugin.LocalNotification/files/10416886/MauiAppLocalNotificationLib.zip) if you want to test it.

**Comment by thudugala** [comment]
@tranb3r Try version 10.1.2

**Comment by 7702244** [comment]
After upgrading to this version, regular MAUI app gives exception:
[Plugin.LocalNotification] No platform plugin found.  Did you install the nuget package in your app project as well?

**Comment by thudugala** [comment]
@7702244 Do you only have net7.0-android and net7.0-ios as TargetFrameworks?

**Comment by 7702244** [comment]
I target net7.0-android net7.0-ios net7.0-maccatalyst

**Comment by thudugala** [comment]
@7702244 remove net7.0-maccatalyst

**Comment by 7702244** [comment]
Is there an option to just not activate the library for Mac, because I want to use the application for this platform?
