### ISSUE TITLE
Asking for permissions on Android 13

### ISSUE THREAD

**Issue by pikausp** [thudugala/Plugin.LocalNotification#346]
Hello,

we are just porting our app to MAUI and as I was working on notifications I wasn't able to get them to display.

Currently, the user isn't prompted for permissions on the application launch and notifications are not displayed with a log message `Notifications are disabled`. This seems to be by design as stated [here](https://developer.android.com/develop/ui/views/notifications/notification-permission). When I open app settings and manually enable notifications they will indeed start showing.

```
If your app targets Android 13 or higher, your app has complete control over when the permission dialog is displayed.
Use this opportunity to explain to users why the app needs this permission, encouraging them to grant it.
```

This behavior was also mentioned here https://github.com/thudugala/Plugin.LocalNotification/issues/257#issuecomment-1214134574.

What is the correct way to prompt users for permissions when targeting Android 13 using your plugin?

**Comment by jl-mobitech** [comment]
+1

**Comment by thudugala** [comment]
@pikausp Have you tried adding android.permission.POST_NOTIFICATIONS to manifest ?

**Comment by chiraagrokadetalent** [comment]
> @pikausp and @jl-mobitech try using version 10.1.0
> 
> Make sure to request permission
> 
> ```cs
> if (await LocalNotificationCenter.Current.AreNotificationsEnabled() == false)
> {
>     await LocalNotificationCenter.Current.RequestNotificationPermission();
> }
> ```

This code was not working on the emulator.
API level(os ver): 34
when I try to debug the app at that time, the app will crash.

**Comment by ChiraagRokade** [comment]
> @pikausp and @jl-mobitech try using version 10.1.0
> 
> Make sure to request permission
> 
> ```cs
> if (await LocalNotificationCenter.Current.AreNotificationsEnabled() == false)
> {
>     await LocalNotificationCenter.Current.RequestNotificationPermission();
> }
> ```

plugin version: 10.1.8
This code was not working on the emulator.
API level(os ver): 34
when I try to debug the app at that time, the app will crash.

error =>
Message => The current Activity can not be detected. Ensure that you have called Init in your Activity or Application class.
StackTrace => Microsoft.Maui.ApplicationModel.ActivityStateManagerExtensions.GetCurrentActivity(IActivityStateManager manager, Boolean throwOnNull) in D:\a_work\1\s\src\Essentials\src\Platform\ActivityStateManager.android.cs:line 95
at Microsoft.Maui.ApplicationModel.Permissions.BasePlatformPermission.DoRequest(String[] permissions) in D:\a_work\1\s\src\Essentials\src\Permissions\Permissions.android.cs:line 109
at Microsoft.Maui.ApplicationModel.Permissions.BasePlatformPermission.RequestAsync() in D:\a_work\1\s\src\Essentials\src\Permissions\Permissions.android.cs:line 86
at Plugin.LocalNotification.LocalNotificationCenter.RequestNotificationPermissionAsync(NotificationPermission permission)
at PMobileMAUI.ViewModel.LoginViewModel.ShowNotification() in C:\Source Code\MobileApplication\MobileMAUI\PMobileMAUI\ViewModel\LoginViewModel.cs:line 308

**Comment by ChiraagRokade** [comment]
If you wrote is method using “void”, then change to “task”, and add two more permissions. 
Permission is below:
```
<uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />
<uses-permission android:name="android.permission.USE_EXACT_ALARM" />
```
This code works on both platform (Android and iOS).
code: 
```
 public async Task ShowNotification()
 {
     try
     {
         if (await LocalNotificationCenter.Current.AreNotificationsEnabled() == false)
         {
             await LocalNotificationCenter.Current.RequestNotificationPermission();
         }
         var request = new NotificationRequest
         {
             NotificationId = 1337,
             Title = "Subscribe to my channel",
             Subtitle = "Hello",
             Description = "It's me",
             Schedule = new NotificationRequestSchedule
             {
                 NotifyTime = DateTime.Now.AddSeconds(60),
                 NotifyRepeatInterval = TimeSpan.FromMinutes(3),

             },
             iOS = new Plugin.LocalNotification.iOSOption.iOSOptions
             {
                 ShowInNotificationCenter = true,
                 PresentAsBanner = true,
                 Priority = Plugin.LocalNotification.iOSOption.iOSPriority.Active,
                 PlayForegroundSound = true
             }
         };
         await LocalNotificationCenter.Current.Show(request).ConfigureAwait(true);

     }
     catch (Exception ex)
     {
         await Toast.Make(ex.Message, ToastDuration.Short).Show();
     }
 }
```
