### ISSUE TITLE
Unable to compile when TargetFrameworks include other than android and ios

### ISSUE THREAD

**Issue by kxrdz** [thudugala/Plugin.LocalNotification#348]
Hallo,
When I install the plugin in Maui project and whenever I reference it in MauiProgram.cs I get to this error

Error	CS1061	'MauiAppBuilder' does not contain a definition for 'UseLocalNotification' and no accessible extension method 'UseLocalNotification' accepting a first argument of type 'MauiAppBuilder' could be found (are you missing a using directive or an assembly reference?)
![image](https://user-images.githubusercontent.com/53437527/211564199-0b822d5b-3425-4831-9610-f5ca61865ff3.png)

**Comment by thudugala** [comment]
@kxrdz Can you please attach a sample project

**Comment by jbloink** [comment]
I received this same error. VS2022 17.5.0 Preview 2.0. Plugin.LocalNotification v10.1.0. Target .NET7. 

I did a File -> New. MAUI App. Installed this NuGet package. Updated MauiProgram.cs and this error came up. 

I've attached a .zip of the project. I hope it helps. 


[MauiAppLocalNotification.zip](https://github.com/thudugala/Plugin.LocalNotification/files/10416461/MauiAppLocalNotification.zip)

**Comment by thudugala** [comment]
@jbloink  ok, the issue is that you are trying to use it with net7.0-maccatalyst and net7.0-windows10.0.19041.0

you have 2 options 
1. Remove net7.0-maccatalyst and net7.0-windows10.0.19041.0 or
2. Add preprocessor directives ANDROID || IOS for UseLocalNotification

```cs
public static class MauiProgram
{
	public static MauiApp CreateMauiApp()
	{
		var builder = MauiApp.CreateBuilder();
		builder
			.UseMauiApp<App>()
#if ANDROID || IOS
            .UseLocalNotification()
#endif
            .ConfigureFonts(fonts =>
			....
		return builder. Build();
	}
}
```

**Comment by jbloink** [comment]
Got it, that makes sense. Thanks for the help and thanks for this awesome plugin!
