### ISSUE TITLE
Make Local Notifications work in Background

### ISSUE THREAD

**Issue by jrahma** [thudugala/Plugin.LocalNotification#35]
Hi,

How can I make the Local Notification triggered in the background even when the app is closed?

Thanks,
Jassim

**Comment by thudugala** [comment]
Hi @jrahma,

Sorry for not replying soon. 
If you set the NotifyTime, even if the app is closed or devices is restarted the Notification will get triggered.

Let me know, if this does not solve you issue.

**Comment by jrahma** [comment]
but this means the app needs to be started first in order to get  the data?

Let me tell you my scenario, I have a prayer reminder app which its timing changes and there is a formula for it

I already have the formula in my app and no issue when the app is in foreground

but I want when the app is also in the background to be able to do the calculation every  and send the notification

**Comment by thudugala** [comment]
@jrahma I do not think you can achieve this with this plugin. 

I would suggest, you look into push notification (App Center Push or Azure Notification Hubs). You may need to put your formula in Scheduler service like Azure Scheduler.

if you don't wont use a cloud service then: 
In Android, you maybe able to do it using AndroidX.Work with a native implementation. 
In iOS, I do not think you can do this.

**Comment by jrahma** [comment]
@thudugala I tried to add the LocalNotification inside WorkManager but nothing is being sent

I added:

[Xamarin.Android.Arch.Work.Runtime](https://www.nuget.org/packages/Xamarin.Android.Arch.Work.Runtime/)

as per this article:

[https://devblogs.microsoft.com/xamarin/getting-started-workmanager/](https://devblogs.microsoft.com/xamarin/getting-started-workmanager/)

My code is like this:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using AndroidX.Work;
using Plugin.LocalNotification;

namespace Jafaria.Droid
{
    public class AthanTime : Worker
    {
        public AthanTime(Context context, WorkerParameters workerParameters) : base(context, workerParameters)
        {

        }

        public override Result DoWork()
        {
            var notification = new NotificationRequest
            {
                NotificationId = 100,
                Title = "Test",
                Description = "Test Description",
                ReturningData = "Dummy data" // Returning data when tapped on notification.
                // Sound = Device.RuntimePlatform == Device.Android ? "Adhan" : "Adhan.mp3",
                // NotifyTime = DateTime.Now.AddSeconds(2) // Used for Scheduling local notification, if not specified notification will show immediately.
            };

            NotificationCenter.Current.Show(notification);

            // var taxReturn = CalculateTaxes();

            // Android.Util.Log.Debug("CalculatorWorker", $"Your Tax Return is: {taxReturn}");

            return Result.InvokeSuccess();
        }

        /*
        public double CalculateTaxes()
        {
            return 2000;
        }
        */
    }
}

```
and in my MainActivity:

```
LoadApplication(new App());

PeriodicWorkRequest taxWorkRequest = PeriodicWorkRequest.Builder.From<AthanTime>(TimeSpan.FromMinutes(1)).Build();

WorkManager.Instance.Enqueue(taxWorkRequest);

```

**Comment by thudugala** [comment]
Hi @jrahma,

Can you attach your sample project ?

**Comment by jrahma** [comment]
@thudugala I guess it's ok now

Thank you so much
