### ISSUE TITLE
GeofenceNotifyOn in and out not work android

### ISSUE THREAD

**Issue by OP-EX** [thudugala/Plugin.LocalNotification#351]
i follow the explain
![Screenshot 2023-01-13 125812](https://user-images.githubusercontent.com/107932068/212376355-56ca41fa-5505-4ee6-927f-f5d2ee384b39.png)
how to use it on android

**Comment by thudugala** [comment]
@OP-EX 

The property name is NotifyOn not GeofenceNotifyOn

```cs
request.Geofence.NotifyOn = NotificationRequestGeofence.GeofenceNotifyOn.OnEntry | NotificationRequestGeofence.GeofenceNotifyOn.OnExit;
```

**Comment by OP-EX** [comment]
> @OP-EX
> 
> The property name is NotifyOn not GeofenceNotifyOn
> 
> ```cs
> request.Geofence.NotifyOn = NotificationRequestGeofence.GeofenceNotifyOn.OnEntry | NotificationRequestGeofence.GeofenceNotifyOn.OnExit;
> ```

thx you

**Comment by OP-EX** [comment]
thx you
