### ISSUE TITLE
Android Notification Priority 

### ISSUE THREAD

**Issue by OP-EX** [thudugala/Plugin.LocalNotification#352]
How to get my notifications  to do this 
https://user-images.githubusercontent.com/107932068/212441412-b37a07d4-cdef-4d2e-a4be-64f9f61ea5b0.mp4

And not this 
https://user-images.githubusercontent.com/107932068/212441429-dfb9bc1d-ce54-494c-ace2-7f20bf1201c7.mp4

**Comment by thudugala** [comment]
@OP-EX 
Set 
```cs
var request = new NotificationRequest();
request.Android.Priority = AndroidPriority.High;
```

**Comment by OP-EX** [comment]
@ thx you

**Comment by thudugala** [comment]
@OP-EX I do not think so

**Comment by AliShafqat-RI** [comment]
@thudugala Hey, how can I set channel priority when initializing it in main activity like 
            NotificationCenter.CreateNotificationChannel(AndroidNotificationPriority.High);
 Thanks.

**Comment by thudugala** [comment]
@AliShafqat-RI, you cannot set Priority at Channel level

https://developer.android.com/reference/android/app/NotificationChannel
