### ISSUE TITLE
Upgrade  error?

### ISSUE THREAD

**Issue by OP-EX** [thudugala/Plugin.LocalNotification#353]
This stop working  after  the update 
So I down grade  and  the error still show up

![Screenshot 2023-01-14 194521](https://user-images.githubusercontent.com/107932068/212502406-89218c3f-4881-414c-8b7d-287136c4fb06.png)

This work even if the error  shows  up

![Screenshot 2023-01-14 194456](https://user-images.githubusercontent.com/107932068/212502410-f458038a-8536-401b-997f-9b326249e294.png)

the red x is where the error is coming from
![Screenshot 2023-01-14 224153](https://user-images.githubusercontent.com/107932068/212520234-5250fd94-3c4e-42cb-972a-d37f823b2a14.png)

**Comment by thudugala** [comment]
Can you please attach a sample project?

**Comment by OP-EX** [comment]
@thudugala 
[New folder.zip](https://github.com/thudugala/Plugin.LocalNotification/files/10419180/New.folder.zip)

**Comment by thudugala** [comment]
@OP-EX zin file does not have the project

**Comment by thudugala** [comment]
Issue fixed try version 10.1.3
