### ISSUE TITLE
Upgrade Error?

### ISSUE THREAD

**Issue by jbloink** [thudugala/Plugin.LocalNotification#354]
Not sure if this is related to #353 or not, but all was well this morning on v10.1.0 (after adding the platform conditionals as suggested in #348), after I upgraded to v10.1.2, I'm receiving this error: System.NotImplementedException: '[Plugin.LocalNotification] No platform plugin found.  Did you install the nuget package in your app project as well?'

I tried uninstalling/cleaning/rebuilding/reinstalling. I tried changing my API versions. Not sure if there is a common way to resolve this or if it's a bug.

**Comment by jbloink** [comment]
Project attached
[MauiAppLocalNotification (4).zip](https://github.com/thudugala/Plugin.LocalNotification/files/10419318/MauiAppLocalNotification.4.zip)

**Comment by thudugala** [comment]
@jbloink I can compile this project

![image](https://user-images.githubusercontent.com/4112014/212528293-d6b095bd-1480-4db2-bef3-d7e06a63ca8a.png)

**Comment by thudugala** [comment]
Issue fixed try version 10.1.3

**Comment by jbloink** [comment]
Works great, thanks!
