### ISSUE TITLE
NotificationServiceImpl.cs for IOS referencing Android

### ISSUE THREAD

**Issue by EntityBox** [thudugala/Plugin.LocalNotification#357]
By just browsing the code to understand a bit more on the native side, I followed the builder from the Centre.Current the INotificationService implementation in iOS: Source/Plugin.LocalNotification/Platforms/iOS)/NotificationServiceImpl.cs

Please check line: 59
if (!OperatingSystem.**IsAndroidVersionAtLeast**(10))

It should be: 
if (!OperatingSystem.**IsIOSVersionAtLeast**(10))

This might cause exceptions internally and could potentially lead to the reason why some issues were raised that the notifications are not working. 

Thanks.

**Comment by EntityBox** [comment]
#360 PR Added for the fix.

**Comment by thudugala** [comment]
thank you @EntityBox
