### ISSUE TITLE
NotificationReceiving not working

### ISSUE THREAD

**Issue by mmajors75** [thudugala/Plugin.LocalNotification#358]
**Describe the bug**
I created a sample MAUI Project on my MAC to test out this Plugin (basically copied the Sample code from the Source).  I am able to schedule notifications and they show up as expected.  However, I am not having any luck with intercepting the notification before it is shown on the device.

**To Reproduce**
1. Create a new MAUI Project
2. From the Sample/Direct Maui Folder, copy the code from MauiProgram.cs and MainPage (not all of it)
3. Run my Project on an iOS Simulator
4. The notification is being delivered, but my OnNotificationReceiving function is not being called.

Relevant code:
`_notificationService.NotificationReceiving = OnNotificationReceiving;`
`private Task<NotificationEventReceivingArgs> OnNotificationReceiving(NotificationRequest request)
    {
        request.Title = $"{request.Title} Modified";

        return Task.FromResult(new NotificationEventReceivingArgs
        {
            Handled = false,
            Request = request
        });
    }`

I added a breakpoint and it was never executed.  In addition, when the Notification was delivered, I did not see the modified content.

**Expected behavior**
I expect the Notification to be modified before delivering it to the system.

**Platform (please complete the following information):**
Visual Studio 2022 Preview on MAC

**Smartphone (please complete the following information):**
iPhone 14 Pro iOS 16.2 Simulator

Update - January 19, 2023
I think we need to set the mutable-content = 1 in the userInfo for iOS.

**Comment by thudugala** [comment]
@mmajors75 If you think you have fix, please send a PR

**Comment by thudugala** [comment]
@mmajors75 please try version 10.1.6
