### ISSUE TITLE
Get Scheduled Notification Details

### ISSUE THREAD

**Issue by jrahma** [thudugala/Plugin.LocalNotification#36]
Hi

How can I loop through all the scheduled notifications and read their details?

Or how can I get a specific scheduled notification details by ID?

** I a not not talking about Notification_Tapped here but I just want to know what are all the pending notifications

Thanks,
Jassim

**Comment by thudugala** [comment]
@jrahma this is not supported at the moment.

**Comment by jrahma** [comment]
Hope to consider this as feature request. Thanks
