### ISSUE TITLE
LocalNotificationCenter does not get a definition of CreateNotificationChannel error

### ISSUE THREAD

**Issue by mbouarroudj** [thudugala/Plugin.LocalNotification#364]
Hi 

I am trying this plugin and added this code in Android mainactivity as indicated in the doc

LocalNotificationCenter.CreateNotificationChannel();

but it said LocalNotificationCenter does not get a definition of CreateNotificationChannel

If I remove this code, I will get a runtime error:
System.NotImplementedException: '[Plugin.LocalNotification] No platform plugin found.  Did you install the nuget package in your app project as well?'

Any help please
thx

**Comment by thudugala** [comment]
@mbouarroudj Can you please attach a sample project?
