### ISSUE TITLE
Too many ANR

### ISSUE THREAD

**Issue by planyazilim** [thudugala/Plugin.LocalNotification#366]
GETS too many Android ANR on google play console
Broadcast of Intent { act = android.intent.action.BOOT_COMPLETED cmp = com.myapp.myapp /plugin.LocalNotification.ScheduledAlarmReceiver }

**Comment by thudugala** [comment]
@planyazilim Please try Version 10.1.5

FYI v10.1.5 has a breaking change Android permission must be specified at the application level now.
