### ISSUE TITLE
Local notification does not properly fire on iOS when notification repeat is set to NotificationRepeat.TimeInterval 

### ISSUE THREAD

**Issue by jl-mobitech** [thudugala/Plugin.LocalNotification#370]
**Describe the bug**
I don't know if this is a bug but I have a requirement for the app that I am developing to recur a notification daily, weekly, monthly, or yearly. Now setting the repeat to daily, weekly, monthly, or yearly successfully shows a notification on Android but not on iOS. Since NotificationRepeat enum does not contain monthly or yearly, I am using NotificationRepeat.TimeInterval. Can you please explain more how to achieve this kind of specifications using the wonderful library you created? Or perhaps, maybe refactor iOS' codebase for repeat like this: https://stackoverflow.com/a/45200310/13061894 ?

**To Reproduce**
Create a notification that should repeat monthly or yearly on iOS

**Expected behavior**
Notification would show up exactly on the date and time specified

**Platform (please complete the following information):**
 - OS: iOS
 - Version: 16.1

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: iOS
 - Version 16.1

**Comment by MaxWroe** [comment]
We are also facing a similar issue to this. 

On Android setting repeat to time interval works as one would expect, with the first notification coming at the scheduled time and following repeats occurring after time intervals of length specified by the NotifyRepeatInterval.

Behaviour on iOS however is inconsistent, it appears as if the repeat interval begins immediately regardless of the scheduled time. For example if it is 3pm and I schedule a notification for 10pm with a notifyRepeatInterval of 15 minutes, I will get a nudge at 3:15 and again every 15 minutes from that point forward. This essentially means you can't use a repeat interval currently if you wish to schedule notifications in the future.

**Comment by MaxWroe** [comment]
> We are also facing a similar issue to this.
> 
> On Android setting repeat to time interval works as one would expect, with the first notification coming at the scheduled time and following repeats occurring after time intervals of length specified by the NotifyRepeatInterval.
> 
> Behaviour on iOS however is inconsistent, it appears as if the repeat interval begins immediately regardless of the scheduled time. For example if it is 3pm and I schedule a notification for 10pm with a notifyRepeatInterval of 15 minutes, I will get a nudge at 3:15 and again every 15 minutes from that point forward. This essentially means you can't use a repeat interval currently if you wish to schedule notifications in the future.

Looking at the source code for the iOS platform (NotificationServiceImpl) it seems like this is a known error, is this a limitation with the apple SDK's with no work around ? I think it would be good to add some sort of documentation and  checks to make sure developers using this library are aware of the limitation ? Otherwise people could potentially be wasting hours wondering why notifications aren't working as expected on iOS.

**Comment by thudugala** [comment]
@MaxWroe thank you documentation updated

https://github.com/thudugala/Plugin.LocalNotification/wiki/Repeat-Notification
