### ISSUE TITLE
InAndroid NotificationActionTapped Only fire Last-Added Notification

### ISSUE THREAD

**Issue by AlexPC03** [thudugala/Plugin.LocalNotification#374]
Hi :)

SAMSUNG Galaxy A12 - Android 12

Visual Studio 2022 MAUI .NET 7

In LocalNotification.Sample I modify the line
MainPage
=>Button_Clicked
     =>From: var notificationId = 100;
     =>To: var notificationId = 100 + _tapCount;
To recibe more Notification

Then I only recibe the NotificationActionTapped from the last one

Thanks for your hard work :)

**Comment by onurcoskun14** [comment]
Hello,

I have the same issue. When i build 3 notification i only receive the last one.

Samsung Galaxy J7-Android 6.0.1

**Comment by andrei-cb** [comment]
Same issue here. I get the event trigger only for the last added notification.

**Comment by thudugala** [comment]
duplicate #365
