### ISSUE TITLE
iOS: notifications work on simulator, don't work on device

### ISSUE THREAD

**Issue by vasile135** [thudugala/Plugin.LocalNotification#375]
**Describe the bug**
The local notification is working on simulator, not working on device. (package version 10.1.3).

**To Reproduce**
1. Created the notification request:
`var notification = new NotificationRequest
				{
					NotificationId = 100,
					Title = "New document",
					Description = "You've got a new document",
					BadgeNumber = 1,
					CategoryType = NotificationCategoryType.Event,
					ReturningData = credential.Id, 
					iOS =
					{
						HideForegroundAlert = false
					}
				};`
2. When a specific event occurs in the application, the notification is shown:
`MainThread.BeginInvokeOnMainThread(async () =>
{
      await LocalNotificationCenter.Current.Show(notification);
 }`
3. I'm checking the permission on the app start:
`if (!await _notificationService.AreNotificationsEnabled())
{
	await _notificationService.RequestNotificationPermission();
}`
4. The notification is displayed on iOS simulator, but doesn't do anything on iPhone

**Expected behavior**
Expecting to work on iPhone as in the simulator.

**Platform (please complete the following information):**
 - OS: iOS
 - Version 16.3.1

**Smartphone (please complete the following information):**
 - Device: iPhone 8 Plus
 - OS: iOS
 - Version 16.3.1

**Comment by thudugala** [comment]
@vasile135 Can you please try version 10.1.6?

**Comment by vasile135** [comment]
> It's working with 10.1.8. Thank you.
