### ISSUE TITLE
Calling LocalNotificationCenter.Current.Cancel(int[]) does not cancel all notifications in array

### ISSUE THREAD

**Issue by kerry-em-u** [thudugala/Plugin.LocalNotification#377]
**Describe the bug**
When there are multiple Pending and Delivered notifications, you call LocalNotificationCenter.Current.Cancel(int[]) where int[] is an array of notification IDs, not all notifications are cancelled. Calling LocalNotificationCenter.Current.CancelAll() reliably cancels ALL notifications

This happens on both Android and iOS

**Comment by mmajors75** [comment]
Hi @kerry-em-u  - I am running into the same issue.  As a workaround, I am doing this:

1. I am retrieving all of the Pending Notifications
2. Filter out the Notifications that I do not want
3. Call CancelAll
4. Then, schedule the remaining notifications.

**Comment by kerry-em-u** [comment]
Thanks @***@***.***>,
I am doing the same thing but it is not ideal

Regards

Kerry Smith
   Senior Developer

***@***.***


M +61 412 722 090
E ***@***.******@***.***>
W www.em-u.co<http://www.em-u.co>
P Please consider the Environment before printing this email

The information in this message and attached file/s may be confidential and/or legally privileged and is intended solely for the addressee.  Access to this information by anyone other than the addressee is prohibited. If you are not the intended recipient, any disclosure, copying, distribution or any action taken or omission made in reliance on the information contained in this email, is prohibited.  The views expressed in this email may not necessarily reflect the views or position of Posturely P/L and should not be relied upon, quoted or used. Posturely P/L cannot guarantee that this message is virus free.  Virus scanning is therefore recommended and is the responsibility of the recipient.

**Comment by thudugala** [comment]
@kerry-em-u Is it cancelling through LocalNotificationCenter.Current.Cancel(int[]) does it cancel some of them?

Do you know if this issue only happens for scheduled notifications? 

cc @mmajors75

**Comment by kerry-em-u** [comment]
@thudugala Through LocalNotificationCenter.Current.Cancel(int[]) it does not appear to cancel all. I think it cancels some.
We are only using scheduled notifications

**Comment by thudugala** [comment]
@kerry-em-u Please try Version 10.1.5

@mmajors75 @wcoder @GitBOUF 

FYI v10.1.5 has a breaking change Android permission must be specified at the application level now.
