### ISSUE TITLE
Xamarin Forms - Android - Cancel and CancelAll not working.

### ISSUE THREAD

**Issue by minitockers** [thudugala/Plugin.LocalNotification#380]
I'm scheduling notifications like this:

```
if (await LocalNotificationCenter.Current.AreNotificationsEnabled() == false)
{
    await LocalNotificationCenter.Current.RequestNotificationPermission();
}

var notification = new NotificationRequest
{
    NotificationId = id,
    Title = title,
    Description = body,
    Schedule =
    {
        NotifyTime = time
    }
};
await LocalNotificationCenter.Current.Show(notification);
```

When I try to cancel any scheduled notification, with either `LocalNotificationCenter.Current.Cancel(id);` or `LocalNotificationCenter.Current.CancelAll();` the notifications are still received.

I have to reschedule all notifications when certain things change. And this is leading to duplicate notifications.

This works perfectly on iOS.

**Comment by minitockers** [comment]
Anyone else having this issue on the latest version?

**Comment by keke1210** [comment]
I am also having this issue.

**Comment by mbouarroudj** [comment]
I am also having this issue with MAUI project running on Android, is there a chance that this issue is fixed soon? I cannot use this plugin since the end user cannot cancel a notification, code:

var request = new NotificationRequest
        {
            Title = "test notif",
            Description = "test notif",
            NotificationId = 111,
            ReturningData = "id: 111",
            Schedule = new NotificationRequestSchedule
            {
                NotifyTime = DateTime.Now.AddSeconds(1),
                NotifyRepeatInterval = TimeSpan.FromMinutes(5),
                RepeatType = NotificationRepeat.TimeInterval
            }

        };

        LocalNotificationCenter.Current.Show(request);


-- cancel method
 LocalNotificationCenter.Current.Cancel(111)
or
 LocalNotificationCenter.Current.CancelAll();

**Comment by k4p1cz** [comment]
Same issue! Please fix or help!

**Comment by CamilaPedocchi** [comment]
Fix the issue by installing version 10.1.3.

**Comment by k4p1cz** [comment]
> 

![image](https://user-images.githubusercontent.com/101667638/227996790-4580f231-68bd-44a4-9d90-3a3362a68402.png)

I am using 10.1.4 but still no fix. 

![image](https://user-images.githubusercontent.com/101667638/227996895-b1aa3d8c-bf35-4081-b13b-6d671df4546f.png)

I've tried everyting I could.

**Comment by CamilaPedocchi** [comment]
Yes, it's working perfect (Android and ios), by installing version 10.1.3.

**Comment by minitockers** [comment]
> Yes, it's working perfect (Android and ios), by installing version 10.1.3.

It still doesn't cancel for me on 10.1.3 either!

**Comment by k4p1cz** [comment]
> Yes, it's working perfect (Android and ios), by installing version 10.1.3.

May I see your request settings?

**Comment by CamilaPedocchi** [comment]
Xamarin.Forms 5.0.0.2578
Plugin.Localnotification 10.1.3

Xamarin.AndroidX.Core 1.9.0.2


   var notificationRepeat = new NotificationRequest
            {
                NotificationId = notificationid,
                Title = title,
                Description = description,
                ReturningData = idTypeGrupo + ";" + keyGroup + ";" + description,
                BadgeNumber = 1,
                iOS = new iOSOptions()
                {
                    HideForegroundAlert = false,
                    PlayForegroundSound = true,
                    PresentAsBanner = true,
                    Priority = iOSPriority.Active,
                    ShowInNotificationCenter = true                   
                },
                Schedule = new NotificationRequestSchedule()
                {
                    NotifyTime = alert                    
                },
                Android = new AndroidOptions()
                {
                    AutoCancel = true,
                    ChannelId = settingApp.ChannelId,
                    Priority = AndroidPriority.Default,
                    VisibilityType = AndroidVisibilityType.Public,
                    LaunchAppWhenTapped = true                    
                },
                Sound = settingApp.AlertSound,
                CategoryType = NotificationCategoryType.Status
            };
                        
            LocalNotificationCenter.Current.Show(notificationRepeat);

	-- After ---
 LocalNotificationCenter.Current.Cancel(notificationsid);

Check that Cancel is not within a task or a transaction or in any backgruond process.

**Comment by Qumalu** [comment]
> Xamarin.Forms 5.0.0.2578 Plugin.Localnotification 10.1.3
> 
> Xamarin.AndroidX.Core 1.9.0.2
> 
> var notificationRepeat = new NotificationRequest { NotificationId = notificationid, Title = title, Description = description, ReturningData = idTypeGrupo + ";" + keyGroup + ";" + description, BadgeNumber = 1, iOS = new iOSOptions() { HideForegroundAlert = false, PlayForegroundSound = true, PresentAsBanner = true, Priority = iOSPriority.Active, ShowInNotificationCenter = true }, Schedule = new NotificationRequestSchedule() { NotifyTime = alert }, Android = new AndroidOptions() { AutoCancel = true, ChannelId = settingApp.ChannelId, Priority = AndroidPriority.Default, VisibilityType = AndroidVisibilityType.Public, LaunchAppWhenTapped = true }, Sound = settingApp.AlertSound, CategoryType = NotificationCategoryType.Status };
> 
> ```
>         LocalNotificationCenter.Current.Show(notificationRepeat);
> 
> -- After ---
> ```
> 
> LocalNotificationCenter.Current.Cancel(notificationsid);
> 
> Check that Cancel is not within a task or a transaction or in any backgruond process.

How you know its canceled and not cleared, this is scheduled notification not repeating one, for me downgrading didn't do the job it clears the notification but it does not cancel it.

**Comment by minitockers** [comment]
> Xamarin.Forms 5.0.0.2578 Plugin.Localnotification 10.1.3
> 
> Xamarin.AndroidX.Core 1.9.0.2
> 
> var notificationRepeat = new NotificationRequest { NotificationId = notificationid, Title = title, Description = description, ReturningData = idTypeGrupo + ";" + keyGroup + ";" + description, BadgeNumber = 1, iOS = new iOSOptions() { HideForegroundAlert = false, PlayForegroundSound = true, PresentAsBanner = true, Priority = iOSPriority.Active, ShowInNotificationCenter = true }, Schedule = new NotificationRequestSchedule() { NotifyTime = alert }, Android = new AndroidOptions() { AutoCancel = true, ChannelId = settingApp.ChannelId, Priority = AndroidPriority.Default, VisibilityType = AndroidVisibilityType.Public, LaunchAppWhenTapped = true }, Sound = settingApp.AlertSound, CategoryType = NotificationCategoryType.Status };
> 
> ```
>         LocalNotificationCenter.Current.Show(notificationRepeat);
> 
> -- After ---
> ```
> 
> LocalNotificationCenter.Current.Cancel(notificationsid);
> 
> Check that Cancel is not within a task or a transaction or in any backgruond process.

So after more testing I realised the cancel was being called before the show, with how my threading was working.

But now I fixed that, it is also seemingly working on 10.1.4. Whereas clearly lots of people are still having issues with that, like I first raised.
Unless I'm having some strange caching issue and I'm somehow actually still using 10.1.3!

**Comment by k4p1cz** [comment]
> > function
> 
> That's the boat I was in, so I have no idea why mine seems to be working now!
> 
> I haven't fully tested, I've just tested doing a loop to create 5 notifications 5 seconds apart. And then calling cancel on the first 2 ids, and it worked to only show the last 3 test notifications. But this previously hadn't been working.
> 
> In my real code, I'm calling CancelAll before then recreating all notifications, when the user changes what time they want the notifications. This part I haven't managed to check yet.

May I message you so we can have a chat about that? I really need to find a way to fix this issue.

**Comment by thudugala** [comment]
@minitockers Please try Version 10.1.5

cc @CamilaPedocchi @keke1210 @mbouarroudj 

FYI v10.1.5 has a breaking change Android permission must be specified at the application level now.

**Comment by CamilaPedocchi** [comment]
Version 10.1.5 works. Thank you.
