### ISSUE TITLE
Nuget assemblies are compiled in Debug instead of Release

### ISSUE THREAD

**Issue by tranb3r** [thudugala/Plugin.LocalNotification#383]
It seems like nuget assemblies are compiled in Debug instead of Release.
Could you please take a look?
Thanks!

**Comment by thudugala** [comment]
@tranb3r Please try Version 10.1.5

FYI v10.1.5 has a breaking change Android permission must be specified at the application level now.

**Comment by tranb3r** [comment]
LGTM. Thanks!
