### ISSUE TITLE
[10.1.4] warning IL2102: Invalid AssemblyMetadata("IsTrimmable", "False") attribute in assembly 'Plugin.LocalNotification'. Value must be "True"

### ISSUE THREAD

**Issue by tranb3r** [thudugala/Plugin.LocalNotification#384]
I'm getting this warning when building my app on android with version 10.1.4 of the plugin:
`warning IL2102: Invalid AssemblyMetadata("IsTrimmable", "False") attribute in assembly 'Plugin.LocalNotification'. Value must be "True"`

I'm building with full mode of dotnet trimmer (net7.0):
`<TrimMode>full</TrimMode>`

I didn't have any issue previously, no warning with 10.1.3.

Could you please take a look?
Thanks

**Comment by Brionvega** [comment]
Hi tranb3r,
I've got the same issue.
Have you manage to solve this?
Thanks for advice,
Stewart

**Comment by tranb3r** [comment]
I don't think there is anything we can do, except waiting for @thudugala to fix it.

**Comment by thudugala** [comment]
Hi @tranb3r I added it due to people having issues when TrimMode is set to full.

Some of the dependent libraries did not work.

**Comment by thudugala** [comment]
@tranb3r Please try Version 10.1.5

cc @Brionvega @wcoder @GitBOUF 

FYI v10.1.5 has a breaking change Android permission must be specified at the application level now.

**Comment by tranb3r** [comment]
LGTM. Thanks!
