### ISSUE TITLE
Notification don't show after reboot

### ISSUE THREAD

**Issue by mos379** [thudugala/Plugin.LocalNotification#39]
I implemented a JobScheduler to show notifications.
The notifications are nicely shown after I opened my app and the jobscheduler gets triggered. 
When I minimize my app the job keeps processing and the notifications are shown. 

After reboot my job is still triggered and processing, but the notifications are not shown and the 
I added logcats to see if the job is working properly and everything seems fine. 
Do I miss any special setting to allow showing notifications after the reboot?

**Comment by thudugala** [comment]
Hi mos379, Can you attach a sample project ?

**Comment by mos379** [comment]
After changing your sample project to include the job, I figured out that the problem was not your plugin! 
Great job on the Plugin so far ;)
