### ISSUE TITLE
'LocalNotificationCenter' does not contain a definition for 'CreateNotificationChannel'

### ISSUE THREAD

**Issue by abdulhamid3183924** [thudugala/Plugin.LocalNotification#393]
i have this error when i try to implement the 
Plugin.LocalNotification in my project , it says that  LocalNotificationCenter  does not contain a definition for  CreateNotificationChannel 

LocalNotificationCenter.CreateNotificationChannel();

and also i got error 
The name 'NotificationCenter' does not exist in the current context
NotificationCenter.CreateNotificationChannel();

**Comment by thudugala** [comment]
@abdulhamid3183924 Can you please attach a sample project?

**Comment by thudugala** [comment]
Closing issue due to no responce.
