### ISSUE TITLE
How do I cancel notification that is set to be repeating?

### ISSUE THREAD

**Issue by k4p1cz** [thudugala/Plugin.LocalNotification#395]
Hello.

So I've setup the notification with id 1000 to notify every 10 seconds (just for testing). And I am activating this notification by clicking a button. 

I've setup button that will cancel that notification and I tried using this. 
![image](https://user-images.githubusercontent.com/101667638/228377596-30252787-5574-47b1-a16c-1b8d66394c45.jpeg)
But none of this was working and the notification just kept notifying. 

Am I doing something wrong?

Thank you for help.

Best regard, 
k4p1

**Comment by hakonn** [comment]
Hi!
Which version are you using? And are you testing on Android or iOS? I experienced the same error on iOS, using .net6, but when I upgraded to .net7 and latest nuget everything worked fine.

**Comment by k4p1cz** [comment]
> Hi! Which version are you using? And are you testing on Android or iOS? I experienced the same error on iOS, using .net6, but when I upgraded to .net7 and latest nuget everything worked fine.

Hi. I am using .NET7 and I am testing on Android. I will try to upgrade nuget to the latest version but I think I am already running latest one.

**Comment by osyyyS** [comment]
I'm having the same issue in Xamarin.Forms on Android using version 10.1.4.

**Comment by thudugala** [comment]
@k4p1cz Please try Version 10.1.5

cc @hakonn @osyyyS 

FYI v10.1.5 has a breaking change Android permission must be specified at the application level now.
