### ISSUE TITLE
Plugin.LocalNotification doesn't show notifications that are scheduled to display after a long time

### ISSUE THREAD

**Issue by MARIA-AZRAR** [thudugala/Plugin.LocalNotification#396]
**Description**
I'm trying to get future data of 6 days for my .net maui application and scheduling the notifications for those 6 days at a specific time. The notifications seem to work fine if the scheduled time is within 3 to 4 minutes or if I go to the future date and time manually within those 3 to 5 minutes but, it doesn't show notifications if notify time is more than 4 minutes. 

          
                                    var arrivalTime = data.event.EventDate + data.event.ScheduledTime.Value;

                                    var notification = new NotificationRequest
                                    {
                                        NotificationId = (int)arrivalTime.Ticks,
                                        Title = Constants.TITLE,
                                        Subtitle = Constants.SUBTITLE,
                                        Description = Constants.DESCRIPTION,
                                        Schedule = new NotificationRequestSchedule
                                        {
                                            NotifyTime = arrivalTime,
                                        }
                                    };

                                    await LocalNotificationCenter.Current.Show(notification);

**Smartphone**
Tested it on 
 - Android Emulator 12.0
 - Android Vivo Device 12.0

**Comment by thudugala** [comment]
@MARIA-AZRAR Can you please attach a sample project?
