### ISSUE TITLE
Grouping notifications error when adding Silent = true Android

### ISSUE THREAD

**Issue by ksawio97** [thudugala/Plugin.LocalNotification#397]
**Describe the bug**
When you set Silent to true in notification it doesn't group (doesn't matter if notification is  IsGroupSummary or not)

**To Reproduce**
Create couple of notifications request with same Android ChannelId and with Silent set to true

**Expected behavior**
Should group but they don't

**Platform (please complete the following information):**
-Android 13.0

**Smartphone (please complete the following information):**
-OnePlus Nord CE 2 Lite

**Comment by thudugala** [comment]
@ksawio97 Can you please attach a sample project?

**Comment by thudugala** [comment]
@ksawio97 I think this a Android limitation
