### ISSUE TITLE
Plugin LocalNotification is not working on iOS with .Net 7

### ISSUE THREAD

**Issue by NEHAMAZIK** [thudugala/Plugin.LocalNotification#398]
The Plugin.LocalNotification works fine on Android device ,but iOS simulator and remote device both does not receive any notification with the code ,I am working on .net maui Blazor with .net standard 7 is there anything platform specific code that I am missing, kindly do let me know the workaround for this and the ways to handle the notification please refer an article related to handling those notifications Both on Android and iOS . @thudugala

**Comment by thudugala** [comment]
@NEHAMAZIK Can you please attach a sample project?

**Comment by thudugala** [comment]
@NEHAMAZIK please try version 10.1.6
