### ISSUE TITLE
Migration to AndroidX

### ISSUE THREAD

**Issue by tranb3r** [thudugala/Plugin.LocalNotification#40]
Is the migration to AndroidX planned ?

**Comment by thudugala** [comment]
The plugin works if you Migration to AndroidX.
The plugin does not have direct dependency to any Android Support Libraries or AndroidX (not published). 
When the Xamarin.Android.Arch.Work.Runtime gets updated to use AndroidX this plugin will automatically get updated to AndroidX.

**Comment by tranb3r** [comment]
I'm not sure I understand.
The plugin depends on Xamarin.Android.Arch.Work.Runtime and Xamarin.Android.Support.v4.
Both libs have their AndroidX equivalent : Xamarin.AndroidX.Work.Runtime and Xamarin.AndroidX.Legacy.Support.V4
Shouldn't you publish a nuget with androidX dependencies (instead of support libs)?

**Comment by tranb3r** [comment]
Thank you for the release.
Did you manage (by any chance) to migrate the nuget sample ?
I'm having this error : The Java type `mono.android.support.v4.media.session.MediaSessionCompat_OnActiveChangeListenerImplementor` is generated by more than one managed type

**Comment by thudugala** [comment]
@tranb3r try [NuGet v500P01](https://github.com/thudugala/Plugin.LocalNotification/tree/master/Sample/NuGet%20v500P01) sample

**Comment by tranb3r** [comment]
I was wrongly assuming that I could remove the xamarin.androix.migration package after adding the correct androidx packages, but it looks like it's not possible (yet).
Anyway, now it works in my app :) Thanks a lot for your help !!
