### ISSUE TITLE
System.NotImplementedException: '[Plugin.LocalNotification] No platform plugin found.  Did you install the nuget package in your app project as well?'

### ISSUE THREAD

**Issue by vihoman** [thudugala/Plugin.LocalNotification#400]
Not sure if this is the right place to get help but i've been stuck on this for a couple of days now and cant seem to figure out why
i pretty much followed this tutorial https://www.youtube.com/watch?v=dWdXXGa1_hI but get issues on the builder giving the error refered in the title. I installed the NuGet packet vers 10.1.4
Thanks in advance and apologies if this is the wrong place to get help

**Comment by shervinmontajam** [comment]
Hey guys,
I have this issue when I try to run my app with a Windows Machine selected

**Comment by vihoman** [comment]
@shervinmontajam any chance you've found a fix yet? Haven't been really active on this project but still stuck on the same error

**Comment by shervinmontajam** [comment]
Hi @vihoman  

Unfortunately, it is the same for me when I try to run it with Windows Machine ...
This is my error message:
[Plugin.LocalNotification] No platform plugin found.  Did you install the nuget package in your app project as well?

**Comment by thudugala** [comment]
@vihoman Can you please attach a sample project?

**Comment by thudugala** [comment]
@shervinmontajam this plugin only support iOS and Android, no windows support yet

**Comment by shervinmontajam** [comment]
@thudugala Thanks for the response, but are there any possibilities to solve the issue when running the app with Windows?

**Comment by thudugala** [comment]
@shervinmontajam can you attach a sample project. So I can understand what you are trying to achieve?

**Comment by shervinmontajam** [comment]
@thudugala I made some screenshots so maybe that helps.

I thought that in the case of Windows, the notification is ignored.

![image](https://github.com/thudugala/Plugin.LocalNotification/assets/33059260/e2c99474-0442-4f39-9bab-a2824a8ef59a)
![image](https://github.com/thudugala/Plugin.LocalNotification/assets/33059260/5ffef0f6-326a-4554-8f70-39457158dc2c)
![image](https://github.com/thudugala/Plugin.LocalNotification/assets/33059260/da23ed71-4040-4fdd-9da3-416cbc2febc8)
![image](https://github.com/thudugala/Plugin.LocalNotification/assets/33059260/7f897f34-d8e2-4164-9cc5-51e86f4893f1)

**Comment by thudugala** [comment]
@shervinmontajam wrap the UseLocalNotification call with conditional compilation so it is only for Android and iOS

cc @vihoman 

```cs
public static MauiApp CreateMauiApp()
{
	var builder = MauiApp.CreateBuilder();
	builder
		.UseMauiApp<App>()
		.........
#if ANDROID || IOS
		.UseLocalNotification();
#endif
			
	return builder. Build();
}
```

**Comment by vihoman** [comment]
@thudugala just noticed the replies. I'm pretty sure i was having the same troubles as @shervinmontajam will try if it works later today and if not will add a sample project. Thanks for the help!
