### ISSUE TITLE
Notifications doesn't show up on Android 13. It doesn't request for permission. Xamarin.Forms 

### ISSUE THREAD

**Issue by JuanTamburini** [thudugala/Plugin.LocalNotification#401]
**Describe the bug**
On Android 13 in a xamarin.forms app the plugin does not request for permission (and doesn't show the notification) even using the line indicated:

```
if (await LocalNotificationCenter.Current.AreNotificationsEnabled() == false)
{
    await LocalNotificationCenter.Current.RequestNotificationPermission();
}
```

Phone: Pixel 5 simulator
OS Version: Android 13 (API 33)
Plugin version: 10.1.4

**Comment by andrei-cb** [comment]
works for me, check the manifest.

**Comment by thudugala** [comment]
@JuanTamburini Can you please attach a sample project?

**Comment by IamMarek** [comment]
@JuanTamburini  I've faced the same issue in my Xamarin.Forms project. The implementation of _RequestNotificationPermission_ seem to be calling MAUI api and only returns true in Xamarin.Forms apps. I've ended up with the following code in the main activity.  

```
protected async override void OnCreate(Bundle savedInstanceState)
        {
...
  var areNotificationsEnabled = await GrantNotificationPermissions(); 
            if(areNotificationsEnabled)
            {
                await InitNotifications();
            }
...
}

private const int PERMISSION_REQUEST_CODE = 12345678;

        private async Task<bool> GrantNotificationPermissions()
        {
            var areNotificationsEnabled = await LocalNotificationCenter.Current.AreNotificationsEnabled(); 

            if (!areNotificationsEnabled)
            {
                this.RequestPermissions(new string[] { Manifest.Permission.PostNotifications }, PERMISSION_REQUEST_CODE);
            }

            return areNotificationsEnabled; 
        }

        public override async void OnRequestPermissionsResult(int requestCode, string[] permissions, [GeneratedEnum] Android.Content.PM.Permission[] grantResults)
        {
            Xamarin.Essentials.Platform.OnRequestPermissionsResult(requestCode, permissions, grantResults);
            base.OnRequestPermissionsResult(requestCode, permissions, grantResults);

            if(requestCode == PERMISSION_REQUEST_CODE)
            {
                await InitNotifications(); 
            }
        }
```

**Comment by thudugala** [comment]
@JuanTamburini Yes RequestNotificationPermissionAsync is not yet implemented for Android xamarin.forms

cc @IamMarek

**Comment by masterofdaemon** [comment]
on .net MAUI same problem, how can i fix it? on .net 7 & 8 preview4

**Comment by thudugala** [comment]
@masterofdaemon Add these permissions

```xml
<uses-permission android:name="android.permission.WAKE_LOCK" />
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
<uses-permission android:name="android.permission.VIBRATE" />

<uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />
<uses-permission android:name="android.permission.POST_NOTIFICATIONS" />
```

https://github.com/thudugala/Plugin.LocalNotification/wiki/Usage-10.0.0--.Net-MAUI

**Comment by ComptonAlvaro** [comment]
I have the same problem with Android 12 API 31. The problem is with this version of the plugin, the version before it works for me.

I am following the documentation that you comment in the link but the notification is not shown.

- I the MUIProgram.cs fileI add .UseLocalNotification
- In the manifest, I add all the permissions
- I request for the permission, but it never ask for it

This is the code when I try to show a notification:

```
NotificationRequest miRequest = new NotificationRequest
            {
                NotificationId = 1000,
                Title = "My Application Name",
                Description = "Notification from LocalNotification Plugin.",
                BadgeNumber = 42,
                Image = new NotificationImage(),
                Schedule = new NotificationRequestSchedule
                {
                    NotifyTime = DateTime.Now.AddSeconds(5),
                },
            };

            LocalNotificationCenter.Current.Show(miRequest);
```


Thanks so much.

**Comment by ComptonAlvaro** [comment]
it works, in my case I forgot to add the permission <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" /> in the manifest.


Thanks so much.

**Comment by oyve** [comment]
@thudugala I have the exact same error after updating to latest package today (last update prior to this back in March...)
However not able to set `LocalNotificationCenter.MainActivity = this;` in code.

```
if (await LocalNotificationCenter.Current.AreNotificationsEnabled() == false)
{
    await LocalNotificationCenter.Current.RequestNotificationPermission();
}
```

```
<uses-permission android:name="android.permission.WAKE_LOCK" />
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
<uses-permission android:name="android.permission.VIBRATE" />
<uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />
<uses-permission android:name="android.permission.POST_NOTIFICATIONS" />
```

PluginLocalNotificaitons v10.1.8
Xamarin.Forms 5.0.0.2612

And seem to be pretty much aligned with DOCs https://github.com/thudugala/Plugin.LocalNotification/wiki/2.-Usage-10.0.0-Xamarin.Forms  .. any clues?

**Comment by oyve** [comment]
To answer my own question, got it working. What I missed was the upgrade from Android platform targeting v12->v13.
The solution was posted with the above links by @thudugala , but I'll add a complete sample for anyone who find it useful.

In your shared project:
 ```
   public interface INotificationPermission
    {
        Task<PermissionStatus> CheckStatusAsync();
        Task<PermissionStatus> RequestAsync();
    }
```

In your Android project:
```
    public class NotificationPerm : BasePlatformPermission, INotificationPermission
    {
        public override (string androidPermission, bool isRuntime)[] RequiredPermissions => new List<(string androidPermission, bool isRuntime)>
        {
            ("android.permission.POST_NOTIFICATIONS", true),
        }.ToArray();
    }
```
        ```
public MainActivity()
        {
            DependencyService.Register<INotificationPermission, NotificationPerm>();
}
```

In your shared project, now able to use it like this:
(NOTE: Denying the permission two times in a row, sets it in a PermissionStatus.Denied state, and Android will not ask again. You'll then have to change into your Android Permissions settings manually.

  async Task AskForPermission()
  {
      var permission = DependencyService.Get<INotificationPermission>();
      var status = await permission.CheckStatusAsync();

      if (status == PermissionStatus.Granted)
      {
//... we're good to go, do something!
      }
      else
      {
          status = await permission.RequestAsync();

          if (status == PermissionStatus.Granted)
          {
//...  user clicked "Allow" in notification, do something!
          }
          else
          {
// run it again
              await Task.Delay(TimeSpan.FromSeconds(2));
              await AskForPermission();
          }
      }
  }
