### ISSUE TITLE
Is this project still supported?

### ISSUE THREAD

**Issue by Sebosek** [thudugala/Plugin.LocalNotification#404]
**Is your feature request related to a problem? Please describe.**
From the list of open bugs without any response from the author, it looks like the project was abandoned.

**Describe the solution you'd like**
I would like to know what is happening with this project and if I should use it or start working on my own implementations.

**Describe alternatives you've considered**
Start working on custom platform-specific solution.

**Additional context**
None.

**Comment by mos379** [comment]
@Sebosek the last release is barely 2 months ago, sometimes people have lives too. 
I highly doubt that this project is abandoned as @thudugala just recently added maui support...

**Comment by Sebosek** [comment]
@mos379 based on the number of issues without any response from the author/maintainer(s) it's a fair question, isn't it? More importantly, some of them might be considered as show-stoppers.

**Comment by mos379** [comment]
@Sebosek why not creating PRs for this project then? If you are in need of specific things?
Isn't that a lot faster than working out a complete own implementation?

**Comment by Sebosek** [comment]
@mos379 well if project would be abandoned, who would approve the PR?

**Comment by mos379** [comment]
@Sebosek valid point, but I doubt that's happening, but if so you could still continue working on the fork

**Comment by thudugala** [comment]
@Sebosek, Yes, this project is still live. I had some different priorities.

cc @mos379 @wcoder @GitBOUF @Epictek
