### ISSUE TITLE
Error when I try to compile the samples

### ISSUE THREAD

**Issue by ComptonAlvaro** [thudugala/Plugin.LocalNotification#419]
I have download the code, I open the sample\direct MAUI solution and when i try to compile, I get this error:

xamarin.androidx.lifecycle.common\2.6.1.1\buildTransitive\net6.0-android31.0\..\..\jar\androidx.lifecycle.lifecycle-common.jar:androidx/lifecycle/LifecycleController.class:
Type androidx.lifecycle.LifecycleController is defined multiple times: d:\Users\AGarcia\.nuget\packages\xamarin.androidx.lifecycle.common\2.6.1.1\buildTransitive\net6.0-android31.0\..\..\jar\androidx.lifecycle.lifecycle-common.jar:androidx/lifecycle/LifecycleController.class, obj\Debug\net7.0-android\lp\144\jl\classes.jar:androidx/lifecycle/LifecycleController.class

Thanks.

**Comment by thudugala** [comment]
@ComptonAlvaro https://github.com/dotnet/maui/issues/4276

**Comment by thudugala** [comment]
Downgraded Xamarin.GooglePlayServices.Location from 120.0.0.2 to 120.0.0.1

@ComptonAlvaro try now

**Comment by ComptonAlvaro** [comment]
Thanks for your attention.

I don't have the package that you mention. I have this:

![imagen](https://github.com/thudugala/Plugin.LocalNotification/assets/20024410/03fd067e-eb5d-41f1-beb4-ad5f62c762ae)

**Comment by thudugala** [comment]
@ComptonAlvaro This plugin depends on it. Now it's fixed

**Comment by ComptonAlvaro** [comment]
It works now. Thanks so much.
