### ISSUE TITLE
[Android] Playing Preferred Sound

### ISSUE THREAD

**Issue by jrahma** [thudugala/Plugin.LocalNotification#42]
Hi,

In this link:

[https://github.com/thudugala/Plugin.LocalNotification/wiki/Notification-with-a-Sound-File](https://github.com/thudugala/Plugin.LocalNotification/wiki/Notification-with-a-Sound-File)

It's mentioned from Androidn >= 26 the sound must be set in Channel Level

What if I have different sound files and it depends on the user preference the sound should play?

Thanks,
Jassim

**Comment by thudugala** [comment]
@jrahma you should create different Notification Channels with different names
