### ISSUE TITLE
The buttons of actions are not shown in the notificaction

### ISSUE THREAD

**Issue by ComptonAlvaro** [thudugala/Plugin.LocalNotification#420]
I would like to have 2 buttons in the notificactions. For that, I am following the [documentation](https://github.com/thudugala/Plugin.LocalNotification/wiki/Notification-with-Action)

Also I am follow the sample code in samples\direct MAUI.

From the sample, I copy the code in MAUIProgram.cs file and then tried to publish a notificaction with this code:

```
NotificationRequest miRequest = new NotificationRequest
    {
        NotificationId = 1,
        Title = "MyTitle",
        Description = "test notification with actions",
        BadgeNumber = 42,
        Image = new NotificationImage(),
        Schedule = new NotificationRequestSchedule
        {
            NotifyTime = DateTime.Now,
        },
    };
    LocalNotificationCenter.Current.Show(miRequest);
```

But the notification deson't show any button.

In the sample code i don't see any another needed configuration more than the cofiguration code in the MAUIProgram.cs file.

Thanks.

EDIT: I add a project that shows the problem.
[MAUIPluginLocalNotificationsWithActions.zip](https://github.com/thudugala/Plugin.LocalNotification/files/11732357/MAUIPluginLocalNotificationsWithActions.zip)

This is the result:

![imagen](https://github.com/thudugala/Plugin.LocalNotification/assets/20024410/f03015ac-26c4-43da-ba15-9e981337a4e1)

Thanks so much.

**Comment by thudugala** [comment]
@ComptonAlvaro can you please attach a sample project?

**Comment by thudugala** [comment]
@ComptonAlvaro The NotificationCategoryType does not match in the request and the config AddCategory

![image](https://github.com/thudugala/Plugin.LocalNotification/assets/4112014/aef60977-3361-494e-bf86-8c2ecbbe4988)

![image](https://github.com/thudugala/Plugin.LocalNotification/assets/4112014/e28b39ab-a610-42bd-b62f-128a71fe32fd)

**Comment by ComptonAlvaro** [comment]
It works. Thanks so much.
