### ISSUE TITLE
10.1.6 Notification are not generated either on Real Phones nor Simulators iOS 

### ISSUE THREAD

**Issue by samirgcofficial** [thudugala/Plugin.LocalNotification#427]
**Describe the bug**
Android works fine but iOS Tested on real phones and simulators notification not received. 

**To Reproduce**
Brand new .Net7 project add Plugin.LocalNotification 
`if (await LocalNotificationCenter.Current.AreNotificationsEnabled() == false)
        {
            await LocalNotificationCenter.Current.RequestNotificationPermission();
        }

        var notification = new NotificationRequest
        {
            NotificationId = 100,
            Title = "Test",
            Description = "Test Description",
            ReturningData = "Dummy data", // Returning data when tapped on notification.
            Schedule =
            {
                NotifyTime = DateTime.Now.AddSeconds(2) // Used for Scheduling local notification, if not specified notification will show immediately.
            }
        };
        await LocalNotificationCenter.Current.Show(notification);`
        
And of course use this : 
.UseLocalNotification()

Getting this output on simulator : 

Plugin.LocalNotification.LocalNotificationCenter: Error: WillPresentNotification: 

System.NullReferenceException: Object reference not set to an instance of an object.
   at Plugin.LocalNotification.Platforms.UserNotificationCenterDelegate.WillPresentNotification(UNUserNotificationCenter center, UNNotification notification, Action`1 completionHandler)

Sample : http://xamaringuyshow.com/wp-content/uploads/2023/06/iOSlatestNotWorking.zip

**Comment by thudugala** [comment]
@samirgcofficial please try version 10.1.7

**Comment by samirgcofficial** [comment]
It works thanks :)
