### ISSUE TITLE
Android exception thrown in 10.1.8

### ISSUE THREAD

**Issue by LeoJHarris** [thudugala/Plugin.LocalNotification#429]
Java.Lang.NullPointerException: 'Attempt to invoke virtual method 'void android.app.Activity.requestPermissions(java.lang.String[], int)' on a null object reference'

Appears to be an exception being thrown when calling `await _notificationService.RequestNotificationPermission().ConfigureAwait(false);` I rolled back to 10.1.7 and it worked again.

Running an android emulator API 33 using XF 5.0.0.2478

Additional error log below

`
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: Java.Lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.requestPermissions(java.lang.String[], int)' on a null object reference
[mono-rt]   at Java.Interop.JniEnvironment+StaticMethods.CallStaticVoidMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00068] in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/JniEnvironment.g.cs:13250 
[mono-rt]   at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeVoidMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00008] in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniStaticMethods.cs:97 
[mono-rt]   at AndroidX.Core.App.ActivityCompat.RequestPermissions (Android.App.Activity activity, System.String[] permissions, System.Int32 requestCode) [0x00057] in C:\a\_work\1\s\generated\androidx.core.core\obj\Release\monoandroid12.0\generated\src\AndroidX.Core.App.ActivityCompat.cs:565 
[mono-rt]   at Plugin.LocalNotification.LocalNotificationCenter.RequestNotificationPermissionAsync (Plugin.LocalNotification.NotificationPermission permission) [0x000b3] in <e49bc52a77b244c2b3563ad13c4b45b7>:0 
`

**Comment by thudugala** [comment]
@LeoJHarris 

Can you try setting under Android on create. 

LocalNotificationCenter.MainActivity = this;

**Comment by LeoJHarris** [comment]
That fixes the issue. Thanks
