### ISSUE TITLE
Raising NotificationReceiving without permissions granted to execute some code

### ISSUE THREAD

**Issue by LeoJHarris** [thudugala/Plugin.LocalNotification#430]
**Is your feature request related to a problem? Please describe.**

If the notifications permission is not granted any scheduled notifications will not raise the `NotificationReceiving` however raising notification receiving event maybe useful where we might want to update say a notifications page without actually surfacing a local notification/alert if the notifications permission was not granted.

**Describe the solution you'd like**

Add another event that allows code execution without surfacing alert or leveraging from the existing `NotificationReceiving` event, provide something like the follows:

```csharp
 public class NotificationReceivedPayloadEventArgs : NotificationEventArgs
    {
        /// <summary>
        /// Indicated if a local notification notification was surfaced
        /// </summary>
        public bool NotificationDisplayed { get; set; }
    }
```

**Describe alternatives you've considered**

Currently its hard to execute some code at a future point in time without using timers and delays. Alerts would provide a mechanism to achieve code execution and would be useful for user cases such as notifications pages where notifications permissions are not granted.

**Comment by thudugala** [comment]
@LeoJHarris It seems in iOS it is not possible to do so without permission to show notifications

**Comment by LeoJHarris** [comment]
Okay, no problem, obviously leveraging the scheduling mechanism wouldn't be any option so if that's the case Ill close this issue.
