### ISSUE TITLE
'Current' is not available in iOS - NotificationCenter

### ISSUE THREAD

**Issue by ashishemm** [thudugala/Plugin.LocalNotification#44]
I installed the nuget package in both Android and iOS projects of Xamarin Forms project. 
The NotificationCenter.Current property has a compilation error that it does not exist in the iOS project. I tried changing the iOS deployment target to 11, but still the error exist.

I couldn't show the notification due to this issue.

Refer the attached screenshot.
![Screenshot 2019-09-28 at 20 32 12](https://user-images.githubusercontent.com/49930392/65818457-209cd480-e22f-11e9-9c7b-23e5f7d1076e.png)

**Comment by thudugala** [comment]
@masonyc can you help. Don't have access to mac right now.

**Comment by masonyc** [comment]
@ashishemm Hi, I could not reproduce this in the sample application. Can you please upload a repo?

**Comment by ashishemm** [comment]
[test.zip](https://github.com/thudugala/Plugin.LocalNotification/files/3681102/test.zip)
I've attached the code here

**Comment by masonyc** [comment]
@ashishemm  you have to link the NuGet package to your shared project as well, which I am not too sure how to do in .shproj project.

**Comment by thudugala** [comment]
closing as there is no response @ashishemm

**Comment by Zalut** [comment]
Hi, 
i have the same problem as the autor, my NotificationCenter.Current.Show(notification) don't work for iOS, i've linked the NuGet package to the both projet iOS and Android

**Comment by thudugala** [comment]
@Zalut please attach a sample project.

**Comment by Zalut** [comment]
@thudugala i can't send you my project, but i can answer your questions. I've installed the v5.2.0 of the package, it work with android, but not with iOS. I can't take new version of the package because my project target version for android is 10.0...

**Comment by thudugala** [comment]
@Zalut Sorry, to make my self clear, I'm asking you to create a sample project that recreate this issue and upload it here as a zip file.

**Comment by Zalut** [comment]
Hi, unfortunately I cannot recreate a similar project with the 2019 version of Visual Studio. The project type is PCL, the project was originally made for Android, I added an iOS project to the solution recently, and my problem with NotificationCenter.Current occurred at that time.
