### ISSUE TITLE
Not displaying badge on Xiaomi devices

### ISSUE THREAD

**Issue by adam-musiol** [thudugala/Plugin.LocalNotification#440]
**Describe the bug**
On Xiaomi devices badge is not working. Local notification shows up, but badge is not showing on app icon. 
On emulator local notification & badge is working fine.

**To Reproduce**
1. Start new MAUI project
2. Install Plugin.LocalNotification package via NUGET
3. Setup local notification with badge
4. See local notification on device without badge

**Expected behavior**
Local notification with badge

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi 9A
 - OS: Android 10
 - Version MIUI 12.0.20

**Sample project attached**

[MauiNotifications.zip](https://github.com/thudugala/Plugin.LocalNotification/files/12144262/MauiNotifications.zip)

**Comment by thudugala** [comment]
@adam-musiol This is a device-specific issue. Check your device settings.

**Comment by thudugala** [comment]
@adam-musiol Do you have any other device to test that is only happening on Xiaomi devices? 

I do not have Xiaomi phone to test this. We need help from someone else.

**Comment by adam-musiol** [comment]
I've been doing more tests and it turned out that I had to enable POSTNOTIFICATIONS permission in Android Manifest and it started working.

**Comment by thudugala** [comment]
@adam-musiol can you get the badge to work with https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/essentials/badge?tabs=tizen

**Comment by adam-musiol** [comment]
> @adam-musiol can you get the badge to work with https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/essentials/badge?tabs=tizen

It doesn't work for any device. 
I've used https://github.com/CommunityToolkit/Maui/tree/main/samples/CommunityToolkit.Maui.Sample where what You've send is implemented.
On stock android and xiaomi it displays in debugger "Current launcher doesn't support badge counter". On Samsung with Android 13 it just throws error related to permissions. 
In overall I don't think it's finished.
