### ISSUE TITLE
`NotificationReceiving` not called when implementing UNUserNotificationCenterDelegate

### ISSUE THREAD

**Issue by LeoJHarris** [thudugala/Plugin.LocalNotification#445]
Might be more a configuration question but we have remote notification support so we are overriding the `WillPresentNotification` and `DidReceiveNotificationResponse` similar to what you see below (code  stripped out):

```csharp
public class UserNotificationCenterDelegate : UNUserNotificationCenterDelegate
    {
        #region Constructors

        public UserNotificationCenterDelegate()
        {
        }

        #endregion Constructors

        #region Override Methods

        public override void DidReceiveNotificationResponse(UNUserNotificationCenter center, UNNotificationResponse response, Action completionHandler)
        {
            ...
        }

        public override void WillPresentNotification(UNUserNotificationCenter center, UNNotification notification, Action<UNNotificationPresentationOptions> completionHandler)
        {
            ...
        }

        #endregion Override Methods
    }
```

And in `AppDelegate` we setup our `UserNotificationCenterDelegate` and set accordingly:

```csharp
public override bool FinishedLaunching(UIApplication app, NSDictionary options)
        {
            global::Xamarin.Forms.Forms.Init();

            LocalNotificationCenter.SetUserNotificationCenterDelegate();
            UNUserNotificationCenter.Current.Delegate = new UserNotificationCenterDelegate();

            LoadApplication(new App(new iOSInitializer()));
            return base.FinishedLaunching(app, options);
        }
```

The problem the `NotificationReceiving` event is not being called:

#### below prevents `NotificationReceiving` from being called ####

```csharp
UNUserNotificationCenter.Current.Delegate = new UserNotificationCenterDelegate();
```
We need access to the overridden methods in the `UserNotificationCenterDelegate` to handle remote notifications in the foreground which is working fine but now the `NotificationReceiving` has stopped firing

**Comment by LeoJHarris** [comment]
After a little bit more playing around,
[NuGet.zip](https://github.com/thudugala/Plugin.LocalNotification/files/12354858/NuGet.zip)

See example project.

**Comment by thudugala** [comment]
@LeoJHarris when you call SetUserNotificationCenterDelegate pass in UserNotificationCenterDelegate 

look at on implementing custom CustomUserNotificationCenterDelegate
Sample/Direct Maui/LocalNotification.Sample/Platforms/iOS/CustomUserNotificationCenterDelegate.cs
