### ISSUE TITLE
Unable to localize Action Button text in MAUI

### ISSUE THREAD

**Issue by sfysi** [thudugala/Plugin.LocalNotification#446]
**Describe the bug**
The `NotificationAction` class has a `string Title` property, but as the application context does not exist yet in the `MauiProgram.CreateMauiApp` method, trying to assign this property to something like `Platform.CurrentActivity.Resources.GetString(Resource.String.some_string_key)` will fail, and `Resource.String.some_string_key` itself is just an `int` that can't be assigned to the `Title` property.

**To Reproduce**
1. Use `builder.UseLocalNotification` to initialize configuration settings.
2. Use `config.AddCategory` to create a category and give it an `ActionList` of `NotificationAction` objects.
3. Try setting the `Title` of one of them to use `Resources.GetString`.
4. Build and deploy the app, and it will immediately crash on startup.

**Expected behavior**
The localized string can be used.

**Platform (please complete the following information):**
 - OS: Android 12.0 - API 31
 - Plugin.LocalNotification version 10.1.8

**Smartphone (please complete the following information):**
 - Device: Galaxy S10e

**Comment by thudugala** [comment]
@sfysi can you please attach a sample project?

**Comment by sfysi** [comment]
@thudugala - In the process of creating a sample project I discovered that MAUI has its own platform-agnostic localization handling, and while the Android-specific `strings.xml` files in `Platforms/Android/Resources/values` can't be accessed in the `CreateMauiApp` method, the `Resources/Localization/AppStrings.resx` files can, so that can be used for handling the button translations. Looks like no changes are needed after all. Thank you for your time!
