### ISSUE TITLE
Usage instructions code sample shows wrong argument type for OnNotificationActionTapped example 

### ISSUE THREAD

**Issue by anthony-glenwright** [thudugala/Plugin.LocalNotification#449]
**Describe the bug**
The code sample at https://github.com/thudugala/Plugin.LocalNotification/wiki/1.-Usage-10.0.0--.Net-MAUI has an example of an event handler for the NotificationActionTapped event in the ""Receive local notification tap event" section" section:

`private void OnNotificationActionTapped(NotificationEventArgs e)`

In order to use the IsDismissed, IsTapped and ActionId properties in the current version (10.1.8) the "e" argument needs to be a  NotificationActionEventArgs, not a NotificationEventArgs:

`private void OnNotificationActionTapped(NotificationActionEventArgs e)`

**Comment by thudugala** [comment]
@anthony-glenwright document is fixed, thank you.
