### ISSUE TITLE
The notification is not working when the app is closed. How we can rectify the issue?

### ISSUE THREAD

**Issue by anoopkrishnan123** [thudugala/Plugin.LocalNotification#452]
The notification is not working when the app is closed. How we can rectify the issue?

**Comment by thudugala** [comment]
@anoopkrishnan123 can you please attach a sample project?

**Comment by anoopkrishnan123** [comment]
Hi sir

This is the repo

https://github.com/jfversluis/XFLocalNotifications

**Comment by thudugala** [comment]
@anoopkrishnan123 this is a very old example. please follow https://github.com/thudugala/Plugin.LocalNotification/wiki/1.-Usage-10.0.0--.Net-MAUI

**Comment by phamquoctuan1** [comment]
hi Mr.@thudugala I have tried this example for xamarins forms. but still cannot receive notification when the app is closed.
could you please help me to check this?

**Comment by anoopkrishnan123** [comment]
> hi Mr.@thudugala I have tried this example for xamarins forms. but still cannot receive notification when the app is closed. could you please help me to check this?

Hi,
I resolved my issue. Create a foreground service and this will work even when the app is closed.
