### ISSUE TITLE
Repeat Notification doesn't work

### ISSUE THREAD

**Issue by ShariatPanah** [thudugala/Plugin.LocalNotification#454]
**Describe the bug**
so i want to set the notification to repeat for example every 5 minutes, so i use this code:
```
_request = new NotificationRequest
{
.
.
.
  Schedule =
  {
      RepeatType = NotificationRepeat.TimeInterval,
      NotifyRepeatInterval = TimeSpan.FromMinutes(5)
  }
};
```

but it just shows the notification only once and it won't repeat, i tried even with your sample but with no luck, maybe I'm missing something?

**To Reproduce**
just run your sample and edit your code to have a TimeInterval Repeat mode notification

**Platform**
 - OS: Android
 - Version: Android 12.0 Api 31

**Smartphone:**
 - Device: Huawei Mate 10 Lite
 - OS: Android
 - Version: 8.0 Api 26

**Comment by thudugala** [comment]
@ShariatPanah https://github.com/thudugala/Plugin.LocalNotification/wiki/4.-Repeat-Notification

Can you please attach sample project?

**Comment by ShariatPanah** [comment]
i've attached the sample project i just created
i tested this on pixel 5 emulator with api 31 android 12.0

[LocalNotificationBug.zip](https://github.com/thudugala/Plugin.LocalNotification/files/12837422/LocalNotificationBug.zip)

**Comment by ShariatPanah** [comment]
Hey @thudugala did you test it?

**Comment by thudugala** [comment]
@ShariatPanah To repeat a notification, the notification must be Scheduled. You can Schedule notifications by setting NotifyTime in NotificationRequest.

https://github.com/thudugala/Plugin.LocalNotification/wiki/4.-Repeat-Notification

**Comment by thudugala** [comment]
@ShariatPanah Please read this doc. I do not think you have configured this project correctly https://github.com/thudugala/Plugin.LocalNotification/wiki/1.-Usage-10.0.0--.Net-MAUI

**Comment by ShariatPanah** [comment]
sorry my bad :) thanks
