### ISSUE TITLE
Version conflict when updating Xamarin.Android.Arch.Work.Runtime

### ISSUE THREAD

**Issue by tranb3r** [thudugala/Plugin.LocalNotification#48]
I have this warning when building my app:
`NU1107: Version conflict detected for ....`
` ... -> Xamarin.Essentials 1.3.1 -> Xamarin.Android.Support.Core.Utils 28.0.0.3 -> Xamarin.Android.Support.Loader 28.0.0.3 -> Xamarin.Android.Arch.Lifecycle.LiveData 1.1.1.3 -> Xamarin.Android.Arch.Core.Common (= 1.1.1.3)`
` ... -> Plugin.LocalNotification 4.0.6 -> Xamarin.Android.Arch.Work.Runtime 1.0.0 -> Xamarin.Android.Arch.Lifecycle.Extensions 1.1.1.1 -> Xamarin.Android.Arch.Core.Common (= 1.1.1.1).`

Could you please publish a Plugin.LocalNotification 4.0.7 referencing Xamarin.Android.Arch.Work.Runtime 1.0.0.3 instead of 1.0.0 ?

xamarin/AndroidSupportComponents/issues/204

**Comment by thudugala** [comment]
[4.0.7](https://www.nuget.org/packages/Plugin.LocalNotification/4.0.7) published
