### ISSUE TITLE
[UPDATE WIKI] Notification with a sound

### ISSUE THREAD

**Issue by Kebechet** [thudugala/Plugin.LocalNotification#487]
While working on notification sounds I found more information that would be helpful for others as well. So please update:
https://github.com/thudugala/Plugin.LocalNotification/wiki/Notification-with-a-Sound-File

**with this information:**

- android doesn't have to to have [file without extension](https://i.imgur.com/SHJVZNu.png) because [here](https://github.com/thudugala/Plugin.LocalNotification/blob/a53ba6610a9b435f3fb910defb80328521a996d8/Source/Plugin.LocalNotification/Platforms/Android/LocalNotificationCenter.cs#L154) you are removing it
- android supported formats are mainly: `mp3`, `m4a`, `wav`, `ogg` based on [doc](https://developer.android.com/media/platform/supported-formats)
- iOS supported formats are: `aiff`, `wav`, `caf` based on [doc](https://developer.apple.com/documentation/usernotifications/unnotificationsound)
  - at the same time sound has to be smaller than 30s 
- best sound format is probably `wav` because it is supported by both platforms
- the reason android sound has to be in platform specific raw folder is that if you put it to global `Resources/Raw` it would be stored not as resource but as asset. And it is not possible to get path to asses, only to resource. If this thing would work it allow to use iOS `BundleResource` because it would be automatically generated from global `Resources/Raw`

**Comment by Kebechet** [comment]
@thudugala could you please add it to wiki ? Because I cant create a PR there.
https://stackoverflow.com/a/11481887/6158341

**Comment by thudugala** [comment]
done
