### ISSUE TITLE
Can't play a custom notification, it keeps playing the default.

### ISSUE THREAD

**Issue by WhileTrueThenRock** [thudugala/Plugin.LocalNotification#498]
**Describe the bug**
Hello, i've followed this guide: 
https://github.com/thudugala/Plugin.LocalNotification/wiki/Notification-with-a-Sound-File

**Screenshots**
I've attached 2 screenshots
I'm on windows 10,  visual studio code 17.9.6
Pixel 5 api 35, .net 8 , latest version of plugin.LocalNotification 11.1.2

Any tips ? 
Much appreciated anyways!

![Annotation 2024-05-08 141334](https://github.com/thudugala/Plugin.LocalNotification/assets/130988912/5c1f892d-2b6c-40a3-a222-a742c9533ef7)
![Annotation 2024-05-08 141212](https://github.com/thudugala/Plugin.LocalNotification/assets/130988912/52c248e2-0bfd-47cb-a893-fd1fccf361e7)

**Comment by chnoergaard** [comment]
@WhileTrueThenRock 
It looks like you are using Maui, correct? Then you should move the "raw" folder til the Platforms -> Android and/or iOS -> Resources folder. Not in the root Resources folder.

Also make sure these are set:

Must be 128kps (320kps does not work)
BuildAction must be set to AndroidResource

**Comment by WhileTrueThenRock** [comment]
Thanks for answering, it worked!
It was moving the folder to the platform of Android and setting the buildAction to Android Resource
