### ISSUE TITLE
How to Bypass Android Volume When Set to Zero and Play Notification Sound at Max Volume

### ISSUE THREAD

**Issue by lpv-1902** [thudugala/Plugin.LocalNotification#499]
Hi everyone,

I'm working on an Android app and I have a specific requirement for notifications. I need to bypass the system volume settings, especially when the volume is set to zero, and ensure that my notification sound plays at maximum volume. This is similar to how critical alerts work in iOS.

Is there a way to achieve this using this great plugin? Any guidance or examples would be greatly appreciated.

Thank you in advance!

**Comment by Kebechet** [comment]
is it even possible to do on android devices ?

**Comment by thudugala** [comment]
@lpv-1902 try https://medium.com/@surendar1006/implementing-critical-alerts-on-android-aa49b4d75705

**Comment by lpv-1902** [comment]
Thanks, I have implemented this using Critical Alerts and a combination of turning off do not disturb, setting ringer mode to Ring, turning notification volume to max and letting the critical alert run. Afterwards I set all the values to their previous setting.
