### ISSUE TITLE
How does group notification work?

### ISSUE THREAD

**Issue by dg2k** [thudugala/Plugin.LocalNotification#501]
First of all, I do not think the code for [group notification Wiki](https://github.com/thudugala/Plugin.LocalNotification/wiki/%5BAndroid%5D-How-to-group-notifications) is correct. There is no **Group** property for `NotificationRequest.Android` and the code examples shown won't compile.

`
var notification = new NotificationRequest
{
    NotificationId = 100,
    Title = "Summary",
    Description = "Summary Description",
    Android =
    {
        Group = "example.GROUP_01",
        IsGroupSummary = true
    }
};
LocalNotificationCenter.Current.Show(notification);
`

The property setting `Group = "example.GROUP_01",` is an issue.

The example code being erroneous, what is the correct way to set a group notification whereby notifications are shown as stacked under a group (to be expanded and collapsed)?

**Comment by thudugala** [comment]
@dg2k documentation updated, can you try again
