### ISSUE TITLE
Actions in iOS MAUI

### ISSUE THREAD

**Issue by TonyLugg** [thudugala/Plugin.LocalNotification#505]
The docs don't seem to include iOS in the Notification Actions examples.  I implemented action buttons but they only show up in Android; iOS doesn't even show the buttons.

**Comment by LeoJHarris** [comment]
Same problem here but still using Xamarin, no action buttons on iOS showing, android working fine.

**Comment by TonyLugg** [comment]
I determined it is an iOS thing. I decided not to use buttons.

**Comment by LeoJHarris** [comment]
@TonyLugg Shame, iOS does support this functionality but seems this library doesn't.

**Comment by TonyLugg** [comment]
@LeoJHarris I noticed that Microsoft Authenticator used buttons for authorization on Android but not on iOS so I thought there must be a reason they aren't on iOS.

**Comment by LeoJHarris** [comment]
@TonyLugg iOS has entire documentation on notification actions https://developer.apple.com/documentation/usernotifications/handling-notifications-and-notification-related-actions

**Comment by TonyLugg** [comment]
@thudugala Any thoughts on making notification buttons work on iOS?

**Comment by thudugala** [comment]
iOS actions are already there
![Screenshot 2024-07-06 111914](https://github.com/thudugala/Plugin.LocalNotification/assets/4112014/84109764-f1db-41e9-895f-de98c95185b7)

**Comment by TonyLugg** [comment]
> @TonyLugg @LeoJHarris  iOS actions are already there
> 
> ![Screenshot 2024-07-06 111914](https://github.com/thudugala/Plugin.LocalNotification/assets/4112014/84109764-f1db-41e9-895f-de98c95185b7)
> 
> 
> 
> 

Cool, is it documented in your library?

**Comment by thudugala** [comment]
@TonyLugg try
 https://github.com/thudugala/Plugin.LocalNotification/wiki/5.-Notification-with-Action

**Comment by TonyLugg** [comment]
@thudugala I have my code exactly like yours in a test project but I only get the notification, not the buttons.  Like this:

![image](https://github.com/thudugala/Plugin.LocalNotification/assets/3819142/454feb33-26dd-4c26-bba4-1c5fc3e6fcc1)

**Comment by LeoJHarris** [comment]
> @thudugala I have my code exactly like yours in a test project but I only get the notification, not the buttons.  Like this:
> 
> ![image](https://github.com/thudugala/Plugin.LocalNotification/assets/3819142/454feb33-26dd-4c26-bba4-1c5fc3e6fcc1)
> 
> ![image](https://github.com/thudugala/Plugin.LocalNotification/assets/3819142/4937c835-273c-43f5-bad1-43a0aa3a0c3a)
> 

Same here. Never saw the button actions. I'm running an emulator only to test. I'm not sure if it makes a difference.

**Comment by TonyLugg** [comment]
> > @thudugala I have my code exactly like yours in a test project but I only get the notification, not the buttons.  Like this:
> > 
> > ![image](https://github.com/thudugala/Plugin.LocalNotification/assets/3819142/454feb33-26dd-4c26-bba4-1c5fc3e6fcc1)
> > 
> > ![image](https://github.com/thudugala/Plugin.LocalNotification/assets/3819142/4937c835-273c-43f5-bad1-43a0aa3a0c3a)
> > 
> 
> Same here. Never saw the button actions. I'm running an emulator only to test. I'm not sure if it makes a difference.

I'm using a physical device, so no difference.

**Comment by thudugala** [comment]
@TonyLugg swipe down the notification

**Comment by TonyLugg** [comment]
@thudugala I see.  I'm not sure how our users will know to swipe down.  I'll probably still just open the app to the page that will give them the options.

For some reason, even with long press on the notification, and/or swipe down, I am still not getting the buttons.  The background of the screen blurs but no buttons show up.  I may play with it a bit more.

Thanks for building this plugin, it has really helped.
