### ISSUE TITLE
Android Review Fails: Use of Exact Alarms causing App to crash for some user

### ISSUE THREAD

**Issue by archergod** [thudugala/Plugin.LocalNotification#506]
We recently migrate our Xamarin app to Maui and when we submit it to Android for review they give following issue with app

![image](https://github.com/thudugala/Plugin.LocalNotification/assets/4686220/a5f21ca6-bfe1-4f4f-ae79-e2964191649c)

Now, to be frank I am not sure if it is because of library itself or Visual studio trimming corrupt it. Thought to get some insight on issue here ? 

PS: The Code is working absolutely fine on Simulator and alarms and stuff are going well.

**Comment by archergod** [comment]
I remove the "SCHEDULE_EXACT_ALARM" Permission and warning goes off. Now I am not sure how far off my alarm will ring. we are happy if it ring at say 30-50 seconds off, but we don't want it to be 3-4 minutes late ..

**Comment by thudugala** [comment]
@archergod It's out of this plugin's control. It depends on the Android OS and device manufacturer.

**Comment by archergod** [comment]
I agree, and I do not see as problem either, but maybe a line in FAQ is good about this thing. Thank for your the plugin though.
