### ISSUE TITLE
Unable to compile after updating to v11.1.4: java.exe error Java0000.

### ISSUE THREAD

**Issue by Qiulin-Git** [thudugala/Plugin.LocalNotification#508]
Unable to compile after updating to v11.1.4: java.exe error Java0000.
![2024-07-09 200803](https://github.com/thudugala/Plugin.LocalNotification/assets/53858121/0ef3afad-9add-470b-b5a4-83069b462267)

**Comment by jerry08** [comment]
I'm getting the same error. The latest commit fixes the problem (https://github.com/thudugala/Plugin.LocalNotification/commit/bacce66e215c44d942c8867a8e77707b55886c8e) but it hasn't been released yet.

Updating the AndroidX NuGet packges to the latest version will fix the current problem which was caused by updating `Xamarin.GooglePlayServices.Location` to the latest version (#507):

```c#
<ItemGroup Condition="$(TargetFramework.Contains('-android'))">
  <PackageReference Include="Xamarin.AndroidX.Fragment.Ktx" Version="1.8.1" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.Common" Version="2.8.3" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData.Core" Version="2.8.3" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData.Core.Ktx" Version="2.8.3" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.Process" Version="2.8.3" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime" Version="2.8.3" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime.Ktx" Version="2.8.3" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModel" Version="2.8.3" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModel.Ktx" Version="2.8.3" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModelSavedState" Version="2.8.3" />
</ItemGroup>
```

**Comment by Kirrasio** [comment]
Hey there, just wondering - I am working with .net maui api 31 Android 12.0 and am getting this error. Is there a workaround? I'm rather new and I need this for a class project that is due within the week.
