### ISSUE TITLE
Wiki example "[iOS] Working with push notifications" won't compile

### ISSUE THREAD

**Issue by eddieyanez** [thudugala/Plugin.LocalNotification#509]
**Describe the bug**
Example uses a method that's marked as internal **TryGetDefaultIOsNotificationService()**.

**To Reproduce**
Follow instructions on Wiki https://github.com/thudugala/Plugin.LocalNotification/wiki/%5BiOS%5D-Working-with-push-notifications.

**Expected behavior**

**Screenshots**
<img width="1042" alt="image" src="https://github.com/user-attachments/assets/b7f50521-07cd-4fdd-96b1-ff55525504b1">

**Platform (please complete the following information):**
 - OS: N/A
 - Version: 11.1.4

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Version N/A

**Additional context**
N/A

**Comment by thudugala** [comment]
@eddieyanez Documentation updated 

https://github.com/thudugala/Plugin.LocalNotification/wiki/%5BiOS%5D-Working-with-push-notifications
