### ISSUE TITLE
Prevent sending message when device is off

### ISSUE THREAD

**Issue by jrahma** [thudugala/Plugin.LocalNotification#51]
Hi,

How can I prevent LocalNotification from sending the message when device is switched on again?

For example, here is my scenario..

I am sending a reminder for prayer time so the app is storing the times and scheduling the messages, let's say the next prayer is at 13:00 and before that the user has switched off his device, and he switched it on at 13:30, in this case I don't want the message to be sent because the time for the prayer is 13:00 so he should not get the message for that prayer

**Comment by thudugala** [comment]
Need to investigate how iOS handles this situation.

@jrahma Do you get the Notification popup in iOS ?

**Comment by thudugala** [comment]
Will be fixed after 4.1.0
