### ISSUE TITLE
Local Notification Not showing on Android SDK 34 (same code works fine in SDK 32)

### ISSUE THREAD

**Issue by billylo1** [thudugala/Plugin.LocalNotification#510]
**Describe the bug**
No notification sent in Android SDK 34.

**To Reproduce**
Run sample on SDK 32 and 34 to compare.

**Expected behavior**
Same behavior in SDK 34.

**Screenshots**
Success in Android 32. <img width="303" alt="image" src="https://github.com/user-attachments/assets/ace70303-525d-41b8-9671-ed69f789f646">
No notification in SDK 34.

**Platform (please complete the following information):**
 - OS: Android
 - Version 14 (SDK 34), Physical Device and Emulator

**Smartphone (please complete the following information):**
 - Device: Pixel 7
 - OS: Android 14

**Comment by thudugala** [comment]
@billylo1 What's the plugin version you are using?

**Comment by billylo1** [comment]
I am on SDK 11.1.4 as well. Let me dive deeper into lower level details and recreate with a clean emulator installation.  Thanks for the quick response.

**Comment by billylo1** [comment]
I have discovered the root cause (device in Do Not Disturb mode).  Not related to this plugin.  Closing issue.

[Side note: the plugin works correctly in SDK 34 beta as well.]
