### ISSUE TITLE
Version 11.1.4 dont work with MAUI .NET8   Android

### ISSUE THREAD

**Issue by CedreLo** [thudugala/Plugin.LocalNotification#511]
Version 11.1.4 dont work with MAUI .NET8   Android

MSBUILD : java error JAVA0000: Error in /.nuget/packages/xamarin.androidx.collection.jvm/1.4.0.4/buildTransitive/net8.0-android34.0/../../jar/androidx.collection.collection-jvm.jar:androidx/collection/ArrayMapKt.class: 

MSBUILD : java error JAVA0000: Type androidx.collection.ArrayMapKt is defined multiple times: /.nuget/packages/xamarin.androidx.collection.jvm/1.4.0.4/buildTransitive/net8.0-android34.0/../../jar/androidx.collection.collection-jvm.jar:androidx/collection/ArrayMapKt.class, 

/.nuget/packages/xamarin.androidx.collection.ktx/1.2.0.9/buildTransitive/net6.0-android31.0/../../jar/androidx.collection.collection-ktx.jar:androidx/collection/ArrayMapKt.class

**Comment by thudugala** [comment]
@CedreLo 

https://github.com/thudugala/Plugin.LocalNotification/releases/tag/v11.1.4

Make sure to Add these Package Reference for android
```xml
<ItemGroup Condition="$(TargetFramework.Contains('-android'))">
  <PackageReference Include="Xamarin.AndroidX.Fragment.Ktx" Version="1.8.1" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.Common" Version="2.8.3" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData.Core" Version="2.8.3" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData.Core.Ktx" Version="2.8.3" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.Process" Version="2.8.3" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime" Version="2.8.3" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime.Ktx" Version="2.8.3" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModel" Version="2.8.3" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModel.Ktx" Version="2.8.3" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModelSavedState" Version="2.8.3" />
</ItemGroup>
```

**Comment by CedreLo** [comment]
ok will try

Thanks
