### ISSUE TITLE
Plugin.LocalNotification - FAILS TO BUILD IMMEDIATELY ON A BRAND NEW PROJECT.

### ISSUE THREAD

**Issue by RobDaytona** [thudugala/Plugin.LocalNotification#519]
THIS NUGET FAILS RIGHT OUT THE BOX ON A FRESH INSTALL.
STEPS TO REPRODUCE
1 - Create Brand New Maui App, (do not select the version with multiple projects per platform).
2 - Install [Plugin.LocalNotification] nuget
3 - Build:
Build Fails:
MSBUILD : java.exe error JAVA0000: Error in <test_path>/androidx.collection.collection-jvm.jar:androidx/collection/ArraySetKt.class:
MSBUILD : java.exe error JAVA0000: Type androidx.collection.ArraySetKt is defined multiple times:
<test_path>/xamarin.androidx.collection.jvm\1.4.0.4\buildTransitive\net8.0-android34.0....\jar\androidx.collection.collection-jvm.jar,
<test_path>/xamarin.androidx.collection.ktx\1.2.0.9\buildTransitive\net6.0-android31.0....\jar\androidx.collection.collection-ktx.jar
MSBUILD : java.exe error JAVA0000: Compilation failed

**Comment by Elvin-Thudugala-2degrees** [comment]
Please follow instructions in https://github.com/thudugala/Plugin.LocalNotification/releases/tag/v11.1.4

Make sure to Add these Package Reference for android
```xml
<ItemGroup Condition="$(TargetFramework.Contains('-android'))">
  <PackageReference Include="Xamarin.AndroidX.Fragment.Ktx" Version="1.8.1" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.Common" Version="2.8.3" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData.Core" Version="2.8.3" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData.Core.Ktx" Version="2.8.3" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.Process" Version="2.8.3" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime" Version="2.8.3" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime.Ktx" Version="2.8.3" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModel" Version="2.8.3" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModel.Ktx" Version="2.8.3" />
  <PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModelSavedState" Version="2.8.3" />
</ItemGroup>
```
