### ISSUE TITLE
API Level 26 Notification Not Working

### ISSUE THREAD

**Issue by ProfessorChristian** [thudugala/Plugin.LocalNotification#52]
I've put all the sample code in my application, and it worked perfectly fine on IOS and Android version 7.1 and below. But on Android 8.0 and above, it won't work. Maybe I missed something?

Here's the code i've inserted to my application.

var notifications = new NotificationRequest
            {
                NotificationId = 100,
                BadgeNumber = 10,
                Title = "sample title",
                Description = "sample description",
                ReturningData = "sample data",
                NotifyTime = DateTime.Now.AddSeconds(1),
                Android =
                {
                   IconName = "download.jpg",
                   ChannelId = CrossDeviceInfo.Current.Version.ToString(),
                   Priority = NotificationPriority.Max,
                   AutoCancel = false,
                   TimeoutAfter = TimeSpan.FromSeconds(5),
                   Ongoing = true,
                   Color = 255,
                   LedColor = 255
                }
            };
            NotificationCenter.Current.Show(notifications);

**Comment by thudugala** [comment]
Did you setup a Notification Channel ?

**Comment by ProfessorChristian** [comment]
Sorry sir, I now i'm in the minority here.

I thought that setting up the notification channels are for specific platforms only.

I've used Xamarin.Forms in setting up for both Android and IOS. 

but if so, where can I setup the notfication channel for android sir?

Thank you so much.

**Comment by thudugala** [comment]
try [[Android = 26] Notification Channel](https://github.com/thudugala/Plugin.LocalNotification/wiki/%5BAndroid---=-26%5D-Notification-Channel) wiki page

**Comment by ProfessorChristian** [comment]
![image](https://user-images.githubusercontent.com/51305140/66532287-75025700-eb41-11e9-97b6-73d514226901.png)

I tried the sample code on the given link sir, but prompts an error that .LocalNotification is nowhere to be found in the namespace Plugin.LocalNotification

**Comment by thudugala** [comment]
Can you please attach a sample project ?

**Comment by thudugala** [comment]
Sorry documentation mistake, it should be NotificationRequest not Plugin.LocalNortification.LocalNortification

**Comment by ProfessorChristian** [comment]
can I just share it to you via Cloud sir? the file, even having only simple UI and one button object, it already has the capacity of 108mb, and github won't allow uploading files larger than 10mb.

Thus, I already tried the NotificationRequest Class instead of Plugin.LocalNotification, still no luck.

**Comment by thudugala** [comment]
can you run the sample project https://github.com/thudugala/Plugin.LocalNotification/tree/master/Sample/NuGet

**Comment by ProfessorChristian** [comment]
The suggested sample project worked sir, on both Android 8.0 and Android 9.0, and it is perfect. 

But how did that sample project work? What did I miss? I'm now very desperate. :(

**Comment by thudugala** [comment]
There is no other way. You have to check line by line.

**Comment by ProfessorChristian** [comment]
Okay sir, I'll update once i'm through with it, thanks for the advice and for the help. I really appreciate your work for cross platform notification, really helped in making the code small. Thumbs up!

For the meantime, please don't close yet the issue, I may be have some follow-up questions later. Thank you sir.

**Comment by ProfessorChristian** [comment]
![image](https://user-images.githubusercontent.com/51305140/66535621-bea46f00-eb4c-11e9-80c6-177a428fdc3b.png)

The problem was, I forgot to insert this piece of configuration, I really thought that this config was for Specific Platforms only, and not intended for Xamarin Forms PCL

After inserting the code, it worked perfectly.
