### ISSUE TITLE
No repeat interval.

### ISSUE THREAD

**Issue by divyesh008** [thudugala/Plugin.LocalNotification#54]
there is no such a property which can be use to repeat a local notifications using this plugin.
For Example: If i want to set a schedule for Monday and Tuesday 5 pm and want to get notification every Monday and Tuesday of each week on Same time till I cancel the local notification than there is no scope to do that using this plugin.

**Comment by agharium** [comment]
This would be nice..

**Comment by agharium** [comment]
@thudugala this is something you plan to do?

**Comment by thudugala** [comment]
@agharium 

Not at the moment. waiting for  [Xamarin.AndroidX.Work.Runtime](https://www.nuget.org/packages/Xamarin.AndroidX.Work.Runtime/) to be released. 

Also:
Android and iOS has very different implementation on repeat.

**Comment by thudugala** [comment]
version [4.1.0](https://www.nuget.org/packages/Plugin.LocalNotification/4.1.0) now support. Repeating schedule notification next day at same time.

**Comment by divyesh008** [comment]
Not at the moment. waiting for Xamarin.AndroidX.Work.Runtime to be released.

Also:
Android and iOS has very different implementation on repeat. @thudugala you are right but there must be a solution. Right now I have make a Renderer to achieve

**Comment by divyesh008** [comment]
@thudugala

**Comment by thudugala** [comment]
@divyesh008 will you be able to do a PR?

**Comment by thudugala** [comment]
Added possibility to set Notification repeat Daily or Weekly

**Comment by agharium** [comment]
Great! Thanks!

I wonder if it wouldn't be possible to set notifications repeat interval to every x number of days?

Like a notification at same time every 2 days (monday, wednesday, friday, sunday, tuesday...)

**Comment by thudugala** [comment]
@agharium 
Will look into it, when I have free time. 
Will require a design change to support it. 

It would be nice, if you can test new changes.
