### ISSUE TITLE
Local Notification sent immediately not scheduled

### ISSUE THREAD

**Issue by jrahma** [thudugala/Plugin.LocalNotification#55]
Hi,

In the attached sample, Ia m using a PeriodicWorkRequest to be running every 30 minutes and inside the WorkRequest I am getting prayer times and then scheduling the time for the notifications.

I am showing the Times On MainPage,xaml just to refer to..

The problem that when I start the app then the push notification is sent immediately although it should be scheduled on the specific time which gives false alert about the prayer time

Also try to close the app several times and open several times you'll notice the push notification is being sent too

[LocalNotifications.zip](https://github.com/thudugala/Plugin.LocalNotification/files/3737335/LocalNotifications.zip)

**Comment by thudugala** [comment]
Not a bug related to this plugin. 

Error at AthanTime.DoWork line number 43, Task.Run is not awaited.

**Comment by jrahma** [comment]
@thudugala but the question is why the notification is sent although I have already set the schedule time for it so it should not be sent with or without the await.. Right?

**Comment by jrahma** [comment]
I also tried this:

```
Task.Run(async () =>
{
    fajer_time = DateTime.ParseExact(await SecureStorage.GetAsync("Fajer"), "HH:mm", CultureInfo.InvariantCulture);
    shurooq_time = DateTime.ParseExact(await SecureStorage.GetAsync("Shurooq"), "HH:mm", CultureInfo.InvariantCulture);
    dhuhur_time = DateTime.ParseExact(await SecureStorage.GetAsync("Dhuhur"), "HH:mm", CultureInfo.InvariantCulture);
    maghreb_time = DateTime.ParseExact(await SecureStorage.GetAsync("Maghreb"), "HH:mm", CultureInfo.InvariantCulture);
}).Wait();

```
with Wait()

but same problem

**Comment by thudugala** [comment]
Hi @jrahma,

if you set the notification time earlier than current date and time. it will fire immediately. 

```cs
var diff = (long)(notifyTime - DateTime.Now).TotalMilliseconds;
requestBuilder.SetInitialDelay(diff, TimeUnit.Milliseconds);
``

**Comment by thudugala** [comment]
Version 4.0.8 will not scheduled notification, if the notification time earlier than current date and time.
