### ISSUE TITLE
Xamarin.Forms' Android doesn't compile with R8/ProGuard active in Release mode

### ISSUE THREAD

**Issue by agharium** [thudugala/Plugin.LocalNotification#58]
**Describe the bug**
Xamarin.Forms' Android doesn't compile with R8/ProGuard active in Release mode.

**To Reproduce**
1. Activate R8/ProGuard with plugin installed and try to compile.

**Expected behavior**
Successful compilation.

**Platform:**
 - OS: Windows 10
 - Visual Studio 2019

**Smartphone:**
 - Device: Tested on Emulator and Samsung A5 2017
 - OS: Android
 - Version 9.0 and 8.0, respectively

**Additional context**
Error when R8 active: Compilation can't be completed because some library classes are missing.
Error when ProGuard active: "java.exe" exited with code 1

It builds normally when no code reducer is selected.
Haven't tested on Debug mode (where code reducer is useless).

**Comment by thudugala** [comment]
Please attach a sample project

**Comment by thudugala** [comment]
https://github.com/xamarin/AndroidSupportComponents/issues/168

**Comment by agharium** [comment]
[Sample](https://file.io/hasW3U)

Also, I noticed that on Android Oreo, the icon doesn't get any color (not even the gray when no color is set). Any idea why? I've only been testing on Android 8 and 9.

Check this out: 

Android 9 Pie:
![screenshot-2019-11-06_11 52 56 913](https://user-images.githubusercontent.com/28984633/68309407-276c0200-008d-11ea-8b41-900fcc6d4723.png)

Android 8 Oreo:
![WhatsApp Image 2019-11-06 at 12 52 27](https://user-images.githubusercontent.com/28984633/68309509-4ff3fc00-008d-11ea-9701-a9c0fafb1f00.jpeg)

As I know, this color feature was added on API 21, right? Not sure though.. Also, the icon file is exactly the same on both.

Thanks for the plugin, it's pretty good. I've been testing and if everything runs smooth, I'll use it on production.

**Comment by FredZaros** [comment]
HI! Does anyone has a solution or a workaround for this problem? Getting the same error in release mode, with code shrinker set to R8 and with Plugin.LocalNotification version 5.0.0 and 5.0.1.
More specifically, the following class is missing: androidx.paging.PositionalDataSource

**Comment by thudugala** [comment]
@GitBOUF please add comment to issue #72

**Comment by thudugala** [comment]
Has a solution in #72
