### ISSUE TITLE
No sound on android < 8.0

### ISSUE THREAD

**Issue by Freddyvdh** [thudugala/Plugin.LocalNotification#60]
**Describe the bug**
No sound is played on devices with Android 7.0 or before

It doesn't work if request.Sound is null or empty. It works if request.Sound is set e.g. to "Default". The sound file must not exist.

**Comment by thudugala** [comment]
@Freddyvdh Can you please attach a sample project

**Comment by Freddyvdh** [comment]
I just used the sample project.

**Comment by Freddyvdh** [comment]
I have downloaded the latest version and can't reproduce it. I will update my project and will have a look how it works.

**Comment by Freddyvdh** [comment]
I think it had been this [commit ](https://github.com/thudugala/Plugin.LocalNotification/commit/97b89e0f7fc230c11e42decdebf09ea43cbc0ed4)
