### ISSUE TITLE
Android 8 Icon Color issue 

### ISSUE THREAD

**Issue by thudugala** [thudugala/Plugin.LocalNotification#63]
[Sample](https://file.io/hasW3U)

Also, I noticed that on Android Oreo, the icon doesn't get any color (not even the gray when no color is set). Any idea why? I've only been testing on Android 8 and 9.

Check this out: 

Android 9 Pie:
![screenshot-2019-11-06_11 52 56 913](https://user-images.githubusercontent.com/28984633/68309407-276c0200-008d-11ea-8b41-900fcc6d4723.png)

Android 8 Oreo:
![WhatsApp Image 2019-11-06 at 12 52 27](https://user-images.githubusercontent.com/28984633/68309509-4ff3fc00-008d-11ea-9701-a9c0fafb1f00.jpeg)

As I know, this color feature was added on API 21, right? Not sure though.. Also, the icon file is exactly the same on both.

This could be a thing on my physical device.. it's a Samsung A5 2017 with the brand modified Android system and things..

And, by the way, thanks for the plugin, it's pretty good. I've been testing and if everything runs smooth, I'll use it on production.

_Originally posted by @agharium in https://github.com/thudugala/Plugin.LocalNotification/issues/58#issuecomment-550354346_

**Comment by thudugala** [comment]
Can you add the sample to zip file directly to GitHub comment

**Comment by agharium** [comment]
Yeah, sure.

[LocalNotificationAghariumSample_2.zip](https://github.com/thudugala/Plugin.LocalNotification/files/3947190/LocalNotificationAghariumSample_2.zip)

Had to zip it twice.

**Comment by thudugala** [comment]
It Works in my android 8.1 emulator

![image](https://user-images.githubusercontent.com/4112014/70571772-52ed8980-1c03-11ea-8597-1d5063c9ee61.png)

![image](https://user-images.githubusercontent.com/4112014/70571823-6bf63a80-1c03-11ea-9f0a-f72a2506012c.png)

**Comment by agharium** [comment]
Then probably it's just my crap Samsung's TouchWiz modded phone haha

Thanks for testing it out.
