### ISSUE TITLE
Future local notifications not working on v4.1.1 on Android

### ISSUE THREAD

**Issue by tomglanville-vsi** [thudugala/Plugin.LocalNotification#64]
**Describe the bug**
Updated from v4.0.8 to v4.1.1 and now notifications with a NotifyTime set in the future no longer work on Android. Instead the application output displays the following when the time is reached but no notification is displayed:
 `[WM-WorkerWrapper] Worker result SUCCESS for Work [ id=8b6a975d-8bb3-43c7-9dc8-23110e719443, tags={ md50e8eea8286f69b03ef3779df0abd57a6.ScheduledNotificationWorker, 4 } ] `

**To Reproduce**
1. Install v4.1.1 from nuget.
2. Setup notification request on Android for a future time.
3. Wait for notification to reach time.
4. No local notification is displayed.

**Expected behavior**
A local notification should appear like previous versions.

**Screenshots**

**Platform (please complete the following information):**
 - OS: Android
 - Version: All versions, recently tested on API 29

**Smartphone (please complete the following information):**
 - Device: Pixel 2XL
 - OS: Android
 - Version: API 29

**Additional context**

**Comment by thudugala** [comment]
@tomglanville-vsi try 4.1.2

**Comment by tomglanville-vsi** [comment]
Seems to be fixed in 4.1.2 - thanks!
