### ISSUE TITLE
Unable to Set Android Notification Icon

### ISSUE THREAD

**Issue by ericc0504** [thudugala/Plugin.LocalNotification#65]
**Describe the bug**
After setting NotificationRequest.Android.IconName, the notification icon on Android is still the default icon.

**To Reproduce**
1. Add notification icon (e.g. icon.png) to Resources/drawable.
2. Initial NotificationRequest object and set Android.IconName to "icon".
3. Try to push notification.
4. Notification icon is the default one

**Expected behavior**
Notification icon should be the customised one.

**Platform:**
 - Plugin Version: 4.1.1
 - OS: Android  9 (Pie)
 - Emulator: Pixel 2 XL

**Additional context**
Notification icon can be set only when setting NotificationRequest. Android.IconName to the resource id of the icon (which can be found inside Resource.designer.cs)

**Comment by thudugala** [comment]
@ericc0504 Can you please attach a same project

**Comment by ericc0504** [comment]
Attached with the demo which the top button will use the image file name and the bottom one will use the resource id.

[LocalNotiTest_Archive.zip](https://github.com/thudugala/Plugin.LocalNotification/files/4021719/LocalNotiTest_Archive.zip)

**Comment by thudugala** [comment]
@ericc0504 can you rename Home_Noti to homenoti and try

**Comment by ericc0504** [comment]
It works after renaming to "homenoti". Does it mean that there are some hidden constraints to the image file name?

**Comment by thudugala** [comment]
I think, It's xamarin andoid issue, 
```CS
Application.Context.Resources.GetIdentifier(iconName, "drawable", Application.Context.PackageName) 
```

does not return identifier if name has underscores
