### ISSUE TITLE
Can't install package from NuGet

### ISSUE THREAD

**Issue by yuraix** [thudugala/Plugin.LocalNotification#67]
When trying to install package from NuGet in VS 2019 16.4.3 I have this error:

Failed to add reference. The package 'Plugin.LocalNotification' tried to add a framework reference to 'System.Drawing.Common.dll' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
Reference unavailable.

**Comment by thudugala** [comment]
Cannot recreate the issue.

![image](https://user-images.githubusercontent.com/4112014/72689659-a0510500-3b78-11ea-8add-67fdfada2afa.png)
