### ISSUE TITLE
Only the ReturningData from the last notification is received

### ISSUE THREAD

**Issue by Husenap** [thudugala/Plugin.LocalNotification#68]
**Describe the bug**
When you schedule multiple notifications, and they have all been triggered, you will only get the ReturningData from the last notification that was triggered.

**To Reproduce**
1. Schedule one notification in 5 seconds with the Title and ReturningData = "1"
2. Schedule another notification in 10 seconds with the Title and ReturningData = "2"
3. Add a NotificationTapped handler that just prints the Data
4. Run the App
5. Wait for both notifications to appear
6. Click on one notification and see that it says "2" in the console
7. Click on the other notification, it will also say "2" in the console

**Expected behavior**
When I click on the first notification, I want to get the ReturningData that was scheduled with the first notification and when I click the second notification, I want the ReturningData for that.

**Platform:**
 - OS: Android
 - Version: Android 10.0 - API 29

**Smartphone:**
 - Device: Samsung SM-G973F
 - OS: Android 10.0
 - Version: API 29

**Additional context**
If you click on the first notification, before the second one appear, you get the correct data for it, and when you wait for the second one, it also has the correct data. The problem only occurs if you wait for both notifications to be shown.

**Comment by thudugala** [comment]
@Husenap Can you please attach a sample project?

**Comment by Husenap** [comment]
Thanks for the quick response, here's a sample project!
[NotificationTestApp.zip](https://github.com/thudugala/Plugin.LocalNotification/files/4112609/NotificationTestApp.zip)

**Comment by thudugala** [comment]
Try version 4.1.3

**Comment by Husenap** [comment]
Seems to be working for me now, thank you very much for the quick fix! :)
