### ISSUE TITLE
Notification icon is incorrect

### ISSUE THREAD

**Issue by yuraix** [thudugala/Plugin.LocalNotification#69]
1. Compile your sample project using Android 10
2. Run on emulator with android 9
3. Notification icon is fully white circle

I also tried icons from clipart (Android notification icons) and they also display incorrectly - always full square.

**Comment by thudugala** [comment]
@yuraix can please attach your sample project?

**Comment by yuraix** [comment]
I'm using your sample project and icon with name notif 
![notif](https://user-images.githubusercontent.com/60047232/73141190-45e10880-4092-11ea-8d02-525d04a55982.png)

**Comment by thudugala** [comment]
@yuraix app does not need to run for future notification to show up. Even if you restart the phone it should work.

**Comment by yuraix** [comment]
> @yuraix app does not need to run for future notification to show up. Even if you restart the phone it should work.

Pending notifications only works on stock Android. If you remove the application from recent list, then the notifications do not work on Xiaomi, ZenUI and other vendor roms. Tested many times. The stackoverflow site is full of these posts and simple solution is not exists. Only push notifications works well on not original Android.
[https://stackoverflow.com/questions/57617450/why-alarm-not-fired-when-i-remove-app-from-recent-apps](https://stackoverflow.com/questions/57617450/why-alarm-not-fired-when-i-remove-app-from-recent-apps)

**Comment by thudugala** [comment]
@yuraix Thanks for the update. Will look in to it

**Comment by thudugala** [comment]
Closing the issue as solution cannot be provided by this plugging as it's Andoid issue.
