### ISSUE TITLE
["SDK Assemblies Only" linking] Setted Android icon not showing on future notifications + future notifications don't appear at all

### ISSUE THREAD

**Issue by agharium** [thudugala/Plugin.LocalNotification#70]
**Describe the bug**
The setted icon is only used in notifications when app is running in **debug mode** or in **release mode with linking option set to none**.
In that last case, it uses the launcher icon instead of the icon set in the notification options. Also, this only happens when **NotifyTime** is set to future. I tested it with a past DateTime and it didn't appeared any notification. I believe this is expected behavior. Instant notifications works just fine.

**To Reproduce**
1. Set a notification with an icon and also set a launcher icon on the android project and a future **NotifyTime**.
2. Set linking option to "SDK Assemblies Only" in release mode.
3. Run app in release mode.
4. Future notifications shows up with the app launcher icon instead of the originally setted icon on code.

[IconSample.zip](https://github.com/thudugala/Plugin.LocalNotification/files/4121970/IconSample.zip)

**Expected behavior**
Future notification shown with the selected notification icon of when it was setted on code.

**Screenshots**
![screenshot-2020-01-27_22 37 58 446](https://user-images.githubusercontent.com/28984633/73228836-9752cb80-4156-11ea-9dfa-6418aeb4ee5a.png)
**☝️ Android 9: blank round icon because android expects a entirely white icon, and that's not the launcher icon case.**

![WhatsApp Image 2020-01-28 at 09 04 09](https://user-images.githubusercontent.com/28984633/73258681-00f9c680-41a5-11ea-8afb-eaabc9b72650.jpeg)
**☝️ Android 8: actually shows launcher entirelly instead of setted icon on the notification.**

**Platform (please complete the following information):**
 - OS: Android
 - Target version: 10

**Smartphone (please complete the following information):**
 - Device: Genymotion emulator and Samsung A5 2017
 - OS: Android
 - Version: 9 and 8 respectively

**Additional context**
I bet the other issue that I had (#63) is probably happening because of that and I see that #69 may have some similarity as well. The issue at #58 may also have some similarity with this "only works without any linking set" thing and such.

This also is the reason that another project of mine (my main one atm) is actually **not showing notifications when *NotifyTime* is set**. I just disabled linking and it's working flawlessly. It soon needs to go into production, so I just gotta deal with the big apk size. If you have any idea of what's going on, it would help a lot.

Thanks for the plugin, see you guys.

**Comment by thudugala** [comment]
Hi @agharium thanks for the detailed bug. Can you please attach your sample project?

**Comment by agharium** [comment]
Added sample and rewrote some of the issue. When I first wrote it, I was almost falling asleep.

And, just for future reference, one only needs to delete bin and obj project folders to decrease solution size drastically enough to zip it and send it on a GitHub issue 😄. That's the reason I didn't send the sample before hahah

**Comment by thudugala** [comment]
@agharium No solution found yet. 
The issue is that System.Xml.Serialization.XmlSerializer Deserialize and Serialize methods ignore object property "Android" when linking option set to "SDK Assemblies Only".

**Comment by agharium** [comment]
not even a workaround? besides turning off "SDK Assemblies Only" linking.

**Comment by thudugala** [comment]
I tried setting Skip Linking assemblies to System.Xml;System.Xml.XmlSerializer;System.Xml.Serialization. But did not work.

**Comment by thudugala** [comment]
@agharium try v5.0.0
