### ISSUE TITLE
Unable to install latest rc

### ISSUE THREAD

**Issue by jrahma** [thudugala/Plugin.LocalNotification#71]
Hi,

I am trying to install the latest v5.0.0-rc to my project but getting this error:

Package Plugin.LocalNotification 5.0.0-rc1 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Plugin.LocalNotification 5.0.0-rc1 supports:
  - monoandroid90 (MonoAndroid,Version=v9.0)
  - netstandard2.1 (.NETStandard,Version=v2.1)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)

Kindly help..

Thanks,
[Jassim](https://www.emiratesangels.org)

**Comment by jrahma** [comment]
Update netstandared 2.1 and solved

**Comment by moellerbj** [comment]
Unable to update to netstandard 2.1 because UWP does not support 2.1 yet. Any ideas?
