### ISSUE TITLE
Update to AndroidX

### ISSUE THREAD

**Issue by PureWeen** [thudugala/Plugin.LocalNotification#72]
**Is your feature request related to a problem? Please describe.**
Hello from the Xamarin.Forms Team!!

Just wanted to drop an FYI here that we've updated our 4.5 release to work with AndroidX.

There have been some issues with libraries that depend on *Xamarin.Android.Arch.Work.Runtime*
https://github.com/xamarin/Xamarin.Forms/issues/9546#issuecomment-586433091

**Describe the solution you'd like**
Provide MonoAndroid10.0 targets that use androidx

Ping me if you have any issues or questions

**Comment by thudugala** [comment]
@PureWeen I'm getting Missing class error When Code Shrinker is set to R8. Can you help ?

Missing class: androidx.paging.PositionalDataSource	LocalNotification.Sample.Android	C:\Users\elvin\source\repos\Plugin.LocalNotification\Sample\Direct\LocalNotification.Sample.Android\R8		

![image](https://user-images.githubusercontent.com/4112014/74599286-3fb7d800-50e4-11ea-9223-3553d9adc670.png)

![image](https://user-images.githubusercontent.com/4112014/74599294-5100e480-50e4-11ea-85a5-409af45bdab7.png)

**Comment by PureWeen** [comment]
@thudugala I think you can fix that with a proguard file
https://github.com/xamarin/Xamarin.Forms/blob/master/.nuspec/proguard.cfg


I'm also poking the AndroidX team see if they have any additional thoughts

**Comment by moljac** [comment]
@thudugala 

Proguard file might help, but repro sample would help me a lot. Can you provide one, please?

**Comment by thudugala** [comment]
Can you try https://github.com/thudugala/Plugin.LocalNotification/tree/master/Sample/NuGet

**Comment by thudugala** [comment]
@PureWeen https://www.nuget.org/packages/Xamarin.AndroidX.Work.Runtime/2.2.0 already has a proguard file. So will it be possible to know that missing, that I need to add ?

**Comment by thudugala** [comment]
@PureWeen as https://www.nuget.org/packages/Xamarin.AndroidX.Work.Runtime/ already has a  proguard file. I'm not sure what I need to add more. Can you Help ?

FYI:
It seems, when I the directly reference Xamarin.AndroidX.Work.Runtime in my android project and plugin source is directly referenced. It works.
https://github.com/thudugala/Plugin.LocalNotification/tree/master/Sample/Direct


But when plugin is reference from nuget package with direct reference to Xamarin.AndroidX.Work.Runtime in my android project. It does not work.
https://github.com/thudugala/Plugin.LocalNotification/tree/master/Sample/NuGet

**Comment by PureWeen** [comment]
@thudugala if you add a proguard file to your android project that keeps *androidx.paging.PositionalDataSource* does it work?

So if you add a proguard file with

-keep class androidx.paging.PositionalDataSource { *; }


does that work?

FYI on windows
https://docs.microsoft.com/en-us/xamarin/android/deploy-test/release-prep/proguard?tabs=windows#troubleshooting

**Comment by thudugala** [comment]
@PureWeen No it does not work.

https://github.com/thudugala/Plugin.LocalNotification/tree/master/Sample/NuGet

![image](https://user-images.githubusercontent.com/4112014/75145021-10950c80-575d-11ea-8b58-02c8cef3906b.png)

**Comment by GitBOUF** [comment]
Redirect from (#58)

HI! Does anyone has a solution or a workaround for this problem? Getting the same error in release mode, with code shrinker set to R8 and with Plugin.LocalNotification version 5.0.0 or 5.0.1.
More specifically, the following class is missing: androidx.paging.PositionalDataSource

EDIT: Only way I've found to compile was by adding the following to proguard.cfg:
-keep class androidx.paging.PositionalDataSource { *; }
-dontwarn androidx.paging.PositionalDataSource
But it crashes the app instantly on launch, so not a workaround sadly

**Comment by GitBOUF** [comment]
Found a workaround, seems like adding the following to proguard.cfg solved the problem in my case:
-keep public class androidx.work.impl.** { *; }
-keep public class androidx.paging.PositionalDataSource { *; }
-dontwarn androidx.paging.PositionalDataSource

**Comment by GitBOUF** [comment]
Updating the following nugets to these version:
- Xamarin.AndroidX.Work.Runtime Version=2.3.3
- Xamarin.AndroidX.Core Version=1.2.0

and adding the following to my proguard.cfg (ignore my previous comments):
- -keep public class androidx.work.impl.WorkManagerInitializer

fixed the issue for me. I'm able to link in release mode with code shrinker set to R8.
