### ISSUE TITLE
Get configured notifications

### ISSUE THREAD

**Issue by thomasgalliker** [thudugala/Plugin.LocalNotification#73]
**Is your feature request related to a problem? Please describe.**
When I configure local notifications for different topics, I might need to cancel them later and reschedule if needed. Until now, I have to keep track of the NotificationIds in order to cancel and reschedule notifications.

Furthermore, for debugging purposes, it would be nice to retrieve a list of all scheduled notifications.

**Describe the solution you'd like**
INotificationService cloud be extended with a method `IEnumerable<NotificationRequest> GetNotificationRequests();` (or similar)

**Describe alternatives you've considered**
Keep track of notifications in my own app code... which is something we could bring into this plugin.

Would be nice to discuss if you share my opinion on this request - or if it's completely off.

**Comment by thudugala** [comment]
@thomasgalliker Will look in to it. If I remember correctly, in Android WorkManager doesn't exposed that information.

**Comment by thomasgalliker** [comment]
I'm not sure if it is a feasible solution to store (at least parts of) the NotificationRequest information in a temporary list, for later access.

**Comment by thudugala** [comment]
This requires storing NotificationRequest information. As result, need to reference data storing plugin. As I think, it is best to keep this plugin referencing only the must needed. Will not implement this functionally for the moment.

**Comment by thomasgalliker** [comment]
Ok, yes, that's fine. Better keep it clean.
