### ISSUE TITLE
Grouped Notifications

### ISSUE THREAD

**Issue by ProfessorChristian** [thudugala/Plugin.LocalNotification#74]
Hi! This isn't really a feature request but a question, I just don't know any way to reach the developer of this library.

I would just like to ask if this library supports grouped notifications. Like a notification of the same kind stacks together or such.

Thank you!!

**Comment by thudugala** [comment]
@ProfessorChristian yes in Android, Check NotificationChannelRequest.Group

**Comment by ProfessorChristian** [comment]
Is there any tutorials for this sir?

**Comment by ProfessorChristian** [comment]
I just checked the NotificationChannelRequest.Group but somehow threw an Exception Unhandled, saying NotificationChannelGroup doesn't exist.

**Comment by thudugala** [comment]
Try https://github.com/thudugala/Plugin.LocalNotification/wiki/%5BAndroid---=-26%5D-Notification-Channel
Does not directly talk about Groups but good start

**Comment by ProfessorChristian** [comment]
I have already tried configuring the local notification sir, but I still don't know how to group them with specific groups.

**Comment by thudugala** [comment]
can you please attach a sample project with some photos of what are you trying to achieve?

**Comment by ProfessorChristian** [comment]
Let :
Phone A = Jude Joseph John
Phone B = Doctor Dave deb dev
Phone C = Joseph Jasper

In this scenario, Phone A messages Phone B, and Phone B receives a push notification that he got a message from Phone A. But when Phone C sends a message to Phone B, the notification Phone B got from Phone A is replaced by Phone C.
![Scene1](https://user-images.githubusercontent.com/51305140/74993394-cde5e280-5485-11ea-9195-69389d4f9283.PNG)
![Scene2](https://user-images.githubusercontent.com/51305140/74993395-cfafa600-5485-11ea-9182-bf6702ee1dd3.PNG)

It would have been nice if I can group them according to their kind of notification.

**Comment by ProfessorChristian** [comment]
And when I tried the NotificationChannelRequest.Group, it throws an exception.

Saying

![SampleGroup](https://user-images.githubusercontent.com/51305140/74994463-2ff41700-5489-11ea-8b1e-444568473e40.PNG)

**Comment by ProfessorChristian** [comment]
Did the error reproduced on your end sir?

**Comment by thudugala** [comment]
Try v5.0.1

https://github.com/thudugala/Plugin.LocalNotification/wiki/%5BAndroid%5D-How-to-group-notifications
