### ISSUE TITLE
Group Notification Bug

### ISSUE THREAD

**Issue by ProfessorChristian** [thudugala/Plugin.LocalNotification#75]
The Group Notification Configuration still throws an Exception. Still stating that NotificationChannelGroup doesn't exist.

Or maybe there's something wrong with my code. Can you please check?

**Platform (please complete the following information):**
 - OS: Android
 - Version 28

**Smartphone (please complete the following information):**
 - Device: Pixel 2 Emulator
 - OS: Android 9
 - Version : API Level 29

![SampleGroup](https://user-images.githubusercontent.com/51305140/75010739-d86d9f80-54b8-11ea-9c8b-27e1c2d1dd18.PNG)

![SampleGroup2](https://user-images.githubusercontent.com/51305140/75010620-904e7d00-54b8-11ea-8653-565f906ebee7.PNG)

Edit : I Upload the wrong screenshot, sorry.

**Comment by thudugala** [comment]
Have you had a look at https://github.com/thudugala/Plugin.LocalNotification/wiki/%5BAndroid%5D-How-to-group-notifications

**Comment by ProfessorChristian** [comment]
The Grouped notifications worked, But I still have to look up some materials or find out how to append notifications in one group.

Like :

Group Notifications : Notification A.

Then an Event triggers, producing Notification B.

Group Notifications : Notification A, Notification B.

**Comment by thudugala** [comment]
Please send a PR when you have time to improve documentation.
