### ISSUE TITLE
New Event for "NotificationReceived"

### ISSUE THREAD

**Issue by thomasgalliker** [thudugala/Plugin.LocalNotification#76]
This plugin provides the event NotificationTapped which fires when a user touches the notification alert. How can I get informed about the occurrence of an event if I can't rely on the user to touch the notification?

I need something like an "NotificationReceived" event which tells me that the notification is displayed to the user. I could use such an event to cancel a recurring notification series (e.g. by checking the EndDate and cancelling the notification).

Do you understand what my intention is?

**Comment by thudugala** [comment]
@thomasgalliker yes, can be done in next version.

**Comment by thomasgalliker** [comment]
Let me ideate about this enhancement. This is - what I think - we probably need to do:

- Create new event "`OnNotificationReceived`" in `INotificationService`, similar to `OnNotificationTapped` event.

**Android:**
- Raise `OnNotificationReceived` event just after we have created a new notification request:
_notificationManager?.Notify(request.NotificationId, notification);

**iOS:**
- Somewhere in `LocalNotificationDelegate` we get informed about the notification, so we forward the call ti `INotificationCenter.OnNotificationReceived` event.

If you don't mind I can create a code proposal or a PR for this change.

**Comment by thudugala** [comment]
@thomasgalliker Please send a PR 👍

**Comment by thomasgalliker** [comment]
Due to limitations in iOS, this can't be done. I'm sorry. iOS provides catastrophic backgrounding possibilities. We would have to setup a background fetch job ("PerformFetch") in order to re-schedule notifications and respect Start/EndDates. This is somewhat unreliable and hacky that I think we're better off with closing this issue.

One more thing to mention: The sample app allow to select Date+Time for future/recurring notifications. This did not work for me when I selected a date in the future, e.g. tomorrow + 2mins. The notification will be fired in 2mins, not in 1d+2mins because the NSDateComponents cannot take start/end date offsets into account.
