### ISSUE TITLE
No platform plugin found. Error

### ISSUE THREAD

**Issue by evagelos21** [thudugala/Plugin.LocalNotification#82]
Hi to you,
i have just install the 5.0.3 version and an error appears:
'[Plugin.LocalNotification] No platform plugin found.  Did you install the nuget package in your app project as well?'

My project target 9.0
![image](https://user-images.githubusercontent.com/9623090/78469239-ff5df900-7727-11ea-8c73-730cf628685f.png)

and my code is just simple:
`            
var request = new NotificationRequest
            {
                NotificationId = 100,
                Title = "Test",
                Description = "Description",
                BadgeNumber = 100,
                Android =
                {
                    IconName = "my_icon",                    
                },
            };           
            request.NotifyTime = DateTime.Now.AddSeconds(20);
            NotificationCenter.Current.Show(request);

`

**Comment by realrubberduckdev** [comment]
@thudugala Hi I am also getting the same error. Do you have a sample code to show how this package is supposed to be used? Guessing it should be in Xamarin.Android/Xamarin.iOS project and not netstandard common library? Unsure what the pattern is.

**Comment by thudugala** [comment]
https://github.com/thudugala/Plugin.LocalNotification/tree/master/Sample/NuGet

**Comment by thudugala** [comment]
Please follow as in readme.md

**Comment by realrubberduckdev** [comment]
Thanks @thudugala, sorry for being so daft!

**Comment by realrubberduckdev** [comment]
Hi, @evagelos21 As I understand (newbie to Xamarin here), the package version 5.0.3 needs your android project to be targeting Android 10.0.
![image](https://user-images.githubusercontent.com/22910832/78985074-c656c780-7b1f-11ea-9d4c-5e76b2c6e24e.png)

I changed the reference to be 4.1.4 in the sample and it worked for me. Hope this helps.

**Comment by thudugala** [comment]
@realrubberduckdev thank you for you answer. Closing issue.
