### ISSUE TITLE
Not found platform plugin

### ISSUE THREAD

**Issue by christmas96** [thudugala/Plugin.LocalNotification#86]
Hello. 

Your lib is really cool, but when I try to start application with installed plugin I get next error:
![image](https://user-images.githubusercontent.com/22245101/82577993-76463880-9b94-11ea-8d38-0338dc7440d1.png)

Project settings:
![image](https://user-images.githubusercontent.com/22245101/82578349-ef459000-9b94-11ea-8ef1-b1fb59a962b8.png)

Even in Android project getting error:
![image](https://user-images.githubusercontent.com/22245101/82578442-156b3000-9b95-11ea-8833-0ec25248f400.png)

If I hideNotificationCenter.CreateNotificationChannel(); I still get error with platform plugin.

I try your samples from NuGet but still get same error
'NotificationCenter' does not contain a definition for 'CreateNotificationChannel'

In lib versions <=4.1.3 all goes fin but with 5.0.4 version I got errors.

What problem can be?

Thanks in advance for your reply

**Comment by thudugala** [comment]
Hi can you please attach a sample project?

**Comment by christmas96** [comment]
Hello. I attach test project with same problem. 
[Test.zip](https://github.com/thudugala/Plugin.LocalNotification/files/4694321/Test.zip)

**Comment by thudugala** [comment]
@christmas96 Must use Xamarin.Forms 4.5.0.356 or above. Try updating  Xamarin.Forms

**Comment by christmas96** [comment]
Thanks for help, work fine. 
But now I need to resolve some bugs that comes with new Forms, especially on iOS)
