### ISSUE TITLE
Avoid opening application on Tap

### ISSUE THREAD

**Issue by abrantie1z** [thudugala/Plugin.LocalNotification#87]
this is more of  question sir. Is there way, say if a user clicks on the notification, that app doesnt get invoked?

**Comment by thudugala** [comment]
@abrantie1z Just to clarify,  You **do not** want app to open when notification is taped ? or When you tap on the notification app does not open ?

**Comment by abrantie1z** [comment]
i do not want the app to open when notification is tapped

**Comment by thudugala** [comment]
@abrantie1z If this a android app you comment out 
```cs
NotificationCenter.NotifyNotificationTapped(intent);
```
in Android MainActivity.

I will let you know about IOS after I look in to iOS

**Comment by abrantie1z** [comment]
alright. Thanks

**Comment by abrantie1z** [comment]
The plugin doesnt seem to work for me. I am using version 4.1.4 and i dont get any error and nothing shows up when i send a notification

**Comment by thudugala** [comment]
@abrantie1z Have you tried the same app https://github.com/thudugala/Plugin.LocalNotification/tree/master/Sample/NuGet

**Comment by abrantie1z** [comment]
No sir, let me do that and report back

**Comment by abrantie1z** [comment]
Sound = Resource.Raw.good_things_happen.ToString(),
this line gives me an error

**Comment by abrantie1z** [comment]
i can confirm, it works after following the 4.1.4  sample. but still have issue with this 
Sound = Resource.Raw.good_things_happen.ToString(). it seems there is no Raw folder in my android project

**Comment by thudugala** [comment]
@abrantie1z Please attach your sample project, so I can Have a look

**Comment by abrantie1z** [comment]
I have the issue fixed sir, thank you. But waiting for ios fix on when a user taps on the notification

**Comment by thudugala** [comment]
@abrantie1z It seems, **not** possible to, **not** to open the app when a local notification is clicked in iOS

https://stackoverflow.com/questions/25925303/how-to-disable-opening-app-when-user-tap-push-notification

https://stackoverflow.com/questions/28019991/do-not-open-the-app-when-a-local-notification-is-clicked-in-ios

**Comment by divyesh008** [comment]
Here is the code project link: https://www.dropbox.com/s/5479fphfsuu29em/NewControlsDemo.zip?dl=0

Steps to reproduce error:
1. Open the project and set android as startup project 
2. Change app mode to release and try to build application it will show exception 

Check this screen shot:

![Screenshot 2020-06-01 at 2 36 03 PM](https://user-images.githubusercontent.com/10617244/83394015-71477b80-a415-11ea-806e-05432c72a34a.png)
