### ISSUE TITLE
Mono.Linker.MarkException: Error processing method: 'System.Void Plugin.LocalNotification.Platform.Droid.NotificationServiceImpl

### ISSUE THREAD

**Issue by divyesh008** [thudugala/Plugin.LocalNotification#88]
**Describe the bug**
After updating Xamarin.Forms version to latest stable version 4.6.0.800 while making build in release mode getting error:

> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(5,5): Error XALNK7000: Mono.Linker.MarkException: Error processing method: 'System.Void Plugin.LocalNotification.Platform.Droid.NotificationServiceImpl::ShowLater(Plugin.LocalNotification.NotificationRequest)' in assembly: 'Plugin.LocalNotification.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve AndroidX.Work.OneTimeWorkRequest/Builder AndroidX.Work.OneTimeWorkRequest/Builder::SetInitialDelay(System.Int64,Java.Util.Concurrent.TimeUnit)
>   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod (Mono.Cecil.MethodReference reference) [0x00013] in <0275dd5bdfa6470181a4d79d0790489d>:0 
>   at Mono.Linker.Steps.MarkStep.MarkMethod (Mono.Cecil.MethodReference reference) [0x0004a] in <0275dd5bdfa6470181a4d79d0790489d>:0 
>   at Mono.Linker.Steps.MarkStep.MarkInstruction (Mono.Cecil.Cil.Instruction instruction) [0x00040] in <0275dd5bdfa6470181a4d79d0790489d>:0 
>   at Mono.Linker.Steps.MarkStep.MarkMethodBody (Mono.Cecil.Cil.MethodBody body) [0x000c2] in <0275dd5bdfa6470181a4d79d0790489d>:0 
>   at Mono.Linker.Steps.MarkStep.ProcessMethod (Mono.Cecil.MethodDefinition method) [0x00186] in <0275dd5bdfa6470181a4d79d0790489d>:0 
>   at Mono.Linker.Steps.MarkStep.ProcessQueue () [0x0001b] in <0275dd5bdfa6470181a4d79d0790489d>:0 
>    --- End of inner exception stack trace ---
>   at Mono.Linker.Steps.MarkStep.ProcessQueue () [0x00047] in <0275dd5bdfa6470181a4d79d0790489d>:0 
>   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue () [0x0000a] in <0275dd5bdfa6470181a4d79d0790489d>:0 
>   at Mono.Linker.Steps.MarkStep.Process () [0x00102] in <0275dd5bdfa6470181a4d79d0790489d>:0 
>   at Mono.Linker.Steps.MarkStep.Process (Mono.Linker.LinkContext context) [0x0000d] in <0275dd5bdfa6470181a4d79d0790489d>:0 
>   at MonoDroid.Tuner.MonoDroidMarkStep.Process (Mono.Linker.LinkContext context) [0x0000b] in <0275dd5bdfa6470181a4d79d0790489d>:0 
>   at Mono.Linker.Pipeline.ProcessStep (Mono.Linker.LinkContext context, Mono.Linker.Steps.IStep step) [0x0000d] in <0275dd5bdfa6470181a4d79d0790489d>:0 
>   at Mono.Linker.Pipeline.Process (Mono.Linker.LinkContext context) [0x0000f] in <0275dd5bdfa6470181a4d79d0790489d>:0 
>   at MonoDroid.Tuner.Linker.Run (Mono.Linker.Pipeline pipeline, Mono.Linker.LinkContext context) [0x00000] in <0275dd5bdfa6470181a4d79d0790489d>:0 
>   at MonoDroid.Tuner.Linker.Process (MonoDroid.Tuner.LinkerOptions options, Mono.Linker.ILogger logger, Mono.Linker.LinkContext& context) [0x00071] in <0275dd5bdfa6470181a4d79d0790489d>:0 
>   at Xamarin.Android.Tasks.LinkAssemblies.Execute (Java.Interop.Tools.Cecil.DirectoryAssemblyResolver res) [0x001dd] in <0275dd5bdfa6470181a4d79d0790489d>:0 
>   at Xamarin.Android.Tasks.LinkAssemblies.RunTask () [0x0001b] in <0275dd5bdfa6470181a4d79d0790489d>:0 
>   at Xamarin.Android.Tasks.AndroidTask.Execute () [0x00000] in <0275dd5bdfa6470181a4d79d0790489d>:0  (XALNK7000) 

**To Reproduce**
1. Update xamarin.forms to 4.6.0.800
2. Go to release mode and archive build  

**Expected behavior**
It should generate apk successfully 

**Platform (please complete the following information):**
 - OS: Android 
 - Version [10.0]

**Comment by thudugala** [comment]
@divyesh008 Can you please attach a sample project ?

**Comment by divyesh008** [comment]
No, can't share the project on it

**Comment by thudugala** [comment]
@divyesh008 I do not the original project. Just recreate the issue in a sample project and attach it.

**Comment by divyesh008** [comment]
@thudugala  Here is the code project link: https://www.dropbox.com/s/5479fphfsuu29em/NewControlsDemo.zip?dl=0
 
Steps to reproduce error:
1. Open the project and set android as startup project 
2. Change app mode to release and try to build application it will show exception 

Check this screen shot:

![Screenshot 2020-06-01 at 2 36 03 PM](https://user-images.githubusercontent.com/10617244/83394015-71477b80-a415-11ea-806e-05432c72a34a.png)

**Comment by thudugala** [comment]
@divyesh008 I updated PackageReference in your project. It's working now.
[NewControlsDemo.zip](https://github.com/thudugala/Plugin.LocalNotification/files/4714987/NewControlsDemo.zip)

**Comment by fazil1979** [comment]
@thudugala actually I have also fix the issue by following workaround:
-Update Net standard to 2.1
-Update Plugin.LocalNotification to latest version 5.0.4
-Remove unnecessary Android X nuggets
-Remove Xamarin.Android.Support.v7.MediaRouter

Still Can you explain me why this exception is raising with Android ?

**Comment by divyesh008** [comment]
@thudugala actually I have also fix the issue by following workaround:

- Update Net standard to 2.1
- Update Plugin.LocalNotification to latest version 5.0.4
- Remove unnecessary Android X nuggets
- Remove Xamarin.Android.Support.v7.MediaRouter

Still Can you explain me why this exception is raising with Android ?

**Comment by thudugala** [comment]
@divyesh008 

In android this plugin (version 5) depends on Xamarin.AndroidX.Work.Runtime. As you can see it's part of Xamarin.AndroidX. As a result, you need to target Android 10, Xamarin.Forms 4.5. 

So when you updated to Xamarin.Forms 4.6, you need to update this plugin also to version 5, Plugin version 4 will not work as old dependency Xamarin.Android.Arch.Work.Runtime does not with Xamarin.Forms 4.6

**Comment by divyesh008** [comment]
@thudugala 

But you do not have installed Xamarin.AndroidX.Work.Runtime in demo, so it comes default with version 5 plugin?

**Comment by divyesh008** [comment]
@thudugala 

Thank you for the knowledge sharing and for the solution too!
