### ISSUE TITLE
No notification when scheduled and when screen is OFF (Android)

### ISSUE THREAD

**Issue by Sebastiii** [thudugala/Plugin.LocalNotification#91]
**Describe the bug**
Hello, when setting a notification (by scheduler) and close the screen (like Android in standby)
There is no notification sent or at least my BT wrist set to vibrate on notification didn't start (while other notification is working) 

**To Reproduce**
1. Set a time on LocalSample APP for Android
2. Tap to send notification
3. Press power button on Android phone
4. Wait notification signal

**Expected behavior**
The BT wrist should vibrate like setup to react on localnotification APP

**Screenshots**

**Platform (please complete the following information):**
 - OS: Windows
 - Version 10

**Smartphone (please complete the following information):**
 - Device: Huawei Mate 20 Pro
 - OS: 10
 - Version EMUI 10.0.0.220

**Additional context**
If the screen in OS (even if LocalNotification APP is behind or reduced, the notification works and BT wrist too.

Thanks for your code :)

**Comment by thudugala** [comment]
@Sebastiii Can you try on deferent device ? A Samsung phone maybe.

**Comment by Sebastiii** [comment]
@thudugala I will try to find one for testing yes :)
Thanks.

**Comment by Sebastiii** [comment]
Hi :)
It's working so it's something to do with battery management
I did test your sample version 👍 

We can close the issue then 😊

I have one request, maybe I should opened a new subjet ?

Is it possible to add code to have the sample plugins running as service to have it start on reboot and always ON ?
Thanks.

**Comment by thudugala** [comment]
@Sebastiii this plugin is using Xamarin.AndroidX.Work.Runtime that Schedule notification task with WorkManager. https://developer.android.com/topic/libraries/architecture/workmanager. So it is already "running as service to have it start on reboot and always ON"

**Comment by Sebastiii** [comment]
Hi,
I surely made a mistake but when testing your sample APP, it didn't restart on fresh boot, need to add something in AndroidManifest.xml ?
Thanks
