### ISSUE TITLE
Impossible to install on xamarin form 4.7.0.968

### ISSUE THREAD

**Issue by AngeloLazzari** [thudugala/Plugin.LocalNotification#92]
Hi, we have a xamarin form cross platfotm project and we want to use your great plugin, but when we try to install on the common project visual studio says that the plugin cannot be installed... we installed directly to the Droid and Ios and all is working... 

So, the question are: 
- do we only install it on the specific Droid and ios? 
- Installing in that way, how we can use it from the common xamarin form project? I ask you that because all the logic actually is in the main project not in the specific platform... and when a notification will arrive we need to simply open a view and show the notification data... 

thank you very much!
Angelo

**Comment by chrisfoulds** [comment]
Are you running netstandard 2.1 ?

**Comment by thudugala** [comment]
Hi @AngeloLazzari 

Please read through the README.md in detail.

1. Install into your platform-specific projects (iOS/Android), 
2. Install into any .NET Standard **2.1** projects required for your app.
3. Must Use Xamarin.Forms **4.5.0.356** or above.
4. Project should target Android framework **10.0+**

look at the sample code here https://github.com/thudugala/Plugin.LocalNotification/tree/master/Sample/NuGet

**Comment by AngeloLazzari** [comment]
ok ok all is working now...i had 2.0 not 2.1 sorry ... and thanks for your help.

Angelo
