### ISSUE TITLE
.NET Standard 2.1 Dependency

### ISSUE THREAD

**Issue by Kiitoksia** [thudugala/Plugin.LocalNotification#93]
Hello,

Is there a reason that version 5.X requires .NET Standard 2.1 instead of 2.0?  We are using the library in a scenario where we can't realistically upgrade to 2.1.  Would be good to lower this to at least 2.0 for compatibility reasons.

**Comment by Kongzilla** [comment]
> Hello,
> 
> Is there a reason that version 5.X requires .NET Standard 2.1 instead of 2.0? We are using the library in a scenario where we can't realistically upgrade to 2.1. Would be good to lower this to at least 2.0 for compatibility reasons.

Same here.

**Comment by thudugala** [comment]
Hi, is your Android app targeting Android 10?

**Comment by Kiitoksia** [comment]
Our app is targeting Android 10, yes.  
I cloned the source locally and put the requirement back to .net standard 2.0 which resolved my issue, but would be good adjust main if possible.

**Comment by thudugala** [comment]
@Kiitoksia  Can you explain in bit more detail, if targeting Android 10, Why can't the shared project be updated to .NET Standard 2.1 ?

**Comment by Kiitoksia** [comment]
We are using other internal libraries that target .NET Standard 2.0 and are used in .NET Framework applications.  As .NET standard 2.1 is not compatible with .NET framework, we can't upgrade those libraries to 2.1.

.NET Standard 2.0 however supports Framework, so downgrading to this will help our scenario.

**Comment by thudugala** [comment]
Hi, I failed to understand just because your internal libraries are .net standard 2.0. Why can't you reference them in your Xamarin shared project that is .net standard 2.1.

**Comment by Kiitoksia** [comment]
Ahh...it was a very long day yesterday.  You're right, I could have stuck with 2.1, but thanks for adjusting the project anyway :)
