### ISSUE TITLE
Additional Repeat Schedules

### ISSUE THREAD

**Issue by mauro-dasilva** [thudugala/Plugin.LocalNotification#94]
As far as I can see you can only repeat notifications on a daily or weekly basis. It would be great if you could repeat the notifications on an hourly, and possibly even a minute basis.

**Comment by DonjetSalihi** [comment]
Yeah i would need this feature also.

**Comment by thudugala** [comment]
@mauro-dasilva it's bit of a tricky change in IOS. Will look into it

**Comment by thudugala** [comment]
@mauro-dasilva Published under v5.0.7

**Comment by mauro-dasilva** [comment]
Awesome, thanks so much bud. Appreciate the efforts!
