### ISSUE TITLE
Need to fetch all the already scheduled notifications

### ISSUE THREAD

**Issue by fun-works** [thudugala/Plugin.LocalNotification#95]
**Is your feature request related to a problem? Please describe.**
I want to retrieve all the scheduled notification and list them in my application.

**Describe the solution you'd like**
Provision to fetch my scheduled notifications.

**Describe alternatives you've considered**
There is a platform specific alternative which can be done. But it is not maintainable.

**Additional context**
I am using version 4.1.4 right now.

**Comment by thudugala** [comment]
Please look in to #73 Get configured notifications

**Comment by angelru** [comment]
is there any way to access? or do we have to implement it on our own?

**Comment by thudugala** [comment]
@angelru Please have your own database to manage push out notification.
