### ISSUE TITLE
Repeat feature with a predefined end date.

### ISSUE THREAD

**Issue by sikandaramla** [thudugala/Plugin.LocalNotification#97]
Hi,
As far as I can see, right now you have repeat feature but it is for the indefinite time, can we have an end date so repeat stops after that?

This will be a significant feature addition.

**Comment by thudugala** [comment]
@sikandaramla it's bit of a tricky change in IOS. Will look into it

**Comment by thudugala** [comment]
Added in version 6.1.0

**Comment by sikandaramla** [comment]
Awesome, thanks.
