### ISSUE TITLE
NotificationTapped is never fired on IOS 13.6

### ISSUE THREAD

**Issue by henriqueu96** [thudugala/Plugin.LocalNotification#99]
**Describe the bug**
When it try to catch the NotificationTapped event on IOS 13.6

`````
NotificationCenter.Current.NotificationTapped += (args) =>
{
    if (App.Current.MainPage is MainPage page)
    {
        page.SetLabelText("notification tapped");
    }
};
`````
The event is never fired.

**To Reproduce**
Get this code:
[TesteApp.zip](https://github.com/thudugala/Plugin.LocalNotification/files/5003748/TesteApp.zip)
Run with IOS 13.6
Touch the notification
Wait for the event to be fired

**Expected behavior**
The event should be fired and text label should be "notification tapped"

**Platform (please complete the following information):**
 - OS: IOS 
 - Version 13.6

**Smartphone (please complete the following information):**
 - Even on simulator

**Comment by henriqueu96** [comment]
There was an update on Xamarin.IOS, i will test it with the new version today, someone can take a look if it is not a local issue?

**Comment by thudugala** [comment]
@henriqueu96 do not have access to a MacBook right now. Will look into it as soon as possible.

**Comment by maciejpawlo** [comment]
I've noticed the same issue on Android 10 (Samsung Galaxy A7 (2018)). App opens, but the event isn't fired. It's a bit weird, because it has worked for me before, both on iOS and Android.

**Comment by maciejpawlo** [comment]
@thudugala have you looked into it?

**Comment by maciejpawlo** [comment]
Ok, I've just found out why NotificationTapped wasn't fired on my Android project. The reason of an issue was a custom launch screen, which was created as another acticity; with its MainLauncher attribute set as 'true' (just like there: https://docs.microsoft.com/en-us/xamarin/android/user-interface/splash-screen).

**Comment by nbsoftware** [comment]
My experience:
- called on Android (X)
- not called on iOS although UNUserNotificationCenterDelegate.DidReceiveNotificationResponse is indeed called
It definitely has worked before.

**Comment by henriqueu96** [comment]
Still not working

**Comment by Mataboge** [comment]
Event no working on IOS when App was killed. When App is on foreground or background the event is called. Please fix

**Comment by michaelconnolly1** [comment]
I also have a splash screen activity with mainlauncher = true and not getting the NotificationTapped event on Android. How do you fix the issue - do I move the Plugin.LocalNotification set up code from MainActivity to my splash screen activity?

**Comment by Mataboge** [comment]
@michaelconnolly1 check this out, it addresses your problem.

https://github.com/thudugala/Plugin.LocalNotification/issues/98#issuecomment-690357888
